src/parameterizations/vertical/MOM_bulk_mixed_layer.F90

This patch overrides the default clock sync (configured in FMS) for the
CPU clocks inside of the bulk mixed layer's loops.
This prevents model hangs due to an inconsistent number of clock syncs
when different ranks have different size domains.

Disable clock sync of in-loop BML timers

---

src/parameterizations/lateral/MOM_hor_visc.F90

1. Three typos are corrected.
2. An if-statement for better bound of the Laplacian viscosity at h-cell
is moved outside of the do-loops.

Correct a couple of typos in hor_visc

---

src/core/MOM_CoriolisAdv.F90
src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_barotropic.F90
src/core/MOM_continuity_PPM.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_sum_output.F90
src/diagnostics/MOM_wave_speed.F90
src/diagnostics/MOM_wave_structure.F90
src/framework/MOM_restart.F90
src/framework/MOM_write_cputime.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_geothermal.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_regularize_layers.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/user/user_change_diffusivity.F90

Added a new variable, initialized, to the control structures of modules that
had been testing for an allocated control structure to verify that it had been
initialized before it was going to be used, and then duplicated the tests using
this new variable.  This was done to enable us to go ahead with MOM6 PR #5,
which eliminated many of these checks when converting the control structures
from pointers in the parent modules to elements that are always there, and then
passing them as simple types instead of as pointers.  If we decide that we do
not need these tests after all, we can easily delete them, but until this is
discussed, this commit avoids losing the messages, as it was easier to do it
this way instead of trying to recreate them after they had been removed.  All
answers and output …

Add initialization tests using CS%initialized

---

src/ALE/MOM_regridding.F90
src/core/MOM.F90
src/core/MOM_barotropic.F90
src/core/MOM_density_integrals.F90
src/core/MOM_open_boundary.F90
src/core/MOM_variables.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_sum_output.F90
src/diagnostics/MOM_wave_speed.F90
src/initialization/MOM_coord_initialization.F90
src/initialization/MOM_fixed_initialization.F90
src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/user/BFB_initialization.F90
src/user/BFB_surface_forcing.F90
src/user/DOME2d_initialization.F90
src/user/DOME_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/Phillips_initialization.F90
src/user/RGC_initialization.F90
src/user/user_initialization.F90

Corrected the units or made other clarifications in comments describing 60
variables in 28 files.  In addition three unused (and unscaled) variables were
eliminated.  All answers and output are bitwise identical.

Corrected the descriptions of 60 variables

---

src/core/MOM_checksum_packages.F90
src/core/MOM_grid.F90
src/core/MOM_transcribe_grid.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_dyn_horgrid.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_shared_initialization.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_geothermal.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/tracer_example.F90

Add a dimensionally rescaled variable with the radius of the Earth in [L ~> m]
to the ocean_grid_type and dyn_hor_grid type to expand dimensional consistency
testing.  For now it exists along-side the previous variable with the radius of
the Earth in [m], which might be used in other drivers or user code that we are
not aware of.  All instances in the MOM6 code that were using the unscaled
variable G%Rad_Earth were changed to use the dimensionally scaled variable
G%Rad_Earth_L.  In addition, the code for setting up the grid metrics was
simplfied by completing the dimensional rescaling of its internal variables
and some grid rescaling factors that were no longer in use were eliminated.
As a part of this change, a unit_scale_type argument was added to the interface
for …

+Add G%Rad_Earth_L and related code simplification

---

src/core/MOM_barotropic.F90

Corrected the dimensional rescaling of the explicit bottom stresses that are
passed to btstep() when SPLIT_BOTTOM_STRESS = True.  Without this correction,
solutions would not pass the dimensional consistency tests in this case.
Thankfully, the parameter setting in question does not seem to be widely used,
and even if it is, answers will not change when Z_RESCALE_POWER = 0.  All
answers and output in the MOM6-examples test suite are bitwise identical.

(*)Fix rescaling when SPLIT_BOTTOM_STRESS = True

---

src/diagnostics/MOM_PointAccel.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Pass wind stresses to write_u_accel() and write_v_accel() in [R L Z T-2 ~> Pa]
without requiring external rescaling first.  Also cleaned up the dimensional
scaling in MOM_PointAccel.F90, so that all arguments and internal variables use
the dimensionally rescaled variables with cleaner and standardized syntax, and
there are comments clearly describing all real variables in this module.
Moreover, several rescaling bugs were corrected in these routines, so that if
there are velocity truncations, now the output will be invariant to rescaling,
whereas before some reported values were not being properly scaled back to MKS
units.  All answers and output from the MOM6-examples regression suite are
bitwise identical.

+Clean up dimensional rescaling in write_u_accel

---

src/core/MOM_forcing_type.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_opacity.F90

Applied appropriate rescaling for dimensional consistency testing to the net
heat and salt fluxes calculated in calculateBuoyancyFlux and used in the two
KPP_NonLocalTransport_...() routines.  Several comments describing variables
were also either corrected or added.  All answers are bitwise identical.

+Rescale fluxes passed to KPP_NonLocalTransport

---

src/user/DOME_initialization.F90

Bitwise identical refactoring of the code in DOME_initialize_sponges,
including renaming variables for greater clarity, adding variables for several
dimensional constants, and correcting comments.  This also includes more careful
handling of the DOME OBCs in DOME_set_OBC_data() to hopefully avoid some obvious
problems (noted in a comment about a "fight with T,S") that would arise if a
DOME case were set up that used temperature and salinity. Future revisions
should add more runtime parameters to specify the details of this case, but
properly doing so would involve changing the order of arithmetic; this has not
happened in this case.  All real variables in this module are now described in
comments.  All answers and output are bitwise identical.

Refactored DOME_initialize_sponges()

---

src/core/MOM.F90
src/core/MOM_CoriolisAdv.F90
src/core/MOM_continuity.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_grid.F90
src/core/MOM_porous_barriers.F90
src/core/MOM_transcribe_grid.F90
src/core/MOM_variables.F90
src/framework/MOM_dyn_horgrid.F90
src/initialization/MOM_shared_initialization.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

Initial implementation of porous topography modifying only cell face metrics (grid volumes are not modified). Cell faces are modified in the continuity scheme (`MOM_continuity_PPM.F90`), Coriolis acceleration (`MOM_CoriolisAdv.F90`), and the Rayleigh bottom channel drag (`MOM_set_viscosity.F90`).
Porous channels can be set in the `CHANNEL_LIST_FILE` using the following a similar template to existing barotropic channel restrictions:
barotropic: `[U|V]_width, min_longitude, max_longitude, min_latitude, max_latitude, width`
baroclinic:` [U|V]_WIDTH_POR, min_lon, max_lon, min_lat, max_lat, width, min_bathy, max_bathy, avg__bathy`
The porous topography implementation was tested for scaling and rotational consistency.

(+) porous topography implementation

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/FMS_cap/ocean_model_MOM.F90

Various minor code cleanup in the drivers/FMS_cap directory, including:
-  Rescaled the internal latent_heat variables in the control structure for MOM_surface_forcing_gfdl for improved dimensional consistency testing.
-  Removed the unused local variable PmE_adj in convert_IOB_to_fluxes().
-  Corrected the documented units or fixed spelling errors in several comments.
All answers and output are bitwise identical.

Minor code cleanup in drivers/FMS_cap

---

src/core/MOM_continuity_PPM.F90

Fixes an out-of-bounds k-index in MOM_continuity_PPM.F90 introduced with the porous topography update. Problem reported in #19 
Two commits:
- actual fix
- some cleanup outstanding from merge of #3 
Needs testing/review by @kshedstrom

Fix issue 19 porous face oob

---

config_src/drivers/solo_driver/MESO_surface_forcing.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
config_src/drivers/solo_driver/user_surface_forcing.F90

Code cleanup in the drivers/FMS_cap directory forcing files, including:
-   Rescaled several internal wind stress variables in the control structure for solo_driver/MOM_surface_forcing.F90 for improved dimensional consistency testing.
-   Added the variable Pa_to_RLZ_T2 to help clarify the conversion factors being applied to several hard-coded constant stresses.  These hard-coded constant wind stress magnitudes should be replaced with variables in wind_forcing_2gyre(), wind_forcing_1gyre() and Neverworld_wind_forcing() but this needs to be done carefully to avoid breaking existing solutions.
-   Removed or commented out unused variables, as appropriate.
-   Corrected or added documented units
-   Added comments describing all real variables in this directory.
-   Fixed spelling errors in …

Code cleanup in drivers/solo_driver forcing files

---

src/core/MOM_forcing_type.F90
src/tracer/pseudo_salt_tracer.F90

This PR fixes a problem with the dimensional rescaling of the tracers in the
pseudo_salt_tracer package and eliminates the essentially redundant netSalt
element from the forcing type.  This could change the output of some passive
tracer diagnostics when dimensional rescaling is in use, and it eliminates an
element from a transparent type, but all answers and output in the MOM6-examples
regression suite are bitwise identical.
- NOAA-GFDL/MOM6@111b3e7e6 +Eliminate forcing%netSalt
- NOAA-GFDL/MOM6@6c01c8d65 (*)Refactored and fixed pseudo_salt_tracer code

+(*)Pseudo_salt_tracer and forcing%netSalt

---

src/core/MOM_forcing_type.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_tracer_diabatic.F90

Changed the units of the optional surface and bottom tracer fluxes, sink rate, and
bottom tracer reservoir arguments to tracer_vertdiff() and tracer_vertdiff_Eulerian()
to fully rescaled units (like [Conc R Z T-1 ~> mol m-2 s-1] and [Z T-1 ~> m s-1]) for
greater dimensional consistency testing.
Only the two CFC packages are using the flux arguments, so these fluxes were rescaled
in those modules as well. Several unused variables or unnecessary pointers were removed
from the CFC tracer modules, and some comments were revised or added to indicate the
dimensions of a number of internal variables in these same modules.
All answers are bitwise identical in the MOM6-examples regression suite, and only
dimensional rescaling factors are changed (so nothing will have changed without
any …

+Rescaled flux arguments to tracer_vertdiff()

---

src/core/MOM.F90

This PR address issue https://github.com/mom-ocean/MOM6/issues/1546 .
1. The primary purpose of this PR is to fix the bug that `First_direction` is not correctly read from restart files. Previously, the code was only added in an if-block that rotate_index is true.
2. Some minor changes are introduced for clarification purposes. When index rotation is turned on, the meaning of the first direction can be ambiguous. It makes more sense to me that the integer parameter `FIRST_DIRECTION` from MOM_input and float field `First_direction` written to and read from the restart files have a physical meaning, i.e. their meanings and values should be independent from index rotation. 
* Local variable `first_direction` in subroutine `initialize_MOM` is slightly repurposed. Now it is only used to store …

Bug fix for reading First_direction from restart

---

.testing/Makefile

This patches updates the codecov uploader to the new version, replacing
the bash uploader to be phased out in 2022.
The uploader URL is now a configuable variable, and the coverage scripts
have been modified to accommodate changes in the uploader.
Under this new uploader, the coverage reports must be generated locally,
rather than relying on the bash script to call gcov.  So we now generate
these scripts based on the *.gcda output.

Testing: Codecov uploader update

---

src/core/MOM_dynamics_split_RK2.F90
src/diagnostics/MOM_diagnostics.F90
src/framework/MOM_diag_mediator.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_vert_friction.F90

This PR adds four new routines to within MOM_diag_manager.F90 to write out a
diagnostic based on the product of two arrays at velocity points, either as a
3-d diagnostic or a 2-diagnostic of the vertical sum.  The second commit in this
PR uses this new set of interfaces to simplify and clarify the diagnostic code
in 4 modules.  All answers are bitwise identical, but there are new public
interfaces.  The commits in this PR include:
- NOAA-GFDL/MOM6@2d053e6cb Use post_product_u for momentum budget diagnostics
- NOAA-GFDL/MOM6@3aad8ca44 +Add post_product_[uv] and post_product_sum_[uv]

+Add and use post_product_[uv]

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/FMS_cap/ocean_model_MOM.F90
src/core/MOM_forcing_type.F90

Retaing dimensional rescaling for several diagnostics:
- Apply dimensional rescaling of fluxes%net_mass_src to and the net_mass_src
argument to get_net_mass_forcing to [R Z T-1].
- Rescaled the patm argument of convert_state_to_ocean_type to [R L2 T-2]
and press_to_Z to [Z T2 R-1 L-2]; these are not actually exercised yet,
so this has a very limited scope, although three other local variables were
also dimensionally rescaled.
- Revised the line breaks in two calls to register_restart to place the units
and conversion factos on the same line, following a widespread code pattern.
- Used the scale argument in calls to global_area_integral or global_area_mean
for 6 diagnostics, so that 3 other primary variables can be calculated in
scaled units and rescaled via factors specified in the …

+Rescale fluxes%net_mass_src and other diagnostics

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/solo_driver/MESO_surface_forcing.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
config_src/drivers/solo_driver/user_surface_forcing.F90
src/user/BFB_surface_forcing.F90
src/user/MOM_controlled_forcing.F90
src/user/benchmark_initialization.F90
src/user/dumbbell_surface_forcing.F90
src/user/user_revise_forcing.F90

This commit revisits the units of the input arguments to the various ocean-
only surfaces forcing routines, including:
- Rescaled the units of the time intervals passed to the various forcing
routines to [T ~> s]
- Applied dimensional scaling to MOM_controlled_forcing.F90.  This code is
not yet in active use, so these changes can not change answers, but it is
now much closer to compliance with modern MOM6 standards, including improved
documentation, and could be ready to try without too much more effort.
- Documented the remaining real variables in benchmark_initialization.F90,
along with their units.
All answers are bitwise identical, but there are changes to the units of some
arguments in public interfaces.

+Rescale forcing arguments and revise ctrl_forcing

---

src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/diagnostics/MOM_obsolete_params.F90
src/ice_shelf/MOM_ice_shelf.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_regularize_layers.F90

This PR fixes some problems with the model potentially hanging, having a
memory leak, or having output that depends on the contents of an uninitialized
logical.  As a part of this change, a run time parameter that is no longer being
used was obsoleted, and because the MOM_parameter_doc files were changing anyway
an additional run-time parameter that does nothing was also obsoleted.  All
answers are bitwise identical, but the contents in some MOM_parameter_doc files
change.
- NOAA-GFDL/MOM6@f410f3c60 +Obsolete ETA_TOLERANCE_AUX
- NOAA-GFDL/MOM6@b0963d492 +Set find_salt_root if SHELF_THREE_EQN = .False.
- NOAA-GFDL/MOM6@eecadd2b3 Deallocate eta_PF_start to avoid a memory leak
- NOAA-GFDL/MOM6@f3ab52c8b +Remove clocks inside of j-loops

+Remove in-loop clocks and obsolete params

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90

The arrays passed to data_overrride need to be sized as the compute
domain. Added indices to pass to data_override.

 Update indexing of array passed to data_override.

---

src/core/MOM_continuity_PPM.F90

Corrected the expressionfs for the por_face_areaU arguments being passed to
`zonal_face_thickness()` to avoid the array out-of-bounds index errors highlighted in
MOM6 issue #24. Also added comments noting where the por_face_area arrays should
probably be included in the effective (relative) face thickness calculations that are
later used for finding the vertically averaged accelerations by the barotropic solver.
All answers and output are bitwise identical in cases that work, but this should
avoid some run-time or compile-time errors with some compiler settings.

Correct out of bounds index (por_face_areaU) bug

---

config_src/drivers/unit_drivers/MOM_sum_driver.F90
src/core/MOM_checksum_packages.F90
src/framework/MOM_unit_scaling.F90
src/ice_shelf/MOM_ice_shelf.F90
src/initialization/MOM_fixed_initialization.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/user/DOME_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/Kelvin_initialization.F90
src/user/Phillips_initialization.F90
src/user/benchmark_initialization.F90
src/user/shelfwave_initialization.F90
src/user/user_initialization.F90

This PR is a series of commits that make the previously optional
unit_scale_type arguments to 28 routines mandatory, mostly related to
the initialization of the bathymetry or the grid metrics.  This change realizes
something that was envisioned when these arguments were originally introduced,
but coordination with SIS2 means that they had to be optional when added to
routines that are also used by SIS2.  Now that SIS2 is using all of these
arguments, they can be made non-optional.  The resulting code should be much
easier to understand.  Because of a specific ODA initialization bug that was
corrected in these commits, answers might change slightly in nearly massless
layers for non-Boussinesq models with ODA enabled using the src/ocean_data_assim
code, but no such case exists in any of our …

+(*)Make unit_scale_type arguments non-optional

---

config_src/infra/FMS1/MOM_cpu_clock_infra.F90
config_src/infra/FMS2/MOM_cpu_clock_infra.F90

This patch fixes an error in the `sync` flag of the cpu clocks.
Previously, we would set the sync bit of a flag based on the presence of
sync, rather than testing if the value was true.  This would cause
potential hangs in any clock that set `sync`, including `.false.`.
This patch correctly replaces the single `ibset` call with an if-block
to either `ibset` or `ibclr`.

Bugfix: cpu clock sync error

---

src/core/MOM.F90
src/core/MOM_boundary_update.F90
src/core/MOM_variables.F90
src/diagnostics/MOM_sum_output.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/MOM_tracer_Z_init.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/advection_test_tracer.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/dye_example.F90
src/tracer/ideal_age_example.F90
src/tracer/nw2_tracers.F90
src/tracer/oil_tracer.F90
src/tracer/pseudo_salt_tracer.F90
src/tracer/tracer_example.F90
src/user/dyed_channel_initialization.F90
src/user/shelfwave_initialization.F90
src/user/supercritical_initialization.F90
src/user/tidal_bay_initialization.F90

Added unit_scaling_type arguments to various routines that had previously used
a unit scaling type, but did so via the G%US pointer, to make the type
dependencies more explicit and to avoid unnecessary pointer use.  It had been
the intention to make these arguments explicit from the time they were
introduced via a pointer in the ocean_grid_type as a temporary convenience.
The construct G%US%... was replaced with US%... wherever it was possible.
Also rescaled some local variables or corrected comments in oil_tracer.F90,
nw2_tracers.F90, and boundary_impulse_tracer.F90, and rescaled the units of
the dt argument to MOM_generic_tracer_column_physics from [s] to [T ~> s].
All answers are bitwise identical, although there are multiple changes to
public interfaces.

+Add US args and rescale dt arg to generic tracers

---

src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_open_boundary.F90
src/diagnostics/MOM_wave_structure.F90
src/initialization/MOM_shared_initialization.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/MOM_lateral_boundary_diffusion.F90
src/tracer/MOM_tracer_registry.F90
src/user/Idealized_Hurricane.F90
src/user/MOM_controlled_forcing.F90
src/user/SCM_CVMix_tests.F90
src/user/baroclinic_zone_initialization.F90

This PR rescaled the dimensions of the tidal amplitudes and frequencies used
internally in calc_tidal_forcing() and ramp-up times used by update_OBC_ramp()
and updateCFLtruncationValue() for nearly complete dimensional consistency
testing.  New unit_scale_type arguments were added to 5 routines, in the case of
calc_tidal_forcing() replacing a previous optional argument that was always
being used.  One overly short internal variable, "N", was renamed "nodelon" to
make its purpose clearer and easier to search for.  The comments documenting an
additional 31 variables or their units were also corrected.  All answers are
bitwise identical, but there are changes to the argument lists of 5 routines.
- NOAA-GFDL/MOM6@7b81cf227 +Rescale tides and ramp-up times
- …

+Rescale tides and ramp-up times

---

config_src/drivers/nuopc_cap/mom_cap.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
config_src/external/stochastic_physics/stochastic_physics.F90
src/core/MOM.F90
src/parameterizations/stochastic/MOM_stochastics.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90

Merge of the stochastic contribution (https://github.com/mom-ocean/MOM6/pull/1538) to dev/gfdl.
Resolved conflicts due to new stochastic arguments and transition of formerly optional arguments as mandatory.

PR #1538 merge to dev/gfdl

---

config_src/external/GFDL_ocean_BGC/generic_tracer.F90

Corrected uninformative comments describing the some of the arguments to the
stub routines in config_src/external/GFDL_ocean_BGC/generic_tracer.F90.  The
updated comments are consistent with how they are used in calls to these
routines and with the underlying actual generic_tracer code if they are actually
documented there.  The previous comments had been added to existing undocumented
code to satisfy the MOM6 requirement that there be a doxygen comment describing
every argument to every routine, in the hopes that someone with familiarity with
the generic tracer could work amend them to something more appropriate.
However, "Unknown" is neither an accurate nor an informative description, and
current MOM6 standards would demand that we reject any new code contributions
with such poor …

Correct comments describing generic_tracer args

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90

- A do_not_log depends on a logical that is only set conditionally. This initializes that logical when the corresponding parameter is not being read.
- Unfortunately, this change MOM_parameter_doc.all for the coupled models. The .all pipeline uses the gnu compiler which was initializing this logical as .true. and thus logging the new parameter when it should not have been. Intel and PGI were initializing with .false.

Fixes an uninitialized logical in FMS_cap

---

src/core/MOM_CoriolisAdv.F90
src/framework/MOM_checksums.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_CVMix_conv.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/user/ISOMIP_initialization.F90
src/user/Kelvin_initialization.F90
src/user/Phillips_initialization.F90

Eliminated 4 unnecessary 3-d allocatable arrays and 8 2-d diagnostic arrays
in CorAdCalc, and simplified the code calculating these diagnostics by using the
post_product_[uv] and post_product_sum_[uv] routines.  Also grouped the calls
that allocate the memory that is still needed for diagnostics.
This commit also includes a few other minor changes to clean up the
documentation of variable intents and unit documentation in a handful of other
places in the code:
- Add intent declarations to the arguments to chksum2d() and chksum3d()
- Corrected incorrect scale arguments for two (untested) checksum calls.
- Corrected the documented units in several comments.
All answers and output are bitwise identical.

Eliminate unneeded diagnostic arrays in CorAdCalc

---

src/core/MOM_barotropic.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_variables.F90

Use the por_face_area[UV] in the effective thickness calculations in
zonal_face_thickness and merid_face_thickness, so that they are more consistent
with their use elsewhere in the code for the relative weights in calculating the
barotropic accelerations.  Because these por_face_area arrays are still 1 in all
test cases, the answers are unchanged in any test cases from before a few weeks
ago, but there could be answer changes in cases that are using the very recently
added capability (in PR #3) to set fractional face areas.  This change was
discussed with Sam Ditkovsky, and agreed that there is no reason to keep the
ability to recover the previous answers in any cases that use the recently added
partial face width option.
This commit also expanded the comments describing the h_u and h_v …

(*)Use por_face_area in zonal_face_thickness

---

config_src/coupled_driver/ocean_model_MOM.F90
src/framework/MOM_diag_mediator.F90

This updates ESM4-maintenance to be compatible with fms2_io. It cherry-picks @nikizadehgfdl updates that are needed in mom. This needs to be updated for the EMS4 public model
This PR is needed for [MOM6-examples #349](https://github.com/NOAA-GFDL/MOM6-examples/pull/349)

Esm4 maintenance fms2io

---

src/ALE/MOM_ALE.F90
src/core/MOM.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_open_boundary.F90
src/core/MOM_variables.F90
src/framework/MOM_checksums.F90
src/framework/MOM_document.F90
src/framework/MOM_io.F90
src/framework/MOM_random.F90
src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/tracer/MOM_lateral_boundary_diffusion.F90

Eliminated a number of instances of non-standard syntax from that described in
https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide.  The changes include
enforcing the MOM6-standard 2-point indentation convention, replacing 'if(A)'
with 'if (A)', and changing logical comparison syntax like '.gt.' to '>' or
'.eq.' to '=='.  An old commented out block of code for debugging (detected by
its use of non-standard syntax) was also eliminated.  All answers and output are
bitwise identical.

Clean up non-standard syntax and whitespace

---

src/initialization/MOM_state_initialization.F90

Slightly modified the recently added subroutine calc_sfc_displacement to
document the units of its variables and to follow the MOM6 code standards from
https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide.  The changes include
white-space corrections, changing logical comparison syntax like '.gt.' to '>',
and explicitly identifying where array syntax is used.  All answers and output
are bitwise identical.

Standardize code in calc_sfc_displacement

---

src/ALE/MOM_ALE.F90

Changed the name and sign convention for the dzInterface argument to
remap_all_state_vars to reflect the convention used in the regridding code and
to reflect the fact that this is always a vertical displacement.  This change
eliminates a subtle array-syntax whole-array multiplication (by -1.) in one call
to remap_all_state_vars (this clearly violated MOM6 code standards), and it
corrects an actual sign error that will change answers (perhaps from a state of
catastrophic failure) in the code for the REGRID_ACCELERATE_INIT=True option if
REMAP_UV_USING_OLD_ALG is also true and the initial velocities that are being
remapped are non-zero.  Also added comments describing the real variables inside
of remap_all_state_vars to help clarify what they do.  Fortunately the situation
where answers …

+(*)Change the remapping dzInterface argument sign

---

src/parameterizations/lateral/MOM_hor_visc.F90

A bug fix and an associated cleanup:
- Commit f7fd4e4c7f79265 addresses a divide by zero encountered by @ElizabethYankovsky in the NeverWorld2 configuration while trying to use back-scatter.
- Commit fc3e3ac4df430b1 cleans up the capitalization of indices to follow https://mom6.readthedocs.io/en/dev-gfdl/api/generated/pages/Horizontal_Indexing.html#soft-convention-for-loop-variables
One question for @Hallberg-NOAA : could we ever encounter a divide by zero indicated by comment at top of fc3e3ac4df430b1 ?

Fix backscatter divide by zero

---

src/framework/MOM_io.F90

The read_variable_2d function was previously configured to only run if
the start and nread arrays matched the size of the field they were
accessing.  This was incompatible with the history of the function,
which had previously required a fourth time axis (of one record), then
was later modified to not require this axis.  As a result, there are now
files in use both with and without a time axis.
This patch relaxes this check to ensure that the read is quasi-2d, i.e.
the first two axes can read a segment of a 2d field, but will now
reshape the start and nread arrays to match the field being read.  Some
additional checks are also added to ensure that it only reads one 2d
slice.

read_variable_2d modified to accept 3 or 4 dims

---

config_src/infra/FMS2/MOM_io_infra.F90
src/ALE/MOM_regridding.F90

Merge of https://github.com/mom-ocean/MOM6/pull/1556 to dev/gfdl

Main to dev

---

src/core/MOM_checksum_packages.F90
src/diagnostics/MOM_spatial_means.F90
src/diagnostics/MOM_sum_output.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/MOM_lateral_boundary_diffusion.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/advection_test_tracer.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/dye_example.F90
src/tracer/ideal_age_example.F90
src/tracer/oil_tracer.F90
src/tracer/pseudo_salt_tracer.F90
src/tracer/tracer_example.F90

Use reproducing sums to obtain tracer stocks that are invariant to PE layout
for all tracer packages, and corrected the mean temperature reported to stdout
when DEBUG_CONSERVATION=True, so that it now really does give the mean.  All
solutions are bitwise identical, but the output does change.
- NOAA-GFDL/MOM6@f996d0919 (*)+Use reproducing stocks for all tracer packages
- NOAA-GFDL/MOM6@9b2debdec (*)+Reproducing tracer stocks
- NOAA-GFDL/MOM6@656a37285 Use global_mass_integral in lateral_bdry_diff
- NOAA-GFDL/MOM6@4dc1fd32c +Add global_mass_int_EFP
- NOAA-GFDL/MOM6@8e2e73e45 Report mean temperature from MOM_state_stats()

MOM6:(*)+Reproducing tracer stocks

---

config_src/infra/FMS1/MOM_coms_infra.F90
config_src/infra/FMS2/MOM_coms_infra.F90
src/core/MOM_verticalGrid.F90
src/framework/MOM_coms.F90
src/framework/MOM_domains.F90
src/framework/MOM_file_parser.F90

This patch includes several minor changes to the MOM_file_parser and
supporting modules in order to accommodate stronger unit testing.
It includes the following API changes:
- Removal of `static_value` from `get_param`
- Redefined `link_parameter` and `parameter_block` as private
- New functions: `all_across_PEs()`, `any_across_PEs()`
`static_value` was not used in any known experiments (outside of
internal GFDL testing), and the two derived types describe internal
operations within `MOM_file_parser`, so we do not expect any disruptions
from these changes.
A detailed summary of the changes are listed below.
- `assert()` is now used to detect same files with different IO units.
Detection of reopenend files of the same name but different IO unit
has been changed from `MOM_error(FATAL, ...)` …

(+) Refactor of MOM_file_parser

---

src/ALE/MOM_ALE.F90

Added a number of options to MOM_ALE to mimic options that are found in
Hycom.  By default, all answers are bitwise identical, but there are several
new runtime parameters.  The code changes include:
- Added the ability to use a different remapping scheme for velocities than
for tracers, using the new runtime parameter VELOCITY_REMAPPING_SCHEME
- Added the new runtime option PARTIAL_CELL_VELOCITY_REMAP to use partial cell
thicknesses for remapping at velocity points, which triggers a call to the
new internal routine apply_partial_cell_mask.
- Added the new internal routine mask_near_bottom_vel to allow MOM6 to mimic
Hycom in zeroing out the velocities in thin layers in a bottom boundary
layer with a thickness given by the new runtime parameter
REMAP_VEL_MASK_BBL_THICK, while the …

+Add ALE options mimicking Hycom

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/tracer/MOM_tracer_diabatic.F90

Enforce a minimum thickness of 0.5*Angstrom in the mixed_layer_restrat
routines.  The streamfunctions in these routines attempt to limit the
thicknesses to exceed Angstrom, but they can be less than this due to roundoff.
The new limit prevents thicknesses from becoming negative when Angstrom is set
to 0, but should not change any answers for test cases with positive values of
Angstrom.  Also added some comments describing variables and their units and
simplified the OMP directives.
Also corrected error messages in MOM_diabatic_aux.F90 to identify the file or
module where these messages come from, and modified an error message in
applyTracerBoundaryFluxesInOut so that it is written if the localized fault does
not happen to occur on the root PE.
All answers in the existing MOM6-examples …

(*)Avoid negative thicknesses in mixed_layer_restrat

---

src/tracer/MOM_offline_main.F90

This patch redefines `h_new` to match the shape of a center-point rather
than a v-face point.
Dynamic memory builds would have been unaffected by this, and older GCC
(~7.3.0) compilers appear to have not objected to the shape mismatch,
but this raised an error in newer GCCs (~9.3.0).
~This should not affect answers, since the loops never strayed into these
redundant undefined regions.~

bugfix: static h_new shape remaining_transport_sum

---

src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/diagnostics/MOM_spatial_means.F90

This PR adds new optional arguments to 7 routines, and then uses them to
correct the dimensional rescaling when HOMOGENIZE_FORCINGS = True.  All answers
in the existing MOM6-examples test suite are bitwise identical, but there are
revisions to public interfaces.  This PR addresses MOM6 issue #60, which can be
closed once this PR is accepted.  The commits in this PR include:
- NOAA-GFDL/MOM6@fa2832c11 +(*)Rescale variables with homogenize_forcing
- NOAA-GFDL/MOM6@b3e80f73f +(*)Add tmp_scale arguments to global_area_mean

+(*)Fix dimensional rescaling with HOMOGENIZE_FORCINGS

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_hybgen_remap.F90
src/ALE/MOM_regridding.F90
src/ALE/MOM_remapping.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90

This commit adds the ability to specify three remapping options derived from
Hycom's hybgen code.
- Adds the new module MOM_hybgen_remap, which contains the new subroutines
hybgen_plm_coefs, hybgen_ppm_coefs, and hybgen_weno_coefs
- Adds code to handle PLM_HYBGEN, PPM_HYBGEN and WENO_HYBGEN as valid entries
for specifying the ALE remapping schemes.  Also added descriptions of units
to some internal remapping variables.
- Adds the optional argument PCM_cell to regridding_main, remapping_core_h, and
remap_all_state_vars to specify layers that should use piecewise constant
remapping, regardless of the overall remapping scheme, to follow the approach
used in Hycom.  ALE_main uses these new optional arguments, although until
the Hybgen regridding code is added, they will always be set to …

+Add Hybgen remapping options

---

src/tracer/MOM_tracer_advect.F90

This change avoids an unnecessary copy of the tracer registry in
advect_tracer().  This should be more efficient, and it should facilitate the
development of improved tracer budget diagnostic capabilities.  It also adds
comments describing a few internal variables and their units.  All answers and
output are bitwise identical.

Avoid copying the tracer registry in advect_tracer

---

src/parameterizations/lateral/MOM_hor_visc.F90

Fixed the bug noted in issue #72 and excessive loop sizes noted in the
unresolved comments in a recent commit, and cleaned up other aspects of
MOM_hor_visc, mostly related to the code that is exercised when USE_GME=True.
- Fixed the bug with the wrong arrays being used when ADD_LES_VISCOSITY=True
that was noted in MOM6 issue #72.
- Corrected some of the overly large loop extents that were noted in unresolved
comments about MOM6 PR #65.
- Only log USE_KH_BG_2D if a Laplacian viscosity is used.
- Use extra calculations in the halos and marching in to avoid unnecessary halo
updates in smooth_GME if there multiple smoothing passes.
- Corrected the capitalization of some horizontal indices to follow the MOM6
convention for indicating the horizontal staggering position.
- Collected the …

+(*)MOM_hor_visc bug fix and loop size cleanup

---

src/diagnostics/MOM_obsolete_params.F90
src/initialization/MOM_state_initialization.F90

Stop logging the deprecated run-time parameter NEW_SPONGES, and always log
INTERPOLATE_SPONGE_TIME_SPACE as if NEW_SPONGES were not used.  This commit will
address MOM6 issue #46, which can be closed it is accepted.  This will change
the MOM_parameter_doc entries in some cases, but all answers are bitwise
identical.

+Stop logging NEW_SPONGES

---

src/diagnostics/MOM_wave_speed.F90

`c2_scale` was missing in the list of shared variables hence inducing the generation of spurious values in cn1 when internal_tides are active and openmp is used in the OM4 configuration:
solutions are now bitwise identical between openmp and non-openmp OM4 runs.

fix bug in wave_speeds when openmp is on

---

src/framework/MOM_file_parser.F90

This PR is a series of commits that will enable to MOM6 to handle much longer
input parameter lines, of up to 1000 characters in a single line, and with no
limit for lines with continuation.  This required the addition of a new internal
function and type, but all changes are private to the MOM_file_parser module.
This PR addresses the problems noted in MOM6 issue #75, which can be closed once
this PR is accepted.  All answers and output are bitwise identical in any cases
that worked before.
- NOAA-GFDL/MOM6@11328d440 Set INPUT_STR_LENGTH to 1024
- NOAA-GFDL/MOM6@5ee5daee3 Reduce the populate_param_data memory footprint
- NOAA-GFDL/MOM6@eb677ebd8 Support arbitrarily long parameter spec lines
- NOAA-GFDL/MOM6@f4dfb9648 +Better multi-line parameter …

+Gracefully handle longer input parameter lines

---

src/framework/MOM_error_handler.F90
src/framework/posix.F90
src/framework/posix.h

This patch introduces some limited support for error handling in a POSIX
environment.  A partial interface to the POSIX system calls is included
as part of the implementation of this feature.
An internal global logical flag, `ignore_fatal` is added to the
`MOM_error_handler` module which controls the behavior of `FATAL`
errors.  If true, then `FATAL` errors trigger a signal (here `SIGUSR1`)
which call a handler which restores the program to the earlier state.
This change allows us to test `FATAL` errors at runtime without stopping
program execution, so that we can cycle through multiple errors.
This feature is toggled with two new functions, `disable_fatal_errors()`
and `enable_fatal_errors()`.
This is implemented in part using POSIX system calls from the C standard
library (libc), using …

Error handler support

---

src/core/MOM.F90
src/core/MOM_barotropic.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_open_boundary.F90
src/core/MOM_verticalGrid.F90
src/framework/MOM_restart.F90
src/framework/MOM_unit_scaling.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90
src/initialization/MOM_state_initialization.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/tracer/boundary_impulse_tracer.F90
src/user/MOM_controlled_forcing.F90

This PR introduces code changes so that MOM6 writes out restart files in which
the dimensional rescaling of variables has been undone, although it is still
able to properly read older restart files that do have dimensionally rescaled
variables.  This PR also includes some new optional arguments to the framework
code that will allow SIS2 to do the same; this has been tested and works, but
will have to come in a subsequent PR to SIS2 after the version of MOM6 in
coupled configurations is updated.  In testing with this PR, the output
differences between cases with and without dimensional rescaling are confined to
MOM_parameter_doc.debug files.  This PR includes a number of new subroutine
arguments, but the solutions are bitwise identical.
The commits in this PR include: 
- …

MOM6: +(*)Write unscaled restart files.

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_hybgen_regrid.F90
src/ALE/MOM_hybgen_unmix.F90
src/ALE/MOM_regridding.F90
src/ALE/regrid_consts.F90
src/initialization/MOM_state_initialization.F90

This PR adds the ability to use Hybgen regridding, derived from Hycom
code.  There are two new files, MOM_hybgen_regrid.F90 and MOM_hybgen_unmix.F90,
which in turn add 15 new runtime parameters (with names like HYBGEN_...) to
control the hybgen code.  This new regridding option is specified by setting
REGRIDDING_COORDINATE_MODE="HYBGEN", and this new option is listed in the
MOM_parameter_doc files for cases that have USE_REGRIDDING=True.  There is also
a new publicly visible parameter, REGRIDDING_HYBGEN, in regrid_consts.F90.
In addition, the new routine regridding_preadjust_reqs is provided in
MOM_regridding.F90 to specify whether convective adjustment or hybgen_unmixing
should be done before regridding.  These pre-adjustment steps are no longer in
regridding_main.  Instead the calls do …

+Add option to use Hybgen regridding

---

.testing/Makefile

- Ever since a renaming of driver directories, the tests under "test-top-api", that are meant to check we are compatible with
each "cap", have been failing silently.
- This fixes the wrong arguments but does not fix the ability to fail silently which is somewhere deep inside mkmf.

Correct --with-driver args for coupled tests

---

config_src/external/GFDL_ocean_BGC/FMS_coupler_util.F90
config_src/external/GFDL_ocean_BGC/generic_tracer.F90
src/ALE/MOM_remapping.F90
src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/core/MOM_open_boundary.F90
src/diagnostics/MOM_PointAccel.F90
src/diagnostics/MOM_debugging.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_checksums.F90
src/framework/MOM_diag_mediator.F90
src/framework/MOM_diag_vkernels.F90
src/framework/MOM_domains.F90
src/framework/MOM_horizontal_regridding.F90
src/framework/MOM_random.F90
src/framework/MOM_write_cputime.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/tracer/MOM_lateral_boundary_diffusion.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/MOM_tracer_advect.F90

This PR resolves several issues which were detected by GCC's `-pedantic` flag.
Detailed explanations of changes are in the commit logs.  A summary is provided below.
* Forward step format descriptors (`x`) require an explicit step count.  Single steps are now explicit.  (`x` -> `1x`).
* The no-advance descriptor (`$`) is not standard, and is replaced with the `advance='no'` argument in `write()`
* All format descriptors should be separated by commas, even when implicitly distinguishable.
* Line continuation tokens applied to strings must appear at both the endline and start of the new line.
* A obsolescent statement function in `MOM_mixedlayer_restrat` has been redefined as an internal function.
* Subprogram specification requires that variables be declared before they can appear in …

A very pedantic pull request

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/drivers/solo_driver/MESO_surface_forcing.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/ALE/coord_adapt.F90
src/core/MOM_forcing_type.F90
src/diagnostics/MOM_wave_speed.F90
src/diagnostics/MOM_wave_structure.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_sponge.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/MOM_offline_aux.F90
src/tracer/MOM_tracer_diabatic.F90
src/tracer/MOM_tracer_hor_diff.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/ideal_age_example.F90

Modified the syntax of the logical comparisons with the various mask2d
variables to always check whether they are larger than 0.0, not 0.5 and use
similar syntax throughout the MOM6 code.  Because these arrays are always either
0.0 or 1.0, the answers are bitwise identical.

Standardized syntax in mask2d logical tests

---

config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS1/MOM_interp_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_interp_infra.F90
src/framework/MOM_coupler_types.F90
src/framework/MOM_diag_mediator.F90
src/framework/MOM_domains.F90
src/framework/MOM_horizontal_regridding.F90
src/framework/MOM_interpolate.F90
src/framework/MOM_io.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

Address undocumented interfaces by adding explicit interfaces to replaces one
level of the pass-throughs or eliminated them.  Specifically
- Eliminated global_field_sum() from MOM_domains, as it is no longer used
anywhere in the MOM6 code or drivers.  At the config_src/infra level, the
pass-through calls to mpp_global_sum are commented out in case there are
other versions of the MOM6 code that still use global_field_sum.
- Added explicit interfaces to horizontal_interp_init() and
time_interp_extern_init() in the config_src/infra rather that leaving them
as undocumented pass-throughs to the FMS code.
- Added the explicit subroutine stdout_if_root() to MOM_io.F90 to replace an undocumented
pass-through to the FMS stdout function.
- Added comments describing the publicly visible encoding …

+Document or eliminate undocumented interfaces

---

src/framework/MOM_string_functions.F90

Removed the unused and unnecessary function append_substring.  All answers
are bitwise identical, but an unused public interface is being eliminated.

+Remove append_substring

---

config_src/infra/FMS2/MOM_io_infra.F90

This patch modifies the `get_field_sizes` function to emulate the
FMS1 behavior when the requested `sizes(:)` is larger than the field's
number of dimensions.
In FMS1, `field_sizes` would always expect a `sizes` array of at least
size 4, and in the format of (nx, ny, nz, nt), and would lean on
netCDF attributes like `cartesian_axes` when assigning the values.
FMS2 lacks similar functionality, due its more general approach.
Previously, this was emulated in a way favorable to certain situations,
but raised issues in others.
This patch attempts to resolve the issue by using the
`categorize_axes()` function's ability to identify axes, either by
attributes, presumed names, or the `unlimited` property.

FMS2: get_field_sizes with FMS1 emulation

---

src/core/MOM_dynamics_split_RK2.F90

Added a call to set thickness_units, which are used in the units description
for the diagnostic deta_dt, which was recently added by
https://github.com/NOAA-GFDL/MOM6/pull/99, but with an uninitialized variable
being used for the units description.  This changes contents of one entry in the
MOM_available_diags, which will once again reproduce across runs and compilers.
All solutions are bitwise identical.

+Set thickness_units for use by deta_dt diagnostic

---

src/ALE/MOM_ALE.F90
src/core/MOM_barotropic.F90
src/core/MOM_open_boundary.F90
src/framework/MOM_horizontal_regridding.F90
src/initialization/MOM_state_initialization.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/MOM_lateral_boundary_diffusion.F90
src/user/DOME_initialization.F90
src/user/dyed_channel_initialization.F90
src/user/dyed_obcs_initialization.F90
src/user/supercritical_initialization.F90
src/user/user_initialization.F90

This PR is a duplicate of https://github.com/NOAA-GFDL/MOM6/pull/104, but is
being done on a branch so that it can be updated to reflect changes to dev/gfdl
without requiring a forced push to ESMG:dev/esmg.  This PR corrects a number of
dimensional rescaling and related issues that were identified with Kate's
regional Bering sea domain.
- Added unit conversion factors to some expressions setting the inverse of the
total depth to change them from [H-1] to [Z-1] in MOM_barotropic
- Added a missing unit conversion factor in horiz_interp_and_extrap_tracer calls
in MOM_ALE_sponge
- Eliminated the unused OBC function parse_segment_param_real and 4 other OBC
encoding integers, and made other OBC functions publicly visible
- Do needed unit conversion on the output arrays returned from …

+Fix some rescaling issues smoked out by the regional Bering domain

---

config_src/external/ODA_hooks/ocean_da_types.F90
config_src/external/ODA_hooks/write_ocean_obs.F90
config_src/external/drifters/MOM_particles.F90
config_src/external/drifters/MOM_particles_types.F90
config_src/external/stochastic_physics/get_stochy_pattern.F90
config_src/external/stochastic_physics/stochastic_physics.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90

This PR is a series of commits that will bring the code in three of the
config_src/external directories into closer alignment with the MOM6 style guide
at https://github.com/mom-ocean/MOM6/wiki/Code-style-guide.  There are also some
stochastics-related code changes in two parameterization/vertical files.  All
answers are bitwise identical, but there are some minor changes to interfaces.
- NOAA-GFDL/MOM6@e5175bfd1 Style compliance in external/ODA_hooks code
- NOAA-GFDL/MOM6@f72b143b2 +Style compliance in external/drifters code
- NOAA-GFDL/MOM6@c1c3fa786 +Revised stochastics code for style compliance

+Improve style compliance in config_src/external code

---

config_src/drivers/FMS_cap/ocean_model_MOM.F90
config_src/drivers/mct_cap/mom_ocean_model_mct.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/mct_cap/ocn_comp_mct.F90
config_src/drivers/mct_cap/ocn_cpl_indices.F90
config_src/drivers/solo_driver/MOM_driver.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90

Corrected unbalanced indentation levels and impose MOM6-standard 2-point
indentation in the config_src/driver codes, including both the FMS and mct caps
and the solo_driver.  The nuopc_cap is excluded from this commit because of the
huge number (over 1000) of lines there that use irregular indentation.  All
answers are bitwise identical, and only white space changes are included.

Impose standard indentation in most driver code

---

config_src/drivers/nuopc_cap/mom_cap.F90
config_src/drivers/nuopc_cap/mom_cap_methods.F90
config_src/drivers/nuopc_cap/mom_cap_time.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90

Corrected unbalanced indentation levels and impose MOM6-standard 2-point
indentation in the config_src/driver/nuopc_cap code.  There were over 1000 lines
that used non-standard or unbalanced indentation, so when reviewing this commit
the use of the "ignore whitespace" option might be very useful.  All answers are
bitwise identical, and only white space changes are included.

Impose standard indentation in nuopc_cap code

---

src/framework/MOM_horizontal_regridding.F90

Avoids using hard-coded dimensional tolerances in horizontal_regridding and
improves the documentation of the variables and their units in this file.
Without this change, calls to horiz_interp_and_extrap_tracer with a non-unity
conversion factor will exhibit unexpected changes in answers, and may have
wildly inappropriate amounts of smoothing of the interpolated values in arrays
that are initialized from z-space file.  However, the defaults are carefully
chosen to avoid changing answers in any cases that do not use rescaling of
tracer concentrations.  The specific changes include:
- Add a new optional argument tr_iter_tol to the horiz_interp_and_extrap_tracer
routines to set an appropriate dimensional threshold for when the post-fill
smoothing of tracers should be considered to be …

+(*)Fix a scaling bug in MOM_horizontal_regridding

---

src/ALE/MOM_ALE.F90
src/ALE/coord_slight.F90
src/core/MOM_density_integrals.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_wave_speed.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_linear.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_regularize_layers.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/user/BFB_initialization.F90
src/user/DOME2d_initialization.F90
src/user/DOME_initialization.F90
src/user/Neverworld_initialization.F90
src/user/Phillips_initialization.F90
src/user/RGC_initialization.F90
src/user/Rossby_front_2d_initialization.F90
src/user/adjustment_initialization.F90
src/user/circle_obcs_initialization.F90
src/user/dumbbell_initialization.F90
src/user/seamount_initialization.F90
src/user/sloshing_initialization.F90
src/user/soliton_initialization.F90
src/user/user_initialization.F90

This PR includes a series of commits that standardize some of the less-used
interfaces or arguments to the MOM6 equation of state routines and how they are
used in a few places.  There is a particular emphasis on the consistency of
which routines use rescaled variables or MKS variables, so that essentially all
of the dimensional rescaling related to the equation of state now occurs inside
of the routines in MOM_EOS.F90.  By design, there is not expected to be any
noticeable performance impact.  The vast majority of calls to the equation of
state routines are unaltered.  All answers in test cases are bitwise identical,
but there are a few (probably untested) places where the rescaled units of some
arguments are corrected.
Changes of note include:
- Refactored MOM_density_integrals to use …

+Revise equation of state interfaces for consistency

---

.codecov.yml
.github/actions/testing-setup/action.yml
.github/workflows/coverage.yml
.testing/Makefile
ac/configure.ac
config_src/drivers/unit_tests/MOM_unit_test_driver.F90
config_src/infra/FMS1/MOM_coms_infra.F90
config_src/infra/FMS2/MOM_coms_infra.F90
src/framework/MOM_coms.F90
src/framework/MOM_unit_testing.F90
src/framework/testing/MOM_file_parser_tests.F90

This patch introduces new features to support unit testing of the MOM6
source code.  The patch includes two new modules (MOM_unit_testing,
MOM_file_parser_tests), two new classes (UnitTest, TestSuite), and a new
driver (unit_testing).
A UnitTest object consists of the following:
* The test subroutine
* Test name (for reporting)
* A flag indicating whether the test should fail (FATAL)
* An optional cleanup subroutine
The UnitTest objects are gathered into a TestSuite object, which
provides a batch job for running all of its tests.
The use of these features is demonstrated in a driver, unit_tests, which
runs the tests provided in the MOM_file_parser_tests module
This patch also includes changes to the ".testing" build system.
* The optional FCFLAGS_COVERAGE has been removed from the testing …

MOM_file_parser unit test implementation

---

src/diagnostics/MOM_sum_output.F90
src/framework/MOM_diag_remap.F90

Fixed two minor bugs in the MOM6 output when run with Z_RESCALE_POWER not
equal to 0.  All solutions are bitwise identical, but some of the diagnostic
output files have minor changes.  With these corrections, several output files
are now unaltered by internal dimensional rescaling.  The specific bug fixes
are:
- Avoid using a rescaled depth as the vertical coordinate label in z-space
output files.  Only the coordinate label is impacted, but this bug fix avoids
the chance of having silly values for this coordinate.
- Rescale the depths back to mks units before taking their checksum for storage
in the MOM_sum_output file.  With this bug, the depth list file might be
unnecessarily recreated with a new run with different scaling, but the file
itself is fine.

Fix bugs in output files with rescaled heights

---

src/core/MOM_open_boundary.F90

Corrected two bugs in the code handling the unscaling of tracers in east-west
open boundary segments.  Both changes bring the east-west code into (closer?)
agreement with the north-south code, and it might explain some recent reports of
strange behavior.  However, the fact that the existing MOM6-examples pipeline
tests do not detect this bug reveals a clear shortcoming in the suite of test
cases with OBCs that are currently being testing with MOM6 code changes.  These
bugs were introduced to dev/gfdl on May 22, 2022 (one week before this fix) as a
part of PR# 122 (https://github.com/NOAA-GFDL/MOM6/pull/122).

(*)Corrected OBC restart scaling bugs

---

src/parameterizations/lateral/MOM_MEKE.F90

Corrected a bug in a dimensional rescaling factor that will cause test cases
using MEKE with MEKE_EQUILIBRIUM_ALT = True to fail dimensional consistency
testing.  However, answers are unchanged when no rescaling is used.  This minor
bug has been in the code since the MEKE_EQUILIBRIUM_ALT was first introduced in
2019.  All answers in the existing MOM6-examples test suite are bitwise
identical.

Fix a rescaling bug with MEKE_EQUILIBRIUM_ALT

---

README.md

- url was pointing to "latest" which is not a version. Pointing to "main" instead.

Fixes badge for doc build status

---

config_src/infra/FMS2/MOM_io_infra.F90

This patch replaces the instances of findloc() with a new function,
find_index.  They should be functionally equivalent.
findloc() is a F2008 intrinsic which returns the index of the first
instance of a value in an array.  Support is still spotty on some older
compilers in active use, so this function is the safer alternative.

Replace findloc() with user-defined find_index

---

config_src/infra/FMS2/MOM_io_infra.F90

This patch fixes two major bugs in the find_index function:
* Incorrect variable declarations have been fixed
* The API is now followed, and assumes that it's looking for .true.
Obviously the previous patch had not been tested with the FMS2 infra or
a compatible FMS library.  This was has been checked against FMS
2022.02.
~I have also added an export statement to the .testing Makefile to allow
for configuration of the FMS branch within the CI test suite.~

Bugfix: find_index in FMS2 infra

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90
src/ice_shelf/MOM_ice_shelf_state.F90
src/ice_shelf/user_shelf_init.F90

Applied dimensional rescaling of all of the ice shelf temperature and salinity
variables that could be modified without requiring any changes at the driver
level.  There is a new unit_scale_type argument to MOM_IS_diag_mediator_init,
mirroring what is done in MOM_diag_mediator_init.  This commit also includes
changing the initial values in the stencil array from -1 to 0, but this
initialization appears to be unnecessary.  A large number of comments were
added, corrected, or modified.  All answers in the test cases are bitwise
identical.

Rescale ice shelf temperatures

---

src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90
src/user/DOME_initialization.F90

Use the new scale argument to time_interp_external to standardize where the
dimensional rescaling occurs for the OBC code, and to use properly dimensionally
rescaled internal variables.  This includes the addition of the new function
scale_factor_from_name, and there are new verticalGrid_type and unit_scale_type
arguments to initialize_segment_data.  All answers are bitwise identical and
are passing dimensional consistency testing, including in Alex Bozec's Gulf of
Mexico regional configuration, but there are new arguments to public interfaces.

+Clean up dimensional rescaling in OBC code

---

ac/Makefile.in
ac/deps/Makefile.fms.in
ac/makedep

- Works with system python (2.7) and later (tested with 3.9)
- Processes #include without invoking cpp
- Currently naive regex without honoring/interpretting CPP macros
- Calculates link dependencies directly rather than invoking "make"
to infer the link list
Changes relative to the bash version of makedep:
- No longer adding/using a macro "SRC_DIRS" since it was only used to record the arguments for regenerating the makefile. Now we record the command line to achieve the same re-run ability.
- Adds new option "-e" to link all externals.
- This was the default before but I think in time we can make this approach more intelligent and figure out which functions/subroutines are used elsewhere.
- Processes F90 `include` to build dependencies
- Currently not tested with nested `include`s …

Re-developed makedep in python 

---

.github/actions/macos-setup/action.yml
.github/actions/testing-setup/action.yml
.github/actions/ubuntu-setup/action.yml
.github/workflows/coupled-api.yml
.github/workflows/coverage.yml
.github/workflows/expression.yml
.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml
.github/workflows/other.yml
.github/workflows/perfmon.yml
ac/configure.ac
src/framework/posix.F90
src/framework/posix.h

This patch makes several changes to to provide better support for MacOS
and BSD-like systems.
Autoconf now includes macros to determine the following:
* The name of sigsetjmp: `sigsetjmp` (BSD) or `__sigsetjmp` (Linux)
* The size of `jmp_buf` and `sigjmp_buf`.  Also renamed to `SIZEOF_*` to
align with autoconf macro name conventions.
The Linux defaults are retained in `posix.h`, but autoconf will now
override these values.
Two CI tests for MacOS have also been added, replicating the "stencil"
and "regression" tests.
The testing-setup has also been restructured to account for multiple
platforms.  Currently only Ubuntu and MacOS are tested.

MacOS Support

---

src/core/MOM_isopycnal_slopes.F90
src/core/MOM_stoch_eos.F90
src/diagnostics/MOM_diagnostics.F90

Added missing unit conversion factors in two calls to register_diag_field and
modified the comments describing the units of some temperature and salinity
variables in code that was recently added to the recently main branch of MOM6
via dev/ncar, reflecting the rescaling of temperatures and salinities that is
now in the dev/gfdl branch.  Without this change, these diagnostics will fail
the dimensional consistency testing for temperature and salinity.  All answers
are bitwise identical, but there is a case change of the units of a variable
in the available_diags files.

+Fix diagnostic conversions in code from dev/ncar

---

src/user/DOME2d_initialization.F90
src/user/DOME_initialization.F90

This PR includes two sets of changes that change answers in the DOME and
flow_downslopes test cases.  One change corrects an obvious bug in
DOME2d_initialize_temperature_salinity that reset the temperatures to 0 with the
ZSTAR and SIGMA vertical coordinates.  The other set of changes to the DOME
initialization is mathematically equivalent to what was there before, but
revises the expressions setting up the DOME test case to use runtime parameters,
more gracefully accomodates changes to those parameters, and replaces some
divisions with multiplication by a reciprocal.  There are changes to the DOME
MOM_parameter_doc.all file, and answer changes in the DOME and two variants of
the flow_downslope test cases.  This commits in this PR include:
- NOAA-GFDL/MOM6@73420c8d3 +*Use runtime …

*+DOME initialization cleanup and bug fix

---

src/core/MOM.F90
src/tracer/MOM_offline_main.F90
src/tracer/MOM_tracer_advect.F90
src/tracer/MOM_tracer_hor_diff.F90
src/tracer/MOM_tracer_registry.F90

This PR includes commits that simplify the interface to use the tracer
registry to write checksums, while retaining the old interface, and then uses
these new interfaces in additional checksum calls to help with debugging.  It
also corrects a minor problem with that could avoid segmentation faults in
certain cases with y-direction open boundary conditions but no tracer
reservoirs.  All answers in the MOM6-examples test suite are bitwise identical,
and it seems very likely that all cases that previously worked will be bitwise
identical.
- NOAA-GFDL/MOM6@4a50417dc (*)Corrected OBC allocated tests in advect_y
- NOAA-GFDL/MOM6@1e1f67913 Added tracer debugging checksum calls
- NOAA-GFDL/MOM6@f4f06749e +Overload MOM_tracer_chksum to use tracer registry

+(*)Improve tracer debugging

---

src/initialization/MOM_state_initialization.F90

Corrected the dimensional rescaling factors in two calls to
set_up_ALE_sponge_field for temperature and salinity for time-varying fields
being read in from an input file.  These had been given the inverse of the
correct values.  An optional scale argument was also added (with its default
value) in the call to set up ALE sponge velocities, for greater clarity of what
this call is doing.  This commit should address an issue noted by Kate Hedstrom
when evaluating the first draft of PR #1577 from dev/gfdl to main.  All answers
are bitwise identical in cases where dimensional rescaling of temperature and
salinity are not being applied, and answers with the rescaling of temperature
and salinity should now reproduce those without the rescaling.

(*)Fix set_up_ALE_sponge_field call T & S scaling

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/framework/MOM_restart.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/advection_test_tracer.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/ideal_age_example.F90
src/tracer/nw2_tracers.F90
src/tracer/oil_tracer.F90
src/tracer/pseudo_salt_tracer.F90
src/user/MOM_wave_interface.F90

Call set_initialized for variables after they are initialized, when their lack
of initialization was detected via query_initialized.  This commit reproduces
the model's behavior prior to the removal of the code that set the initialized
flag within query_initialized in https://github.com/NOAA-GFDL/MOM6/pull/149, and
it completes the set of changes that was envisioned when set_initialized was
added in https://github.com/NOAA-GFDL/MOM6/pull/152.  All answers are bitwise
identical.

Call set_initialized after query_initialized

---

src/core/MOM_open_boundary.F90

Change suggested by @Hallberg-NOAA to shorten some expressions.

Seg offset

---

ac/Makefile.in
ac/configure.ac

Where we had placed the dependency discovery (makedep) was leading to some small annoyances:
- The dependency generation was being invoked twice
- The dependency generation was not invoked when source code was changed.
Now:
- `./configure` creates config.status Makefile and Makefile.dep
- `./config.status` recreates Makefile and Makefile.dep
- `make depend` recreates Makefile.dep
- `make` will conditionally recreate Makefile.dep
Changes:
- Add dependency of Makefile.dep on source code in Makefile.in. This allows `make` to know when to run `makedep`.
- Fix syntax issue for AC_CONFIG_COMMANDS which caused errors to be issued without stopping.
Side note: the system works perfectly well if we comment out the "AC_CONFIG_COMMANDS" line in configure.ac to invoke makedep. This is because `make` …

Fixes minor issues with ac/make process

---

src/diagnostics/MOM_wave_structure.F90

Revised the MOM_wave_structure code to avoid using array syntax in
calculations and subroutine arguments.  While making these changes, several
incorrect or missing variable unit descriptions in comments were identified and
corrected.  This set of changes is mathematically equivalent, but will result in
changes at the level of roundoff, either because the order of sums was changed
or because divisions are replaced by multiplication by a common reciprocal.
Some debugging safety checks were moved inside of a logical test of the debug
flag for efficiency.  One dimensionally inconsistent expression (in vertical and
horizontal distances) was corrected, so that it should now pass the dimensional
consistency checks.
This commit will change answers in any cases that depend on this code, but …

(*)Avoid array syntax math in MOM_wave_structure

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
src/initialization/MOM_state_initialization.F90
src/user/BFB_initialization.F90
src/user/DOME2d_initialization.F90
src/user/Kelvin_initialization.F90
src/user/dense_water_initialization.F90
src/user/dumbbell_initialization.F90
src/user/shelfwave_initialization.F90

Set default values in all get_param calls for USE_REGRIDDING.  Previously,
there had been 4 calls where this was missing, which led to the problems noted
at https://github.com/mom-ocean/MOM6/issues/1576.  This PR will allow that issue
to be closed.  Also used the default argument in a get_param call for INPUTDIR,
although that case would not change any behavior because the value was set
before the get_param call.  A fail_in_missing argument was added to the FMS_cap
call to get_param for GUST_2D_FILE, mirroring what is done for the solo_driver
code, but cases where this was actually missing were very likely to have failed
later anyway, but without an explicit error message.  This PR could change
unpredictable behavior in cases where USE_REGRIDDING is not explicitly set, but
all answers are …

(*)Set defaults in USE_REGRIDDING get_param calls

---

src/ALE/MOM_ALE.F90
src/diagnostics/MOM_diagnostics.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/tracer/MOM_offline_main.F90

Modified the units for 10 thickness or thickness tendency diagnostics to write
them in their native units (e.g., kg m-2) when run in non-Boussinesq mode. These
changes were proposed in https://github.com/mom-ocean/MOM6/issues/1565 and
discussed and agreed to at the MOM6 dev call on 4/25/22.  Previously these
diagnostics had been converted to approximate thicknesses in m using a constant
reference density, but this was only accurate to about 0.1% and could be
misinterpreted.  A number of other (more commonly used) thickness-related
variables were already being written in their native units, and this makes the
model's output more self consistent.  All solutions are bitwise identical, but
some diagnostics will change when run in non-Boussinesq mode.

+Non-Boussinesq thickness diagnostics in kg m-2

---

.github/actions/testing-setup/action.yml
.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml
.testing/Makefile
ac/deps/Makefile

Two changes in this PR:
* Resolves the MacOS build issues by removing the environment variables pointing to gcc-11 and gfortran-11 compiler (which seem to no longer be supported). The CC is removed and FC now just points to gfortran.
* If the dependency ./configure fails for any reason, the config.log output is now streamed to the CI log, which should make future debugging easier.

MacOS CI fix + verbose builds on error

---

src/tracer/DOME_tracer.F90
src/tracer/ISOMIP_tracer.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/RGC_tracer.F90
src/tracer/advection_test_tracer.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/dye_example.F90
src/tracer/dyed_obc_tracer.F90
src/tracer/ideal_age_example.F90
src/tracer/nw2_tracers.F90
src/tracer/oil_tracer.F90
src/tracer/pseudo_salt_tracer.F90
src/tracer/tracer_example.F90

Made the WARNING error messages that were issued if a tracer package
registration routine is called with an associated control structure into FATAL
errors, as suggested by github.com/mom-ocean/MOM6/issues/1444.  A tracer package
could be used twice, but it would require the use of separate control structures
for each instance.  This change will bring down the model in a case that
probably should not be running.  All solutions are bitwise identical in any
cases that run, and all MOM6-examples test cases work exactly as before.

Fatal error if a tracer package is registered twice

---

.gitmodules

This patch modifies the URLs of the git modulues from the main
repositories to local mirrors at @mom-ocean.
Since the MOM6 sourc code is hard-coded to particular hashes, there is
no benefit to linking to the most recent versions of these codes.  And
linking to local forks controlled by us will protect us from potential
removal of the commits in these repositories.

Point gitmodules to mom-ocean forks

---

src/parameterizations/stochastic/MOM_stochastics.F90

Modified output from MOM_stochastics to stdout to only occur if the
stochastics code is actively being used, and to only register stochastics
related diagnostics if they are actually available.  Also, initialized some
stochastics arrays to 0 when they are allocated.  Some indenting and white space
were also changed to bring the MOM_stochastics code into closer compliance with
MOM6 code standards.  All answers are bitwise identical, but there will be fewer
inappropriate entries in the available_diags files, and some output to stdout
will only occur when appropriate and be subject to verbosity control.

+Remove inappropriate stochastics output

---

.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml

GitHub appears to have restored their compiler alias conventions on
their MacOS nodes.  This patch restores those variables.

CI: Restore MacOS compiler variables

---

config_src/drivers/FMS_cap/ocean_model_MOM.F90

- Ice shelf needs to be initialized prior to
ocean state initialization. This fixes any cases with
an ice shelf using the FMScap.

Fix ice shelf initialization

---

src/parameterizations/vertical/MOM_set_viscosity.F90

Added the new runtime parameter CHANNEL_DRAG_MAX_BBL_THICK, to allow the
CHANNEL_DRAG parameterization to use the full dynamically determined depth of
the bottom boundary layer, or to use a fixed maximum thickness, regardless of
the settings of other parameters, although for now the default value is set
based on the settings of USE_JACKSON_PARAM and DRAG_AS_BODY_FORCE in order to
reproduce existing solutions by default.  There are new entries in some
MOM_parameter_doc files.  All answers in the MOM6-examples test suite are
bitwise identical, and this test suite has been tested and works with revised
values of this parameter.

+Add runtime parameter CHANNEL_DRAG_MAX_BBL_THICK

---

src/core/MOM_open_boundary.F90

This PR is to fix nudged OBCs on tracers when both inflow and outflow length scales of tracer reservoirs are zero. 
At open boundaries, tracers are updated based on tracer reservoirs. For flow entering reservoirs (exiting interior domain), reservoirs are updated with interior tracers and reservoir tracers in the previous time step. For flow existing reservoirs (entering interior domain), reservoir is updated based on nudged data applied at open boundaries and reservoir tracers in the previous time step. However, this does not work if length scales of tracer reservoirs are zero, in which case reservoirs are not updated.  (@MJHarrison-GFDL )
In this fix, it is assumed that if length scale is 0, the impact of associated data is dominant, i.e.,
1. In case the reservoir out-length-scale is 0 …

+Fix nudged OBCs for tracers

---

.testing/Makefile

This patch extends the REPORT_ERROR_LOGS flag behavior to also report
the error log of failed codecov uploads.
I expect there's little we can do on our end, but more information will
at least help to understand the problem.

Report error logs from codecov upload fail

---

src/core/MOM.F90
src/core/MOM_variables.F90
src/parameterizations/lateral/MOM_interface_filter.F90

Added the new module MOM_interface_filter to allow for a biharmonic or
other order of filtering of the interface heights.  This new capability
is enabled with the new runtime parameter APPLY_INTERFACE_FILTER, and with
rates of filtering determined by the new runtime parameters
INTERFACE_FILTER_TIME, INTERFACE_FILTER_MAX_CFL, INTERFACE_FILTER_ORDER and
INTERFACE_FILTER_ISOTROPIC.  Set APPLY_INTERFACE_FILTER to True and provide a
positive timescale in INTERFACE_FILTER_TIME to enable the filtering.
The comments describing THICKNESSDIFFUSE and THICKNESSDIFFUSE_FIRST were
also updated to clarify the distinctions with the new capabilities or to
clearly identify which parameters work together.
By default, all answers are bitwise identical, but there are new entries or
modified comments in the …

+Add an interface filtering capability

---

ac/configure.ac
src/framework/posix.F90
src/framework/posix.h

The `sigsetjmp` function is part of the POSIX, but is not required to be
defined as a symbol, and may be implemented as a macro.  Since Fortran
C bindings require a symbol, we cannot bind to macro implementations.
The prior implementation assumed a Linux glibc binding of `__sigsetjmp`
(accessed by a `sigsetjmp` macro), but this did not work on BSD and
MacOS builds, which have a dedicated `sigsetjmp` symbol.
Although the autoconf build included a macro to test and assign the
symbol to `SIGSETJMP_NAME`, this did not resolve builds based on mkmf or
similar build systems, and would fail to compile.
To resolve this, the `SIGSETJMP_NAME` points to a placeholder function,
`sigsetjmp_missing` which permits compilation but raises an error if
called.
Since this function is only used in our unit …

Disable sigsetjmp for default compilation

---

config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/core/MOM.F90
src/core/MOM_porous_barriers.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_vert_friction.F90

This is a series of commits designed to add new capabilities to handle the
near-surface viscous coupling between thin near-surface layers when there is a
wind stress, and to strongly discourage the use of the KVML-derived viscosities
that scale with the inverse of the distance from the free surface squared. 
These new capabilities have been determined to work as intended in variants of
the double gyre test case with additional thin layers added in the lightest
density range.  These changes should allow us to address the source of the
problems that have plaguing runs with an ice-shelf that do not use a bulk
mixed layer.
In addition, the friction velocity, forces%ustar, is now being set with several
idealized wind forcing prescriptions where it previously had not been set. 
Also, the von …

+(*)Add new viscosity options and discourage the use of KVML

---

src/diagnostics/MOM_obsolete_params.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/_V_diffusivity.dox

As discussed in the dev call today, make HENYEY_IGW_BACKGROUND_NEW obsolete.

Obsolete the HENYEY_IGW_BACKGROUND_NEW option.

---

src/core/MOM_barotropic.F90

This patch modifies the calculation of barotropic weight functions
wt_[uv] to a more vectorizable form.  The if-blocks used to evaluate the
piecewise function was replaced with a sequence of min/max evaluations,
which are vectorizable.
A nondimensional subroundoff term is also introducted to address the
division by zero in the evaluation of 1 - 0.5 * Instep / visc_rem.
When visc_rem is zero, this term will never be selected by the max()
operator, since it is negatively asymptotic.  When visc_rem is
sufficiently large to accept this term, the value of subroundoff is too
small to modify the significand of the floating point value.
In our runs, the overall time of btstep was reduced by 6%.
Experiment: benchmark
Platform: AMD Ryzen 5 2600
Compiler: gfortran 12.2
Flags: -O3 -mavx
Timer: (Ocean …

Barotropic weight vectorization

---

src/parameterizations/vertical/MOM_vert_friction.F90

Add calls to query_averaging_enabled to avoid unnecessary extra calls to post_data for diagnostics that will never be used in vertvisc and vertvisc_coef. All answers are bitwise identical, but the C.I. testing appears to fail because there are fewer calls to post_data.

Avoid extra post_data calls from vertvisc

---

src/core/MOM_barotropic.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Updated the default values for KV_ML_INVZ2, BAROTROPIC_TIDAL_SAL_BUG,
LAYER_Z_INIT_IC_EXTRAP_BUG, and KAPPA_SHEAR_VERTEX_PSURF_BUG. Also completed obsoleting of HENYEY_IGW_BACKGROUND_NEW.  This PR will change answers in some cases, unless the MOM_input files already included lines with the following settings, or otherwise explicitly set these parameters:
KV_ML_INVZ2 = 0.0
BAROTROPIC_TIDAL_SAL_BUG = False
LAYER_Z_INIT_IC_EXTRAP_BUG = False
KAPPA_SHEAR_VERTEX_PSURF_BUG = False
For each of these parameters, there is another parameter (such as BULKMIXEDLAYER or TIDES) whose value determines whether they might be used in a particular case.  To determine whether or why answers for a particular configuration might change with this PR, compare the MOM_parameter_doc.all files from equivalent runs …

*Change defaults for KV_ML_INVZ2 and 3 bug flags

---

src/core/MOM_barotropic.F90

The first commit fixes a couple of typos in BT solver.
The second commit moves the `log_param` calls of the wide halo size parameters after the `clone_MOM_domain` call, where these parameters may be modified. Otherwise, the entries in `MOM_parameter_doc.layout` record only the use specified values or the default, which is usually zero. As a result, this commit may change `MOM_parameter_doc.layout` from the old runs.
The third commit addresses a potential problem with the timestamps of the BT step diagnostic outputs. Previously, the (hifreq) output between BT steps has a time interval = `dtbt`. While this is technically the right choice, it ignores the filter steps. As a result, the time interval at each baroclinic time step is not enough for all output from nstep+nfilter BT step. The …

Fix BT solver wide halo log_param and hifreq diagnostics timestamps

---

.testing/Makefile
config_src/infra/FMS2/MOM_io_infra.F90

This patch re-implements the FMS2 implementations of `open_ASCII_file` and `open_namelist_file` to remove their dependency on FMS1 functions which have been staged for deletion.
Note that if a file is opened with `mpp_open` but closed with `close_file_unit`, then it will raise an error in `fms_io_exit`. This will no longer be an issue after all references to `mpp_open` have been removed.  But in the meantime, we will need to ensure that all unit-based `close_file` calls were not opened with `mpp_open`.
There is also a minor patch to `.testing/Makefile` which selects the framework ("infra") source dependency, rather than hard-set to FMS1.

FMS2: open_ASCII_file and open_namelist_file

---

src/core/MOM_dynamics_split_RK2.F90
src/framework/MOM_restart.F90

This PR adds the option to store Coriolis and momentum self-advection
accelerations for use in the next predictor step in the restart file with the
split RK2 time stepping scheme, rather than storing the horizontal volume
transports and time-averaged thicknesses.  This option is controlled by the new
runtime parameter STORE_CORIOLIS_ACCEL, with the default being to use the new
restart file contents.  In order to maintain identical diagnostics, separate
arrays are used for the predictor and corrector versions of the Coriolis
accelerations.
The PR also includes the addition of a new capability (based on one that has
long been in use in SIS2) to read extra variables from restart files.  This new
capability allows for the contents in restart files to be modified, and the PR
includes code to …

+Store next predictor step Coriolis accelerations in restarts

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/core/MOM.F90
src/initialization/MOM_state_initialization.F90
src/tracer/MOM_offline_main.F90

This PR includes a series of commits that refactor the capabilities that had
been wrapped up in ALE_main, giving greater flexibility in the determination of
the variables that are remapped, and allowing for a reduction in the number of
different routines within MOM_ALE.F90.  This PR takes essential preliminary
steps toward addressing https://github.com/NOAA-GFDL/MOM6/issues/203. The specific changes include:
- Split remap_all_state_vars into ALE_remap_tracers and ALE_remap_velocities
- Created the new public subroutine pre_ALE_diagnostics, and call it from step_MOM
- Eliminated the unused argument conv_adjust to regridding_main
- Eliminated check_grid, and moved these tests into regridding_main
- Eliminated check_remapping_grid, and replaced it with calls directly to
check_grid_column …

+Refactored and replaced ALE_main

---

src/core/MOM_CoriolisAdv.F90
src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_barotropic.F90
src/core/MOM_continuity.F90
src/core/MOM_continuity_PPM.F90

Revised or extended comments to correct or more clearly document the units of
49 internal variables in modules in the core directory.  All answers are bitwise identical.

Document variable units in core modules

---

src/core/MOM_barotropic.F90
src/core/MOM_grid.F90
src/core/MOM_open_boundary.F90
src/core/MOM_transcribe_grid.F90
src/framework/MOM_dyn_horgrid.F90
src/initialization/MOM_grid_initialize.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_interface_filter.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90

This PR includes a series of commits that correct the fact that the model was
not reproducing across restarts with OBLIQUE open boundary conditions, as is
discussed extensively at github.com/NOAA-GFDL/MOM6/issues/208.  Unfortunately,
MOM6 is not yet reproducing answers when the OBLIQUE_TAN OBCs.  The primary
changes are:
- Replaced certain OBC-related variables in the restart files to avoid
reusing the same variables for fields that are not co-located
- Project the some values of gtot_[NSEW] outward at OBC points in btstep
- Added two (OBCmaskCu and OBCmaskCv) to the ocean_grid_type and
dyn_horgrid_type to mask out values over land or at OBC points
- Simplify the some sections code applying OBCs by using these new masks
- Apply OBC-related masks in several places to avoid using …

*+Correct oblique OBC restarts

---

config_src/infra/FMS2/MOM_io_infra.F90

Closes #220 
- The subroutine categorize_axes cannot find the axes in ice restart files and gives warnings
WARNING from PE     0: categorize_axes: Failed to identify x- and y- axes in the axis list (xaxis_1, yaxis_1, Time) of a variable being read fr
om I
NPUT/ice_model.res.nc
- This leads to an incorrect initializations and a subsequent sat.vap.press.overflow crash when using
infra/FMS2
- Same experiment runs fine with infra/FMS1
- After the fix the infra/FMS1 and infra/FMS2 answers are bitwise
identical
- Thanks @uramirez8707 for suggesting this fix.

Bug fix for categorize_axes causing crash

---

.github/actions/macos-setup/action.yml
.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml
ac/configure.ac
ac/m4/ax_fc_check_c_lib.m4

This patch introduces a new autoconf macro, `AX_FC_CHECK_C_LIB`, which confirms if the Fortran compiler can be linked to the netCDF C library. As with other netCDF tests, the `nc-config` tool is used if necessary (and available).
This resolves some recent issues on platforms where netCDF and netCDF-Fortran are installed in separate locations, with different library directories (`-L`).
It also resolves some false assumptions in configure.ac which presumed equivalent access by the configured C and Fortran compilers. Previously, we would test if the C compiler could be linked to netCDF, and then assume that the Fortran compiler shared the same relationship. We now use the Fortran compiler for both C and Fortran tests.
This patch fixes many issues observed on MacOS systems, including some …

Autoconf: Fortran-netCDF C compatibility test

---

ac/configure.ac
ac/m4/ax_fc_check_bind_c.m4
ac/m4/ax_fc_check_c_lib.m4

This patch fixes some issues with testing of C bindings in Fortran. Specifically, some tests are using a C compiler which may be unconfigured, causing unexpected errors.
The autoconf script now uses the Fortran compiler to test these bindings, rather than using the C compiler to test for their existence. A new macro (AX_FC_CHECK_BIND_C) was added to run these tests.
This achieves the actual goal (test of Fortran binding) on top of the original goal (availability of C function), while ensuring that the actual compiler of interest (FC) is used in the test.
Two C-based tests are still present in the script for testing the size of jmp_buf and sigjmp_buf.  The C compiler is now configured with the AX_MPI macro, and is only used to determine the size of these structs.

Autoconf: Fortran testing of C bindings

---

src/core/MOM_dynamics_split_RK2.F90

Merge of main branch to dev/gfdl (#1586).  Includes the spherical harmonic allocation bugfix.

Update from main

---

src/ice_shelf/MOM_ice_shelf.F90
src/initialization/MOM_coord_initialization.F90
src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

Added calls to get_param to set 12 input variable names in files via runtime parameters, including TIDEAMP_VARNAME, TEMP_COORD_VAR, SALT_COORD_VAR, THICKNESS_IC_VAR, INTERFACE_IC_RESCALE, TEMP_IC_VAR, SALT_IC_VAR, BASIN_VAR, TIDAL_DISSIPATION_VAR, ROUGHNESS_VARNAME, TIDEAMP_VARNAME and KH_BG_2D_VARNAME. Also added two new runtime parameters, THICKNESS_IC_RESCALE and INTERFACE_IC_RESCALE, to allow input thickness and interface height fields to be rescaled.  A number of spelling errors in comments or output messages in the files that were being modified as a part of this commit, including changes in the documentation that appears in MOM_parameter_doc files.
A second commit added calls to get_param to set 4 more input variable names in files via runtime parameters, including U_IC_VAR, …

+Set input file variable names via runtime params

---

src/parameterizations/vertical/MOM_tidal_mixing.F90

Corrected a bug in converting depths read from an input file from units of cm to m when the ER03 version of tidal mixing is used.  This commit will change answers when INT_TIDE_DISSIPATION = True, USE_CVMix_TIDAL = True, and TIDAL_ENERGY_TYPE = "ER03".  There are no such configurations in the MOM6-examples pipeline tests, and it is not clear whether or where such a configuration has ever been used.
This bug was introduced into dev/gfdl on Nov. 19, 2018 as a part of PR #883 in
commit https://github.com/NOAA-GFDL/MOM6/commit/967e470, which was supposed to be a refactoring of this portion of the code without changing answers, but introduced this bug.  This commit should restore solutions with impacted configurations to what they would have been before that earlier commit.

*Fix bug with TIDAL_ENERGY_TYPE = "ER03"

---

.gitlab-ci.yml

GitLab CI includes the internal testing suite (.testing) and included an explicit setup of the Python environment (`make work/local-env`).  The rule has since been removed, and the command now fails.
This patch removes those steps, since we no longer use Python in the tests.
It also slightly reworks the reporting of test output.  Instead of re-running `make test`, it uses the `make test.summary` rule to report the final result.

Remove Python venv setup from GitLab-CI rules

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_remapping.F90
src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_open_boundary.F90
src/framework/MOM_diag_remap.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

This PR consists of a series of commits that add the capability, selected at
runtime via the new parameter REMAP_AUXILIARY_VARS, to remap all of the 3-d
variables that are registered for restarts but were not previously remapped.
This PR addresses the issue at github.com/NOAA-GFDL/MOM6/issues/203 in cases
using ALE remapping, but it may also be worthwhile to examine this issue in
non-ALE cases as well.  There are several new interfaces and a new runtime
parameter, so the contents of the MOM_parameter_doc files change, but by
default all answers are bitwise identical.
- NOAA-GFDL/MOM6@987a0ef3e +Add REMAP_AUXILIARY_VARS to remap accelerations
- NOAA-GFDL/MOM6@ba145bff7 +Add ALE_remap_interface_vals and ALE_remap_vertex_vals
- NOAA-GFDL/MOM6@949392b2d +Add …

+Add remapping of auxiliary variables in restarts

---

src/core/MOM_CoriolisAdv.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90
src/initialization/MOM_fixed_initialization.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/boundary_impulse_tracer.F90

Corrected the units written to the output files for 4 diagnostics (CAu_Stokes, CAv_Stokes, area_shelf_h and sfc_mass_flux) and added missing units arguments to the get_param calls for some (mostly unlogged) parameters.  The logged calls where units are added include those for EKE_MAX, NDIFF_DRHO_TOL, NDIFF_X_TOL, and IMPULSE_SOURCE_TIME, while some unnecessary carriage returns were removed in the descriptions of some of these and closely related parameters.  Also added units to the comment describing the AGlen argument to initialize_ice_AGlen.  All answers are bitwise identical, but there can be minor changes in the metadata of some files, and some MOM_parameter_doc and available_diags files might exhibit minor changes.

+Correct reported units for 4 diagnostics

---

src/user/dense_water_initialization.F90

Added a missing scale factor in the DENSE_WATER_EAST_SPONGE_SALT get_param call in dense_water_initialize_sponges, and added comments describing the local variables (and their units) throughout the dense_water_initialization module. Comments were added noting that the variable set by DENSE_WATER_SILL_HEIGHT is unused, and that perhaps this should have been DENSE_WATER_SILL_DEPTH.  Units arguments were also added to two of the unlogged get_param calls in this module.  Without this change, this test case would not reproduce with dimensional rescaling due to a scale factor that was omitted when salinity was being rescaled on May 3, 2022, which became a part of PR #122 to dev/gfdl, but answers should not change when dimensional rescaling of salinities is not used. All answers and output in …

(*)Rescale DENSE_WATER_EAST_SPONGE_SALT

---

.testing/Makefile
.testing/tc4/Makefile.in

This patch fixes two issues in the preprocessing of tc4.
* ocean_hgrid.nc is marked as a dependency of gen_data
* Multiple ouputs are handled more safely in the Makefile
Expanding on the second point: We were directing one rule to produce two output files, which resulted in the rule being run twice when invoked in parallel (make -j).
This has been replaced with the recommended solution for handling concurrent outputs: use one to generate both, and connect the second to the first with a separate rule.
I have also generalized the `make` command in the .testing Makefile.
This should address (and hopefully fix) some intermittent errors in the .testing build on Gaea.

.testing: Fix concurrency errors in tc4 rules

---

.gitlab/pipeline-ci-tool.sh

The Gaea GitLab test configuration includes two no-library compilation tests for ocean-only and ice-ocean configurations.  They are currently configured to run in the same directory.
Recently, several unusual I/O errors suggest problems due to concurrent testing of the builds.  In order to rule out this possibility, this patch moves the ice-ocean test to a separate directory.

GitLab: Fix nolib build directories

---

src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_regularize_layers.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

Documented numerous internal variables and their units in 9 vertical parameterization modules (MOM_bkgnd_mixing, MOM_bulk_mixed_layer, MOM_diabatic_aux, MOM_diabatic_driver, MOM_entrain_diffusive, MOM_kappa_shear, MOM_regularize_layers, MOM_set_diffusivity and MOM_set_viscosity). This commit includes the addition of units arguments in 9 unlogged get_param calls.  A number of spelling errors were also corrected in comments.  All answers and output are bitwise identical.

Document units in 9 vertical param modules

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

If the forcing ustar is exactly zero, the denominator of the momentum mixing rate term reduces to just the Coriolis parameter. With a grid construction that is symmetric about the equator, this term is also exactly zero, leading to a division by zero.
To avoid this, a very small minimum ustar value is introduced, using the Earth's rotation as a velocity timescale, in the same manner as in some of the vertical parameterisations. This should prevent the denominator of the momentum mixing rate from going to zero. My only question here is whether this is the right velocity scale to be using (and indeed if this is the right approach)?

Use small minimum ustar in mixed layer restratification

---

ac/makedep

Applying makedep to a single shot build of FMS+MOM6 (i.e. skipping the libFMS.a) I found the list of objects was incomplete because the C files were not covered by the module dependencies. makedep figures out the Fortran module dependencies and then has a list of "externals" to cover all the files that don't provide modules. "externals" are always compiled, in lieu of flinting the source code. The main commit simply adds all the C object files to the list of externals. When building via a library, the module dependencies are ignored and everything gets built, which is why this gap was not seen before.
Two other commits refactor the script to follow PEP8 (the first from @marshallward).

Patch makedep to include C in "externals"

---

src/core/MOM_barotropic.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_write_cputime.F90
src/framework/testing/MOM_file_parser_tests.F90
src/parameterizations/lateral/MOM_MEKE_types.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/tracer/MOM_tracer_flow_control.F90

Documented numerous internal variables and their units in 3 lateral parameterization modules (MOM_hor_visc, MOM_lateral_mixing_coeffs, MOM_MEKE_types) and the write_cputime module.  In addition, the units of a number of internal variables in the MOM_sum_output module and arguments to call_tracer_stocks were added to their descriptions in comments.  This commit includes the addition of units or scale=1.0 arguments in 9 unlogged get_param calls.  A number of spelling errors were also corrected in comments.  All answers and output are bitwise identical.

Document units in 8 lat_param or diag modules

---

config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
src/ALE/MOM_hybgen_regrid.F90
src/core/MOM_grid.F90
src/framework/MOM_diag_mediator.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ocean_data_assim/MOM_oda_driver.F90

Add units arguments to 11 get_param calls in 8 files, and added scale=1.0 arguments to 3 get_param calls in solo_driver/MOM_driver.F90, along with comments explaining why these time variables are not being rescaled.  Also changed comments describing the various units that might be used for geoLat or geoLon variables in the ocean_grid_type to use standard syntax.  The added units arguments lead to some minor differences in MOM_parameter_doc files, but all answers are bitwise identical.

+Add 11 units arguments to get_param calls

---

src/core/MOM_grid.F90
src/core/MOM_transcribe_grid.F90
src/framework/MOM_dyn_horgrid.F90
src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
src/initialization/MOM_grid_initialize.F90
src/user/baroclinic_zone_initialization.F90
src/user/circle_obcs_initialization.F90

Added the new elements x_ax_unit_short and y_ax_unit_short to the ocean_grid_type and the dyn_horgrid_type to facilitate the documentation of the units of variables when they depend on the units of the axes.  This includes modifying some units that were being reported as the meaningless "[k]" into the meaningful "[km]", and some units that were being reported as just "[degrees]" are now being reported with the more specific "[degrees_E]" or "[degrees_N]". These new elements are also being used in the baroclinic_zone_initialization and circle_OBCs modules, and comments describing the units of a number of the internal variables in the former module were added or modified.  The description of the AXIS_UNITS parameter was expanded to provide some of the other working options.  All answers are …

+Add x_ax_unit_short to ocean_grid_type

---

src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_barotropic.F90
src/core/MOM_verticalGrid.F90
src/framework/testing/MOM_file_parser_tests.F90
src/tracer/oil_tracer.F90

Add appropriate units arguments to 11 log_param calls that were missing them.
All answers are bitwise identical, but the logged output can change in some cases.

+Add units to 11 log_param calls

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/FMS_cap/ocean_model_MOM.F90
config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
config_src/drivers/mct_cap/mom_ocean_model_mct.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/drivers/solo_driver/MOM_driver.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_marine_ice.F90
src/tracer/MOM_offline_main.F90

This pull request applies dimensional rescaling to units of [T ~> s] for a
number of timestep variables in all of the driver codes and for some of the
arguments to step_MOM and 6 other routines.  With this change, the rescaling
increasingly takes place at the driver level, especially on lines converting
time_types to real variables.  All answers and output are bitwise identical, but
the scaling for several arguments in publicly visible interfaces have changed.
- NOAA-GFDL/MOM6@604cd0a33 +Rescaled real time arguments to step_MOM
- NOAA-GFDL/MOM6@81284483f +Rescaled time variables in all MOM6 drivers

+Rescale driver timestep variables and step_MOM args

---

config_src/external/GFDL_ocean_BGC/generic_tracer_utils.F90
src/tracer/MOM_generic_tracer.F90

This PR is my attempt to fix the issue #217, which affected generic tracers that had fluxes into the ocean from runoff. During a thermodynamics time step, MOM6 adds the river tracer flux to the surface tracer flux `stf`. If more than one thermodynamics time step is done per coupler time step, the river input gets added to `stf` multiple times. This PR fixes this bug by checking each tracer for a new logical flag `runoff_added_to_stf`. If this flag is false, the runoff is added to `stf` and then the flag is set to true. 
For this PR to work in configurations using generic tracers, it will need to be paired with a PR I have to ocean_BGC (https://github.com/NOAA-GFDL/ocean_BGC/pull/20) that adds `runoff_added_to_stf` to `g_tracer_type` and resets the flag to false after updates to `stf` …

Keep track of whether runoff has been added to stf

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

There are extra US%T_to_s scaling factors in the expressions for ustar_min that were recently introduced with dev/gfdl PR #251; these are duplicative of the scaling factor that is already being applied when the parameter OMEGA is read in.  The resulting expressions for ustar_min therefore effectively have units of [Z s T-2 ~> m s-1] when they should have units of [Z T-1 ~> m s-1]. Because ustar_min is a tiny floor on the magnitude of ustar, there is a range of values of T_RESCALE_POWER that will give the same answers as when it is 0, but for large enough values the answers will change, perhaps dramatically.  This small commit removes these extra factors.  Answers will change for some large values of T_RESCALE_POWER, but they are bitwise identical in the TC testing and in MOM6-examples …

*Fix new scaling bug in ML restrat minimum ustar

---

src/core/MOM.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

Added the runtime parameters KV_RESTRAT and RESTRAT_USTAR_MIN, to build on the improvements in github.com/NOAA-GFDL/MOM6/pull/251, and to provide run-time physical parameters to avoid the potential division by zero in the mixed_layer_restrat code noted at github.com/mom-ocean/MOM6/issues/1168. Once this PR is merged onto the main branch of MOM6, that issue can be closed.  By default, these do not change answers in the MOM6-examples test suite, but the default value for RESTRAT_USTAR_MIN was taken from the hard-coded value in PR that PR.  The six copies of the eddy growth rate timescale calculations were consolidated into a new internal function, growth_time, with some other related minor refactoring of the code.  Also, mixedlayer_restrat_register_restarts now takes a unit_scale_type …

+Add runtime params KV_RESTRAT & RESTRAT_USTAR_MIN

---

src/core/MOM_checksum_packages.F90
src/equation_of_state/MOM_EOS.F90

Corrected the pressure rescaling in calculate_density_second_derivs_scalar()that had been using an uninitialized variable.  Also corrected the dimensional rescaling of dSVdT and dSVdS in calc_spec_vol_derivs_1d when temperature and salinity are being rescaled but density is not.  Fortunately these do not seem to impact solutions in any production runs, and there do not appear to be any calls to calculate_density_second_derivs_scalar().  Comments were also added describing the units of a number of internal variables or conversion factor in the MOM_EOS module.  All answers in the MOM6-examples test suite are bitwise identical.
Also added checksum calls for tv%varT, tv%varS and tv%covarTS to MOM_thermo_chksum when these elements of the thermovar type are associated.

(*)Correct two rescaling bugs in MOM_EOS

---

src/core/MOM.F90
src/core/MOM_PressureForce_FV.F90
src/core/MOM_isopycnal_slopes.F90
src/core/MOM_stoch_eos.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90

This PR corrects several bugs that would prevent cases with STOCH_EOS = True or that set a non-negative value of STANLEY_COEF from running at all, and then when it runs it corrects other bugs that cause it to give incorrect answers, as evident in its inability to reproduce across processors, and to fail to pass dimensional consistency testing.  There was also extensive refactoring of the MOM_stoch_eos.F90 code.  Specifically this PR makes the following changes:
- The new routine stoch_eos_register_restarts was added to register the restart
field associated with the MOM_stoch_EOS module before the restarts are read
and before restart_registry_lock is called, which was causing any test case
with STOCH_EOS=True or a positive value of STANLEY_COEF to have a fatal error.
- Added a missing …

+(*)Fix numerous issues with MOM_stoch_eos and Stanley parameterizations

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/parameterizations/lateral/MOM_spherical_harmonics.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/user/MOM_wave_interface.F90
src/user/Rossby_front_2d_initialization.F90
src/user/user_change_diffusivity.F90

This PR includes a series of commits to correct the documentation of variable units, especially in the MOM_spherical_harmonics and MOM_wave_interface modules. It also includes the addition of conversion factors to the register_diag_field calls for the two "developmental" diagnostics dudt_Stokes and dvdt_Stokes whose documented units were corrected, and to the register_restart calls for Us_x_prev and Us_y_prev.  This also required the addition of a unit_scale_type argument to waves_register_restarts.  All answers are bitwise identical.
- NOAA-GFDL/MOM6@b819d9778 +Correct MOM_wave_interface unit descriptions
- NOAA-GFDL/MOM6@ea699efb0 Correct scattered unit description syntax
- NOAA-GFDL/MOM6@2ca2d19f9 Unit descriptions in MOM_spherical_harmonics

Correct wave and spherical harmonics unit descriptions

---

src/diagnostics/MOM_wave_structure.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/tracer/RGC_tracer.F90
src/tracer/dye_example.F90
src/tracer/oil_tracer.F90
src/user/BFB_surface_forcing.F90
src/user/ISOMIP_initialization.F90
src/user/Neverworld_initialization.F90
src/user/RGC_initialization.F90
src/user/adjustment_initialization.F90
src/user/basin_builder.F90
src/user/dumbbell_initialization.F90
src/user/external_gwave_initialization.F90
src/user/seamount_initialization.F90
src/user/shelfwave_initialization.F90
src/user/user_change_diffusivity.F90

The series of commits in this PR adds or modify units arguments to 22 get_param calls in 14 user or tracer modules, and it uses elements of the ocean_grid_type to specify the units of some horizontal position related variables or to determine the domain size.  It also includes a commit that cleans up the internal tide debugging source locations and another that adds 6 new runtime parameters to replace hard-coded values in the ISOMIP configuration. These commits also add comments describing many internal real variables and their units in these same files.  All answers and output are bitwise identical, but there are changes in some of the MOM_parameter_doc files.
This series of commits includes many of the changes that are required to make the units argument mandatory for calls to …

+Document axis and other units in user modules

---

src/diagnostics/MOM_spatial_means.F90
src/initialization/MOM_shared_initialization.F90
src/tracer/MOM_tracer_advect.F90
src/user/Phillips_initialization.F90
src/user/RGC_initialization.F90
src/user/benchmark_initialization.F90

Swapped the order of the i- and j- loops in 13 places in 6 files so that they will be stride-1 in memory for efficiency, and to follow the established patterns elsewhere in the MOM6 code.  All answers are bitwise identical.

Reorder i- and j-loops to be stride-1 in memory

---

src/core/MOM_PressureForce_FV.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90

We were issuing a WARNING when the user indicates to use the STANLEY contribution to density with a logical flag but if the coefficient is negative we were toggling the logical flag with logging and only issuing a warning. This would lead to users getting a result they were not expecting, regardless of whether they were informed. Better for the run to fail so they can set the coefficient to non-negative.

Made STANLEY_COEFF<0 warnings be fatal

---

src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/vertical/MOM_vert_friction.F90

This adds a new vertical viscosity parameterization as in Greatbatch and Lamb (1990), Ferreira & Marshall (2006) and Zhao & Vallis (2008), hereafter referred to as the GL90 vertical viscosity parameterization. This vertical viscosity scheme redistributes momentum in the vertical, and is the equivalent of the Gent & McWilliams (1990) parameterization, but in a TWA (thickness-weighted averaged) set of equations. The vertical viscosity coefficient `nu` is computed from `KD_GL90` (corresponding to `kappa_GM`) via thermal wind balance, and the following relation:
```
nu = KD_GL90 * f^2 / N^2.
```
Currently, the GL90 parameterization is only implemented in stacked shallow water (SSW) mode, in which case we have `1/N^2 = h/g'`.
The vertical viscosity `del_z ( nu del_z u)` is applied to the …

Add GL90 parameterization for stacked shallow water

---

src/core/MOM_porous_barriers.F90
src/initialization/MOM_shared_initialization.F90

Apply dimensional rescaling immediately after reading the open face width and porous barrier depth variables in reset_face_lengths_list() to facilitate the detection of improperly scaled variables or incorrect unit declarations throughout the code.  Also eliminated unnecessary local copies of rescaling factors in the MOM_porous_barriers module.  All answers are bitwise identical.

Rescale internal variables in reset_face_lengths_list

---

src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_geothermal.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/tracer/MOM_tracer_hor_diff.F90

This commit includes minor cleanup of the units documentation in several of the process parameterization routines.  These changes include:
- Change the units of the (apparently unused) optional read_khdt_[xy] arguments to tracer_hordiff from [m2] to [L2 ~> m2]
- Correct a tiny number used for safety in the denominator of a normalization factor based on the (nondimensional) masks from H_subroundoff to a tiny nondimensional number, giving an expression that is dimensionally consistent. Without this change, the diagnostic "KHTR_h" will vary with large enough negative values of H_RESCALE_POWER.
- Replace a local variable in  bulkmixedlayer_init with units of time with distinct get_param calls setting the default for BUFFER_LAY_DETRAIN_TIME depending on which buffer layer detrainment scheme is …

(+)Better units documentation in MOM_tracer_hor_diff and 4 other modules

---

src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

The commits in this PR apply dimensional rescaling to the diagnostics that are written by the MOM_tidal_mixing and MOM_CVMix_KPP modules, and then add the corresponding conversion factors for the register_diag_field calls for these
diagnostics.  In addition, the input forcing fields for the MOM_tidal_mixing module and some of the preliminary calculations before the calls to the CVMix routines are also in rescaled units.  All answers and output are bitwise identical.
- NOAA-GFDL/MOM6@8b2e5401c Rescale diagnostics from MOM_CVMix_KPP
- NOAA-GFDL/MOM6@5dd95c5d0 Rescale input fields in MOM_tidal_mixing

Rescale CVMix_KPP and MOM_tidal_mixing diagnostics

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Avoid using the unscaled argument to MOM_get_param in 5 places in 4 files, and
made related changes to avoid using some unscaled variables:
- Replace Hmix_min_m (in [m]) with Hmix_min_z (in [Z ~> m]) in bulkmixedlayer_init and then set CS%Hmix_min by rescaling Hmix_min_z to [H ~> m or kg m-2].
- Replace Hmix_m (in [m]) with Hmix_z (in [Z ~> m]) in vertvisc_init, and then set CS%Hmix by rescaling Hmix_z to [H ~> m or kg m-2].
- Add a separate unlogged and unscaled get_param call for FLUXCONST for flux_const_default in the solo_driver surface_forcing_init
- Do not rescale FLUXCONST when it is read in the FMS_cap surface_forcing_init.
- The Flux_const element of the FMS_cap surface_forcing_CS was not actually being used apart from setting a default for Flux_const_temp and Flux_const_salt, so …

Avoid using the unscaled argument to MOM_get_param

---

src/user/MOM_wave_interface.F90

Added 7 new runtime parameters (LA_DEPTH_MIN, DHH85_MIN_WAVE_FREQ, DHH85_MAX_WAVE_FREQ, RHO_AIR, VISCOSITY_AIR, WAVE_HEIGHT_SCALE_FACTOR and VON_KARMAN_WAVES) to specify the previously hard-coded dimensional parameters in the MOM_wave_interface module.  Because there are several different ways to set the parameters related to the Langmuir number calculation, several of these parameters are set in the new private subroutine set_LF17_wave_params, which in turn is called in two different places.  Some comments were also added to annotate the units of some of the variables in this module.  By default all answers are bitwise identical, but there are new entries in the MOM_parameter_doc.all files for some configurations that use the MOM6 surface wave module.

+Add runtime parameters for MOM_wave_interface

---

src/user/Kelvin_initialization.F90
src/user/dumbbell_initialization.F90
src/user/tidal_bay_initialization.F90

This PR adds 6 new runtime parameters to replace hard-coded dimensional
parameters in 3 user modules (dumbbell_initialization, Kelvin_initialization and
tidal_bay_initialization) that were added to provide tests of the OBC code. The
new runtime parameters that were added are DUMBBELL_T_LIGHT, KELVIN_WAVE_PERIOD,
KELVIN_WAVE_SSH_AMP, KELVIN_WAVE_INFLOW_AMP, TIDAL_BAY_PERIOD and
TIDAL_BAY_SSH_ANOM.  By default all answers are bitwise identical, but there are
new entries in the MOM_parameter_doc.all files for configurations using the
three impacted modules.
- NOAA-GFDL/MOM6@7c12ead59 +Add runtime parameters for tidal_bay_initialization
- NOAA-GFDL/MOM6@780ff973e +Add runtime parameters for Kelvin_initialization
- NOAA-GFDL/MOM6@9b3f1ba2f +Add runtime parameter …

+Add 6 runtime parameters for OBC testcase initialization modules

---

ac/makedep

The current implementation of makedep contains something like a race condition, where the creation of the .mod and .o files may be in an order which breaks the current dependency tree.  Currently, .mod depends on .o, and changes to a module do not trigger rebuilds of dependent source.
Rather than try to sort out the rule order, which could even depend on compiler internals, this patch just adds both object and module output files as dependencies, and rebuilds if either changes.
We might want to come back to this someday and understand the actual order of rule execution.
Thanks to Alistair Adcroft (@adcroft) for proposing this solution.

makedep: Include object file dependencies

---

src/framework/MOM_horizontal_regridding.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/tracer/MOM_tracer_Z_init.F90

This series of commits revises the interfaces to horiz_interp_and_extrap to eliminate two unused arguments and rename a third from conversion to scale for consistency with other MOM6 interfaces.  It also adds a set of 20 runtime parameters to replace hard coded dimensional variables, including tolerances for use with horiz_interp_and_extrap, tolerances and bounds in determine_temperature and default dynamic ice shelf temperatures.  It also adds comments documenting the units of a number of internal variables in MOM_ALE_sponge.  By default all answers are bitwise identical, but there are new parameters in several MOM_parameter_doc files.
- NOAA-GFDL/MOM6@9ffa1bbc8 +Add 2 runtime params for ice shelf temperatures
- NOAA-GFDL/MOM6@dda6d4535 +Add 11 runtime …

+Revise horiz_interp_and_extrap and set related params

---

src/core/MOM.F90
src/core/MOM_boundary_update.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/RGC_tracer.F90
src/tracer/advection_test_tracer.F90
src/user/shelfwave_initialization.F90

Pass ocean_grid_type arguments to call_tracer_register and call_OBC_register in place of the hor_index_type arguments that had been used previously.  Also use these ocean_grid_type arguments in calls to register_shelfwave_OBC, register_RGC_tracer and register_advection_test_tracer.  Within these three routines, the contents of the ocean_grid_type are now used to specify axis units. The new runtime parameter SHELFWAVE_AMPLITUDE was added to allow for run-time control of the amplitude of the shelfwave test case.  By default all answers are bitwise identical, but there are some changes in the units of parameters as documented in the MOM_parameter_doc files and a new entry in these files for the shelfwave test case.

+Pass ocean_grid_type to call_tracer_register

---

src/user/DOME2d_initialization.F90
src/user/DOME_initialization.F90
src/user/benchmark_initialization.F90
src/user/sloshing_initialization.F90

This PR adds 7 new runtime parameters to replace hard-coded dimensional parameters in 4 user initialization modules (benchmark_initialization, DOME2d_initialization, sloshing_initialization and DOME_initialization).  The new runtime parameters that were added are BENCHMARK_T_LIGHT, INITIAL_SSS, DOME2D_T_BAY, DOME2D_EAST_SPONGE_S_RANGE, INITIAL_SSS, SLOSHING_T_PERT and DOME_T_LIGHT.  By default all answers are bitwise identical, but there are new entries in the MOM_parameter_doc.all files for configurations using the four impacted modules.
- NOAA-GFDL/MOM6@157b8068e +Add runtime parameters for DOME_initialization
- NOAA-GFDL/MOM6@5831dc6f1 +Add runtime parameters for sloshing_initialization
- NOAA-GFDL/MOM6@dd7c787a1 +Add runtime parameters for …

+Add 7 runtime parameters for user init modules

---

src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_regularize_layers.F90

This PR adds 12 new runtime parameters to replace hard-coded dimensional parameters in 11 parameterization modules (MOM_lateral_mixing_coeffs.F90, MOM_internal_tides.F90, MOM_CVMix_KPP.F90, MOM_kappa_shear.F90, MOM_MEKE.F90, MOM_thickness_diffuse.F90, MOM_entrain_diffusive.F90, MOM_diabatic_aux.F90, MOM_bulk_mixed_layer.F90, MOM_ALE_sponge.F90 and MOM_regularize_layers.F90).  The new runtime parameters that were added are MEKE_MIN_DEPTH_TOT, MEKE_LSCALE_MAX_VAL, EN_CHECK_TOLERANCE, MIN_DZ_FOR_SLOPE_N2, MEKE_MIN_DEPTH_DIFF, ENTRAIN_DIFFUSIVE_MAX_ENT, KD_SEED_KAPPA_SHEAR, KPP_LT_MLD_GUESS_MIN,  REG_SFC_SUFFICIENT_ADJ, SALT_EXTRACTION_LIMIT, MECH_TKE_FLOOR and VARYING_SPONGE_MASK_THICKNESS).
This PR also includes a commit that makes the optional argument dz_subML to …

+Add 12 runtime parameters for parameterization modules

---

src/framework/MOM_document.F90

Added code to harmonize differences in how different compilers format the output of tiny (< 1e-99) or huge (>= 1e100) real values.  All answers are bitwise identical, but output could change with the PGI compiler for any cases that are writing out such extreme values.

Standardize the output of tiny real values

---

src/user/adjustment_initialization.F90

This commit replaces previously hard-coded values for dRho_dS and the temperature range for the sloshing test case with values read in from the existing runtime parameters DRHO_DS and the previously unused parameter T_RANGE that was already being read in for this configuration.  The default value for dRho_dS from the EOS code (0.8 kg m-3 ppt-1) does not match hard coded value here (1 kg m-3 ppt-1), but in the existing tests using adjustment_initialization DRHO_DS was being explicitly set to the hard-coded value here, so I have chosen to reuse the same parameter with the same default value as is used elsewhere even though it could change answers in cases that do not set DRHO_DS consistently with the previous hard coded parameter.  In addition, the previous default value for T_RANGE read …

*+Use runtime params in adjustment_initialization

---

src/user/MOM_wave_interface.F90

This PR is a series of commits to enable the use of more robust code in the the MOM_wave_interface module, and to specify runtime parameters for this code.  The changes in this PR include:
- Add the runtime parameter WAVE_INTERFACE_ANSWER_DATE.  For now the default (20221231) is to recover the previous settings, but after coordination with the MOM6 community, the default should change to reflect the global DEFAULT_ANSWER_DATE used elsewhere in MOM6.
- Removed the unused element La_SL from the wave_parameters_CS
- Add the 3 runtime parameters CHARNOCK_MIN, CHARNOCK_SLOPE_U10 and  CHARNOCK_0_WIND_INTERCEPT to specify the curve fit in the Charnock coefficient calculation.
- Add three new runtime parameters (LANGMUIR_STOKES_BACKGROUND, SURFBAND_MIN_THICK_AVG and SURFBAND_OVERRIDE_LAND_SPEED) …

+Add and use WAVE_INTERFACE_ANSWER_DATE

---

src/core/MOM.F90
src/ocean_data_assim/MOM_oda_driver.F90

These changes follow suggestions from @Hallberg-NOAA for clarity in documentation and code readability.  These modifications should not impact existing applications (e.g. SPEAR) which are reliant on this code.

Updates to ODA driver suggested by @Hallberg-NOAA Issue#277

---

src/tracer/DOME_tracer.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/tracer_example.F90

Added the new runtime parameters DOME_TRACER_STRIPE_WIDTH, DOME_TRACER_STRIPE_LAT and DOME_TRACER_SHEET_SPACING to specify the previously hard-coded dimensional parameters in the DOME_tracer module, and added the runtime parameters TRACER_EXAMPLE_STRIPE_WIDTH and TRACER_EXAMPLE_STRIPE_LAT to specify parameters used by tracer_example.  This change requires that an ocean grid type be passed to register_DOME_tracer and USER_register_tracer_example instead of a hor_index type.
Descriptions of the units of a number of internal variables were added to both modules.  In addition, the confusing (and dimensionally heterogeneous) trdc array in tracer_column_physics was replaced with 3 internal variables with more suggestive names.
By default all answers are bitwise identical, but there are new …

+Add DOME_tracer and tracer_example runtime params

---

src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_verticalGrid.F90
src/framework/MOM_domains.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90
src/parameterizations/vertical/MOM_CVMix_shear.F90
src/tracer/MOM_neutral_diffusion.F90
src/user/BFB_surface_forcing.F90
src/user/circle_obcs_initialization.F90
src/user/dumbbell_surface_forcing.F90

Removed extra white space around the named argument assignments for default, units or conversion arguments to align with the MOM6 style guide.  Only white space is modified, and all answers are bitwise identical.

Named argument assignment white-space clean-up

---

.testing/tc4/MOM_input
src/core/MOM_density_integrals.F90
src/diagnostics/MOM_obsolete_params.F90
src/initialization/MOM_fixed_initialization.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90

This PR includes a series of commits that cleans up minor issues with the code in the src/initialization directory.  It includes commits that make the formerly optional z_tol arguments to find_depth_of_pressure_in_cell() and cut_off_column_top() non-optional.  Two hard-coded but apparently unused fill values for temperature and salinity were replaced with standard fill values for land.  It also formally obsoletes the archaic runtime parameter NEW_SPONGES, which required that the MOM_input file for .testing/tc4 be updated to reflect more recent parameter names and defaults.  In addition, comments in several other modules were updated to reflect the units of a number of internal variables.  All answers are bitwise identical, but there are a few spelling error corrections in some of the …

+Minor code cleanup in initialization modules

---

src/diagnostics/MOM_wave_speed.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

This PR includes a pair of commits that expand the documentation of the internal variables and their units in the MOM_wave_speed module, and then adds a new runtime parameter, INTERNAL_WAVE_CG1_THRESH, to set a previously hard coded dimensional value for the threshold a first mode speed below which all higher mode speeds are simply given a speed of 0.  By default, all answers are bitwise identical, but there is a new entry in the MOM_parameter_doc files for some cases.
- NOAA-GFDL/MOM6@e469e984c +Add runtime parameter INTERNAL_WAVE_CG1_THRESH
- NOAA-GFDL/MOM6@cd7a47b6b Document units of variables in MOM_wave_speed

+MOM_wave_speed cleanup

---

src/diagnostics/MOM_diagnostics.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Follow-up from PR #293.
`KE_visc_gl90` is an alternative to the diagnostic `GLwork`. Both diagnostics describe the energetics of the GL90 parameterization, as part of the kinetic energy budget.
* `KE_visc_gl90` is consistent with `KE_visc`, and the remaining KE diagnostics. In particular, it is true that `KE_visc_gl90` is exactly contained in `KE_visc`, i.e., we have that `KE_visc` - `KE_visc_gl90` represents exactly the energetics of all viscosity contributions except the GL90 viscosity.
* GLwork is not directly compatible with `KE_visc`, but is guaranteed to be sign-definite if summed in the vertical.
The figures below show **snapshots** of the vertically summed diagnostics `KE_visc_gl90` and `GLwork`.

Add KE_visc_gl90 diagnostic

---

config_src/infra/FMS2/MOM_io_infra.F90
src/ALE/MOM_hybgen_regrid.F90
src/ALE/MOM_regridding.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_io.F90
src/framework/MOM_io_file.F90
src/framework/MOM_netcdf.F90
src/framework/MOM_restart.F90
src/ice_shelf/MOM_ice_shelf.F90
src/initialization/MOM_coord_initialization.F90
src/initialization/MOM_shared_initialization.F90

This patch introduces a generalized I/O interface, through a new class, `MOM_file`, for reading and writing of axis-based model fields.
A common API for interacting with files is defined in the `MOM_file` class, and two implementations are provided:
* `MOM_infra_file`, using the "infra" framework (i.e. FMS)
* `MOM_netcdf_file`, using native netCDF framework
This separation allows us to define certain generic functions by class, and platform-specific functions by type.  It will also allow for removal of legacy FMS1 operations which are no longer used for the majority of I/O but are still required for isolated MOM files.
This change will allow us to "remove" such files from the FMS system and reimplement them with native MOM operations, while still preserving a common structure for both …

Generic I/O layer for infra and netCDF

---

.gitlab-ci.yml
.testing/Makefile
.testing/tc4/Makefile.in

Two commits related to allowing the run/testing of .testing to happen in in a different location to where the git repo is cloned and the executables are built
- 0f5e6ca6a separates the compiling and running of the "prepoc" codes. This was needed since we can not compile on the compute nodes, and once we move the runners we will not be able to run in the same place we compile
- 91f32885c allows the work/ and results/ directories to be re-located
- d70feab3f is unrelated and just aesthetic, reporting all the green "PASS"s which I find therapeutic to see

Pipeline patch for .testing

---

src/framework/MOM_horizontal_regridding.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90

Added the ability to use reproducing sums to create spatially homogenized tracer fields when Z_INIT_HOMOGENIZE = True, for rotational symmetry and consistency across layouts.  The previous version had used non-reproducing sums.  This new code is used when HOR_REGRID_ANSWER_DATE >= 20230101, and the comments describing HOR_REGRID_ANSWER_DATE have been updated to reflect this. As a part of this change, the new publicly visible routine homogenize_field was added to the MOM_horizontal_regridding module, so that the homogenization occurs in a single part of the code rather than being spread across several files.
By default this commit could lead to answer changes in some cases, depending on whether and how HOR_REGRID_ANSWER_DATE is set, but it turns out that the existing single_column test …

+(*)Use reproducing sums to homogenize fields

---

src/diagnostics/MOM_wave_speed.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90

VarMix_CS%slope_x was being set with units of [Z L-1 ~> nondim], but described in comments as though it was simply [nondim], and then used in the (apparently unused?) calculate_slopes=.false. branch in calc_slope_functions_using_just_e as though its units actually were [nondim].  This commit corrects this inconsistency, while also rescaling the internal slope variables in that routine to also have the proper units of [Z L-1 ~> nondim].  In so doing, several rescaling factors could be eliminated from the calculations.  In addition, the slopes used in calc_QG_Leith_viscosity were also being rescaled with the wrong factor or had dimensionally incorrect tiny values in some denominators, and this has been corrected as well.  In testing this rescaling fix, a number of other bugs were identified …

(*)Corrected the units of VarMix_CS%slope_x

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/diagnostics/MOM_debugging.F90
src/diagnostics/MOM_diagnostics.F90

This PR has three commits that improve the diagnostics code, by adding to the description of internal variables and their units, by using rescaled units for 6 globally averaged temperature and salinity diagnostics, and by adding unscale arguments to the various check_redundant and chksum_vec routines that can be used to give debugging error messages that are invariant to dimensional rescaling.  A separate commit adds unscale arguments to the various check_redundant calls so that any error messages that are generated by inconsistent redundant points will be invariant to the unit scaling that is in use.  All answers and typical output are bitwise identical, but there are new optional arguments to several publicly visible routines.
- NOAA-GFDL/MOM6@c4176e5b7 …

Minor diagnostics code improvements and unit annotations

---

src/diagnostics/MOM_spatial_means.F90
src/framework/MOM_array_transform.F90
src/framework/MOM_checksums.F90
src/framework/MOM_horizontal_regridding.F90
src/framework/MOM_intrinsic_functions.F90
src/framework/MOM_io.F90
src/framework/MOM_restart.F90

This PR includes a series of 7 commits (1 per file) that add or amend the documentation of the units of 476 arguments and internal variables, in large part to clearly indicate which variables must be unscaled and which may be scaled.  Only comments are changed, and all answers are bitwise identical.
-NOAA-GFDL/MOM6@f8751de55 Document units of invcosh and its argument
-NOAA-GFDL/MOM6@dd946158b Revise argument units in MOM_horizontal_regridding
-NOAA-GFDL/MOM6@f8f127521 Document units of arguments in MOM_array_transform
-NOAA-GFDL/MOM6@f7f2de9d2 Document units of arguments in MOM_restart
-NOAA-GFDL/MOM6@625ff637c Document units of arguments in MOM_io
-NOAA-GFDL/MOM6@ccd62c1eb Document units of variables in MOM_checksums
-NOAA-GFDL/MOM6@251d9be2b Document …

Document 476 framework argument and variable units

---

src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_CVMix_conv.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_regularize_layers.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_sponge.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/parameterizations/vertical/MOM_vert_friction.F90

This PR includes a series of 18 commits (1 per file) that add or amend the documentation of the units of 245 internal variables in various parameterization modules.  It also revises the terminology in a number of the comments describing the thickness_diffuse module for greater clarity of language.  This PR might be a good candidate for a squash merge 
Apart from a few unused variables that eliminated, only comments are changed and all answers are bitwise identical.
- NOAA-GFDL/MOM6@492afee31 Better terminology in thickness_diffuse module
- NOAA-GFDL/MOM6@d8191d90f Document units of variables in MOM_tidal_forcing
- NOAA-GFDL/MOM6@62952b6d7 Document units of variables in MOM_internal_tides
- NOAA-GFDL/MOM6@d4ccba775 Document units of 7 variables in MOM_sponge …

Document 245 parameterization variable units

---

src/parameterizations/lateral/MOM_MEKE.F90

This commit fixes a number of dimensional rescaling issues that were introduced to the MOM_MEKE code with the SmartRedis related options. Specifically, it adds a missing scale factor for the time_interp_external call for the offline data eddy kinetic energy used in MEKE when EKE_SOURCE=file.  It also corrects the documented units and conversion factors for 4 diagnostics related to machine learning within MEKE.  This commit also adds or amends comments to document the units of 27 internal variables in MOM_MEKE.F90, and corrected a few spelling errors in comments.   All answers and output are bitwise identical in the existing MOM6-examples test suite, but there may be other examples where the units or rescaling of diagnostics are corrected or (in cases using EKE_SOURCE=file) where …

(*)Fix MEKE scaling issues with SmartRedis options

---

src/core/MOM_CoriolisAdv.F90
src/core/MOM_checksum_packages.F90
src/core/MOM_density_integrals.F90
src/core/MOM_porous_barriers.F90
src/ice_shelf/MOM_marine_ice.F90
src/ice_shelf/user_shelf_init.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_state_initialization.F90
src/user/MOM_controlled_forcing.F90
src/user/MOM_wave_interface.F90
src/user/Phillips_initialization.F90
src/user/SCM_CVMix_tests.F90
src/user/benchmark_initialization.F90
src/user/circle_obcs_initialization.F90
src/user/dense_water_initialization.F90
src/user/dumbbell_surface_forcing.F90
src/user/dyed_channel_initialization.F90
src/user/dyed_obcs_initialization.F90
src/user/external_gwave_initialization.F90
src/user/lock_exchange_initialization.F90
src/user/shelfwave_initialization.F90
src/user/user_change_diffusivity.F90
src/user/user_revise_forcing.F90

Added or amended comments to document the units of 75 variables in 23 files in the src/core, src/initialization, src/ice_shelf and src/user directories that had been overlooked when the other variables in these files had their units documented.  Only comments are changed, and all answers are bitwise identical.

Document units of 75 scattered variables

---

src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_NEMO.F90
src/equation_of_state/MOM_EOS_TEOS10.F90
src/equation_of_state/MOM_EOS_UNESCO.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_linear.F90
src/equation_of_state/MOM_TFreeze.F90

Added or amended comments to document the units of about 250 variables in 6 files in the src/equation_of_state directories.  Also revised comments to make it clear that the MOM6 code for the UNESCO equation of state is based on the Jackett and MacDougall (1995) refit to the UNESCO equation of state (which uses potential temperature as a state variable) as opposed to the original UNESCO equation of state, as documented in an appendix to Gill (1982) (which uses in-situ temperature as a state variable).  Also corrected a handful of spelling errors in comments.  Only comments are changed, and all answers are bitwise identical.

Document units of about 250 EOS variables

---

.gitlab/pipeline-ci-tool.sh

After a recent update to how the build environment is defined within MOM6-examples, the "no libraries" build test (unique to MOM6) is failing because the Makefile now no longer contains the environment. This commit overrides a CPP macro that points to the bash script that is needed.
I tested the pipeline at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/18205

Fixes build failure in gitlab pipeline

---

src/core/MOM.F90
src/core/MOM_checksum_packages.F90
src/core/MOM_dynamics_split_RK2.F90
src/parameterizations/lateral/MOM_MEKE.F90

This commit makes a set of changes so that the chksums output by the OM4_05 configuration with DEBUG = True reproduce between 252 and 256 PE runs (note that the solutions themselves already reproduced).  This is includes adding a new optional omit_corners argument to the MOM_state_chksum and MOM_thermo_chksum routines, and revising the haloshift, omit_corners or symmetric arguments on 6 subroutine calls, to check more appropriate loop ranges.  All answers are bitwise identical, but there is a new optional argument to three publicly visible debugging routines.

+Make output reproduce across layout if DEBUG=True

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/FMS_cap/ocean_model_MOM.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
config_src/drivers/unit_drivers/MOM_sum_driver.F90

Added or amended comments to document the units of 30 variables in FMS_cap/MOM_surface_forcing_gfdl.F90, FMS_cap/ocean_model_MOM.F90, solo_driver/MOM_surface_forcing and unit_drivers/MOM_sum_driver.F90.  Only comments are changed, and all answers are bitwise identical.

Document units of 30 driver variables

---

src/core/MOM_barotropic.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_file_parser.F90
src/initialization/MOM_fixed_initialization.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/oil_tracer.F90

This PR consists of two commits, the first of which adds the new optional argument unscale to the two interfaces wrapped by log_param for real variables.  This argument allows for rescaled variables to be passed into these log_param
calls, without having to be multiplied by this unscaling factor, and it will allow the units and unscale arguments to be easily compared for consistency.  The second commit uses this new optional argument in 10 calls to the log_param routines.  All answers and output are bitwise identical.
The first of these two commits covers the non-controversial parts of MOM6 PR #300.
- NOAA-GFDL/MOM6@8c8fbb3a7 Use unscale argument in 10 log_param calls
- NOAA-GFDL/MOM6@c90426494 +Add optional unscale argument to log_param_real

+Add and use optional unscale argument to log_param_real

---

src/diagnostics/MOM_obsolete_params.F90
src/parameterizations/vertical/MOM_CVMix_shear.F90

Because `get_param()` is case-sensitive, CVMix_shear_is_used will incorrectly return false if USE_PP81 = True and USE_LMD94 = False.  This would cause such cases to fail to reproduce across restarts or use uninitialized or incorrect arrays, but because the Pacanowski and Philader parameterization is very out-dated it appears not to be used in any active test case.  Moreover, no one has reported any such issues yet.  Therefore, rather than adding a flag to reproduce the old (unreproducing) results, this commit simply corrects this bug. All answers are bitwise identical in all known MOM6 configurations, but this could lead to answer changes in certain unlikely configurations.

(*)Fix bug in CVMix_shear_is_used if USE_PP81=True

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/framework/MOM_hor_index.F90
src/framework/MOM_io.F90
src/framework/MOM_io_file.F90
src/framework/MOM_netcdf.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

This patch introduces `read_netCDF_data`, a new method for reading netCDF datasets using the native netCDF I/O interface.  It is designed to resemble the existing `MOM_read_data` function.
Motivation
----------
Legacy input files may contain content which is not supported by the newest framework I/O (FMS).  In order to retain support for these input files, particularly over a wider range of compilers, this patch provides an alternative method for reading these files.
Interface
---------
As with `MOM_read_data`, the function is provided with a netCDF filepath and a variable name, and returns the values to a provided variable.
The `global_file` and `file_may_be_4d` flags have been dropped, since they are related to specific FMS2 compatibility issues.  (Global vs domain-decomposed reads is …

Direct netCDF data reads

---

ac/Makefile.in
ac/configure.ac
ac/deps/Makefile.fms.in
ac/deps/configure.fms.ac

The introduction of makedep means that Python is now a dependency of the MOM6 compilation.  On some systems, we cannot assume that `python` is the name of the interpreter, and strictly should not even assume that it exists.
This is notably an issue on the recent MacOS M1 systems, which use `python3` as its interpreter, and do not provide one named `python`.
This patch adds macros to the MOM6 and FMS autoconf builds to detect if Python is on the system, and makes a few attempts to determine the name of the interpreter (python, python3, python2).  Perhaps more can be done here, but this is probably sufficient in nearly all cases.

Autoconf configuration of Python

---

src/framework/MOM_io.F90

reopen_MOM_file includes an inquire test to determine whether we are attempting to reopen an existing file.  If missing, it will attempt to instead create the file.
The switch from FMS to netCDF I/O exposed a race condition here, where one rank may create the file, and a another rank may incorrectly identify the file as existing.  This resulted in a segmentation fault.
Unsure why this was not detected before, it could be that FMS was more resilient to the possibility of missing files.
Regardless, it makes sense to use a barrier after the inquire call to ensure that each rank is reporting the correct state.  This patch does this with a sync_PEs call.

sync reopen_MOM_file existence inquiry

---

src/parameterizations/vertical/MOM_diabatic_driver.F90

Restored an else that was inadvertently deleted as a part of code clean up in MOM-ocean/MOM6 PR #1127 on June 5, 2020.  This bug causes bulkmixedlayer to be called twice (with cumulative effects) when 0. < ML_MIX_FIRST < 1., and not to be called at all when ML_MIX_FIRST = 1.  This bug only applies to cases where the bulk mixed layer is enabled by setting BULKMIXEDLAYER=True and USE_REGRIDDING=False (i.e., in layered mode configurations with active thermodynamics), however because the default value of ML_MIX_FIRST = 0, this bug does not appear to be used in any active test cases, and it went undetected when it was introduced.  All answers in the MOM6-examples test suite are bitwise identical, but this could change answers in some cases.

(*)Fix a bug with BULKMIXEDLAYER & ML_MIX_FIRST>0

---

src/diagnostics/MOM_sum_output.F90

Revised write_energy so that only the root_PE attempts to open, reopen or write to a netcdf file.  Although FMS can handle cases where multiple PEs make the same calls with internal logic, this change avoids requiring such internal (hidden) logical tests, and instead is more explicit on what is actually intended.  This change is complementary to MOM6 dev/gfdl PR #328, which adds internal logic to handle the case where all PEs are making a call to reopen a single netcdf file.  All answers and output are bitwise identical.

Only root_PE makes write_energy netcdf file calls

---

src/framework/MOM_io.F90
src/framework/MOM_io_file.F90
src/framework/MOM_netcdf.F90

Fixed two horizontal indexing bugs in `get_field_nc()`, where the difference between the array starting index (always 1 in this subroutine) and the values in the handle argument were not being taken into account when the array was being passed in with only its computational domain.  Also initialized the internal `unlim_index` array in `get_netcdf_fields()` to fix a problem with using an uninitialized array that was being flagged when run in debug mode.  With this commit, the model is once again reproducing the expected answers when rescaling is applied for vertical distances or time.  All answers are bitwise identical in cases that were working before.
This commit addresses the issue at github.com/NOAA-GFDL/MOM6/issues/333, which can be closed once this commit is merged into dev/gfdl.

*Fix indexing bugs in get_field_nc

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/ALE/MOM_remapping.F90
src/ALE/PPM_functions.F90
src/ALE/coord_hycom.F90
src/ALE/regrid_edge_values.F90
src/ALE/regrid_interp.F90

Add "PPM_CW" as an option for INTERPOLATION_SCHEME and REMAPPING_SCHEME. This implements the original Colella and Woodward (1984) edge calculation for PPM. It computes 4th order explicit edge values but constrains them to produce a monotonic profile, which is particularly effective for remapping.
INTERPOLATION_SCHEME="PPM_CW" is identical to "REMAPPING_PPM_HYBGEN", but hybgen_PPM_coefs has been replaced by edge_values_explicit_h4cw and PPM_monotonicity for flexibility and to simplify upgrades. Answers with existing INTERPOLATION_SCHEME options are unchanged.
REMAPPING_SCHEME="PPM_CW" is a new option which can perform better than "P1M_H2" when used with INTERPOLATION_SCHEME="PPM_CW".  Answers with existing REMAPPING_SCHEME options are unchanged.
HYCOM1 regridding walks a monotonic density …

Add PPM_CM and HYCOM1_ONLY_IMPROVES

---

src/core/MOM_check_scaling.F90

Updated check_MOM6_scaling_factors and compose_dimension_list to reflect the fact that MOM6 is now doing dimensional consistency testing for temperature (via [C ~> degC]) and salinity (via [S ~> ppt]), with an expanded dimension of the scaling key from 6 to 8 and additional calls to add_scaling.  Also updated the weights on the add_scaling calls, which are essentially counts of the frequency of the various unit descriptors in the MOM6 code, to reflect only the counts of variables with doxygen comments (i.e., arguments, function return values and elements of types) but excluding the user, framework and diagnostics directories and the passive tracer packages.  All model solutions are bitwise identical, but there will be updated suggestions for combinations of scaling factors that minimize …

+Update check_MOM6_scaling_factors with C and S

---

src/core/MOM.F90
src/core/MOM_barotropic.F90
src/core/MOM_checksum_packages.F90
src/core/MOM_dynamics_split_RK2.F90
src/tracer/MOM_offline_main.F90

Redid the scaling of 52 checksum or check_redundant calls for thickness or transports to use the MKS counterparts of the thickness units (i.e., m and m3/s or kg/m2 and kg/s, depending on the Boussinesq approximation), rather than always rescaling them to m or m3/s.  In Boussinesq mode, everything remains the same, but in non-Boussinesq mode, this means that the model's actual variable are being checksummed and not a version that is rescaled by division by the (meaningless?) Boussinesq reference density.  All solutions are bitwise identical, but some debugging output will change in non-Boussinesq mode.

Checksum unrescaled non-Boussinesq thicknesses

---

src/core/MOM_unit_tests.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Jackett06.F90
src/equation_of_state/MOM_EOS_NEMO.F90
src/equation_of_state/MOM_EOS_Roquet_SpV.F90
src/equation_of_state/MOM_EOS_Roquet_rho.F90
src/equation_of_state/MOM_EOS_TEOS10.F90
src/equation_of_state/MOM_EOS_UNESCO.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_Wright_full.F90
src/equation_of_state/MOM_EOS_Wright_red.F90
src/equation_of_state/MOM_EOS_linear.F90
src/equation_of_state/MOM_TFreeze.F90
src/equation_of_state/MOM_temperature_convert.F90
src/equation_of_state/_Equation_of_State.dox

This PR includes a series of commits that add 4 new equation of state (EoS) modules, add and deploy unit testing to the EoS modules, correct actual bugs in every one of the pre-existing modules, adds missing routines to the previous modules, and adds parentheses to most of the EoS modules (but not LINEAR or WRIGHT) to specify the order of arithmetic so that they will reproduce answers across compilers and levels of optimization.  By default, answers are bitwise identical when EQN_OF_STATE = LINEAR or EQN_OF_STATE = WRIGHT, but a survey of the community suggested that the other equations of state were not being used yet, so answers will change due to both bug-fixes and changes in the order of arithmetic for all the other equations of state.  Despite all of these changes, answers are …

*+Refactor, correct and augment the MOM6 EoS code

---

config_src/drivers/nuopc_cap/mom_cap.F90
config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_io_infra.F90
src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/framework/MOM_io.F90
src/framework/MOM_io_file.F90
src/framework/MOM_restart.F90
src/initialization/MOM_coord_initialization.F90

This patch removes the calls to FMS1 I/O (fms_io_mod, mpp_io_mod) from the FMS2 infra layer, and now exclusively uses FMS2 for those operations.
FMS2 I/O is currently restricted to files which use domains; files which do not use them are delegated to the native netCDF layer.  The reasoning for this is that FMS is required to define the formatting of domain-decomposed I/O; for single-file I/O, this is not necessary.
This does not remove all references to FMS1 I/O from MOM6, only those in the I/O layer.
Several minor changes are included to accommodate the change:
* MOM restart I/O now always reports its MOM domain.  Previously, the domian was omitted when PARALLEL_RESTARTFILES was false, in order to trick FMS into handling this as a single file.  We now generate a new domain with an IO …

Removal of FMS1 I/O from FMS2 I/O infra

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

Due to some machines reporting a regression in the mixed layer restratification code, this patch reverts the calculation of the growth time in a separate function.
Most of the content related to comments and parameter setup have been retained, even if those parameters are no longer used.

Reversion of MOM_mixed_layer_restrat growth_time

---

src/ALE/MOM_ALE.F90
src/core/MOM_interface_heights.F90
src/diagnostics/MOM_obsolete_params.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/tracer/MOM_tracer_Z_init.F90
src/user/DOME2d_initialization.F90
src/user/DOME_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/Neverworld_initialization.F90
src/user/Phillips_initialization.F90
src/user/Rossby_front_2d_initialization.F90
src/user/SCM_CVMix_tests.F90
src/user/adjustment_initialization.F90
src/user/baroclinic_zone_initialization.F90
src/user/benchmark_initialization.F90
src/user/circle_obcs_initialization.F90
src/user/dense_water_initialization.F90
src/user/dumbbell_initialization.F90
src/user/external_gwave_initialization.F90
src/user/lock_exchange_initialization.F90
src/user/seamount_initialization.F90
src/user/sloshing_initialization.F90
src/user/soliton_initialization.F90
src/user/user_initialization.F90

This PR includes a series of commits that improve the accuracy with which MOM6 is initialized in certain non-Boussinesq configurations and which extend the capabilities of the MOM_interface_heights module to include new routines to properly convert the vertical extent of layers (in height units) to thicknesses (even when in non-Boussinesq mode).  These changes lead to a notable simplification of the code in some places where the calculations are working in, depth space, and to the elimination of the use of GV%H_to_Z or GV%Z_to_H, especially in a number of user modules.  These changes greatly reduce the dependence of non-Boussinesq configurations on the value of the Boussinesq reference density, and they will lead to more accurate initialization of non-Boussinesq models.  The changes in …

+(*)Better initialization of non-Boussinesq models

---

ac/configure.ac
src/framework/posix.F90
src/framework/posix.h

This patch extends the generic wrappers of sigsetjmp to all of the *jmp wrapper functions in <setjmp.h>
The C standard allows these to be defined as macros, rather than explicit functions, which cannot be referenced by Fortran C bindings, so we cannot assume that these functions exist, even when using a compliant libc.
As with sigsetjmp, these functions are now disabled on default, and raise a runtime error if called by the program.  Realistically, they will only be defined by an autoconf-configured build.
This is required for older Linux distributions where libc does not define longjmp.

POSIX: generic wrappers for all setjmp.h symbols

---

.testing/Makefile
ac/deps/Makefile

This patch modifies the `ac/deps` Makefile used to build the FMS depedency.  The autoconf compilation is now done entirely outside of the `ac/deps/fms/src` directory.  This keeps the FMS checkout unchanged and allows us to better track any development changes in that library during development.
The .testing/Makefile was also modified to use existing rules in deps/Makefile rather than duplicating them.

Autoconf: External FMS build configuration 

---

.testing/Makefile
ac/configure.ac

MOM6 requires an explicit MOM_memory.h header to define its numerical field memory layout.  Previously, autoconf provided a flag to configure this with `--enable-*`, but was prone to two issues:
* The binary choice of symmetric/nonsymmetric prevented use of static headers.
* It was an incorrect use of `--enable-*`, which is intended to enable additional internal features; it is not used to select a mode.
To address these issues, we drop the flag and replace it with an AC_ARG_VAR variable, MOM_MEMORY, which is a path to the file.  This variable will default to dynamic symmetric mode,
config_src/memory/dynamic_symmetric/MOM_memory.h
so there should be no change for existing users.
To the best of my knowledge, no one used the `--enable-*` flag, nor was it used in any automated systems …

Autoconf: Explicit MOM_memory.h configuration

---

.testing/Makefile
.testing/tools/parse_fms_clocks.py

The very crude MOM_input parser in the automatic profiler did not support subparameters (e.g. MLE% ... %MLE), which caused an error when trying to read the FMS clock output.
This patch adds the support, or at least enough support to avoid errors.

Profiling: subparameter parser support

---

src/core/MOM.F90
src/core/MOM_density_integrals.F90
src/core/MOM_interface_heights.F90
src/core/MOM_variables.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_Wright_full.F90
src/equation_of_state/MOM_EOS_Wright_red.F90
src/equation_of_state/MOM_EOS_linear.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/tracer/MOM_offline_main.F90

This PR includes a pair of commits that add code to calculate the layer averaged specific volumes, either using analytical expressions or quadrature, and the new routines `thickness_to_dz` and `calc_derived_thermo` to make use of this to convert layer thicknesses to vertical distances in all cases.  There is new unit testing of the layer averaged specific volumes included in this PR.  The `thickness_to_dz` calls have been extensively tested (and appear to be correct) in much more extensive changes on a separate branch that will be in coming PRs, but they are not yet being exercised with this commit.   The new public interfaces include `avg_specific_vol`, `average_specific_vol`, `avg_spec_vol_Wright`, `avg_spec_vol_Wright_full`, `avg_spec_vol_Wright_red`, `avg_spec_vol_linear`, …

+Add thickness_to_dz, calc_derived_thermo and avg_specific_vol

---

src/framework/MOM_io.F90
src/framework/MOM_io_file.F90

MOM IO was using the `threading` flag rather than `fileset` to determine whether a file should be forced as single file rather than domain-decomposed.  This patch applies the correct flag.

Use fileset rather than threading for decompositon

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/infra/FMS1/MOM_interp_infra.F90
config_src/infra/FMS2/MOM_interp_infra.F90
src/core/MOM_open_boundary.F90
src/framework/MOM_horizontal_regridding.F90
src/framework/MOM_interpolate.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/tracer/MOM_CFC_cap.F90

All instances of an FMS ID to the internal interpolation content is replaced with a derived type containing additional metadata recording the field's origin filename and fieldname.
This additional information is required in order to replicate the axis data from the field, which is no longer provided by FMS2.
The abstraction of this type also allows us to either extend it or redefine it in other frameworks as needed in the future.
This primarily affects the usage of the following functions:
- init_external_field
- time_interp_external
- horiz_interp_and_extrap_tracer
References to FMS1 move data into an `axistype`, but the contents are transferred to an `axis_info` when leaving the FMS1 layer.  FMS2 directly populates the `axis_info` content.
The `get_external_field_info` calls are …

FMS2: Replace time_interp_external IDs with a MOM-defined type

---

.github/workflows/coupled-api.yml
.github/workflows/coverage.yml
.github/workflows/documentation-and-style.yml
.github/workflows/expression.yml
.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml
.github/workflows/other.yml
.github/workflows/perfmon.yml
.github/workflows/regression.yml
.github/workflows/stencil.yml

- Updates actions/checkout from v2 to v3 . This simply uses the newer version of checkout and has no immediate impact, but does anticipate the inevitable need to roll forward.
Suggestion comes from https://github.com/NCAR/MOM6/pull/231#issuecomment-1347224581 thanks to @jedwards4b) . I had imagined this commit was going to be cherry-picked some time ago but it seems it was not.

github workflows: update to use actions/checkout@v3

---

config_src/infra/FMS2/MOM_io_infra.F90

The FMS2 function `get_unlimited_dimension_name` raises a netCDF error if no unlimited dimension is found.  This is problematic for legacy or externally created input files which may have not identifed their time axis as unlimited.
This patch adds a new function, `find_unlimited_dimension_name` which mirrors the FMS2 function but returns an empty string if none are found.
This is an internal function, not intended for use outside of the module.

FMS2: Safe inspection of unlimited dim name

---

src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

Refactors the internal tide code in MOM_internal_tides and MOM_diabatic_driver to consolidate it in the MOM_internal_tides module and allow the control structure for that module to be made opaque.  This includes moving the internal wave speed diagnostics and the call to wave_speeds or other code setting the internal wave speeds into propagate_int_tide.  The get_param calls for INTERNAL_WAVE_CG1_THRESH and UNIFORM_TEST_CG were moved from the diabatic module to the MOM_internal_tides module. The wave_speed_CS and uniform_test_cg were removed from diabatic_CS and added to int_tide_CS.  The Nb argument to propagate_int_tide has been made intent inout, as it is now usually set via the call to wave_speeds in that routine, but for certain tests it could use the value passed in from …

+Refactor internal_tides interface

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
config_src/drivers/solo_driver/user_surface_forcing.F90
src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/framework/MOM_unit_scaling.F90

Add new allocatable tau_mag arrays to the forcing and mech_forcing types to hold the magnitude of the wind stresses including gustiness contributions. There is also a new tau_mag diagnostic.  This same information in tau_mag is being transformed into ustar, but these changes avoid division by the Boussinesq reference density (GV%Rho0), and allow for a more accurate calculation of derived fields when in non-Boussinesq mode, without having to multiply and divide by GV%Rho0.  There is also a new optional tau_mag argument to extract_IOB_stresses to support these changes.  These new arrays are not being used yet in the MOM6 solutions, but they are being allocated and populated in the routines that set the ustar fields, and they have been tested in changes to the modules that use ustar that …

+Add fluxes%tau_mag and forces%tau_mag

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

Fixed several problems with the recently added Bodner mixed layer restratification parameterization code.
- Corrected the dimensional rescaling in the expressions for psi_mag by adding a missing factor of US%L_to_Z.
- A logical branch was added based on the correct mask for land or OBC points to avoid potentially ill-defined calculations of the magnitude of the Bodner parameterization streamfunction, some which were leading to NaNs.
- Set a tiny but nonzero default value for MIN_WSTAR2 to avoid NaNs in some calculations of the streamfunction magnitude.
- Revised the expression for dd within the mu function in a mathematically equivalent way to avoid any possibility of taking a fractional exponential power of a tiny negative number due to truncation errors, which was leading to NaNs in …

*+Fix problems in mixedlayer_restrat_Bodner

---

config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90

This patch adds wrappers to the set_domain and nullify_domain functions used in FMS1 for internal FMS IO operations.  These are not used in FMS2, so the wrapper functions are empty.
This is required to eliminate FMS1 IO dependencies in SIS2.

FMS2: New interface to set/nullify_domain

---

ac/Makefile.in
ac/configure.ac

The autoconf Python interpreter search was slightly modified to search for Python even if $PYTHON is set to an empty string.  This is done by unsetting PYTHON if it is set but empty, then following the usual macro.
This was required since `export PYTHON` in a Makefile will create the `PYTHON` variable but will assign it no value (i.e. empty string). This causes issues in some build environments.
The backup `configure~` script was also added to the developer `ac-clean` cleanup rule.

Autoconf: Find Python, even if PYTHON is empty

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_hybgen_regrid.F90
src/ALE/MOM_regridding.F90
src/ALE/coord_adapt.F90
src/ALE/coord_hycom.F90
src/ALE/coord_rho.F90
src/initialization/MOM_state_initialization.F90
src/tracer/MOM_offline_main.F90

Refactored 6 files in the ALE directory to calculate the nominal depth in thickness units in a single place (it is done in regridding_main now) and pass it to the various places where it is used, in a preparatory step to modify how this calculation is done in non-Boussinesq mode.  There are new arguments to several publicly visible routines, including:
- Add non_depth_H arguments to hybgen_regrid, build_zstar_grid, build_sigma_grid, build_rho_grid, build_grid_HyCOM1, build_grid_adaptive, build_adapt_column and build_grid_arbitrary
- Add optional zScale arguments to build_zstar_grid and build_grid_HyCOM1
- Add unit_scale_type arguments to regridding_main, ALE_regrid_accelerated and ALE_offline_inputs
Also eliminated an incorrect rescaling GV%Z_to_H facto when calculating the total column …

+Refactor nominal depth in ALE code

---

config_src/drivers/FMS_cap/ocean_model_MOM.F90
config_src/drivers/mct_cap/mom_ocean_model_mct.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
config_src/drivers/solo_driver/MOM_driver.F90
src/core/MOM.F90

As described in issue #372, I would like to be able to create restart files that contain information about the particle location. These files should be written at the same time as other restart files. I cannot add these calls directly to the driver, because the driver does not have information about the particle location. 
We have opted to add `save_MOM6_internal_state` as a subroutine in `MOM.F90`, and to call it from each of the drivers. We hope this will allow for more new packages to write restart files in the future. 
I have tested these additions for `solo_driver` and `FMS_cap`, but I don't have access to the other drivers, so I haven't been able to test them. 
cc @adcroft

Add save_MOM6_internal_state subroutine to MOM.F90 and call during restart

---

src/ALE/MOM_ALE.F90
src/core/MOM.F90
src/core/MOM_interface_heights.F90
src/core/MOM_variables.F90
src/tracer/MOM_offline_main.F90

Added the integer valid_SpV_halo to the thermo_var_ptrs type to indicate whether the SpV_array has been updated and its valid halo size, to facilitate error detection and debugging in non-Boussinesq mode.  Tv%valid_SpV_halo is set to the halo size in calc_derived_thermo or after a halo update is done to tv%SpV_avg, and it is set to a negative value right after calls that change temperatures and salinities (such as by ALE remapping) unless there is a call to calc_derived_thermo.  Tests for the validity of tv%SpV_avg are added to the routines behind thickness_to_dz, with fatal errors issued if invalid arrays would be used, but more tests could perhaps be used in any parameterization routines where tv%SpV_avg is used directly.  Handling the updates to tv%SpV_avg this way helps to avoid …

+Add tv%valid_SpV_halo to debug non-Boussinesq mode

---

src/core/MOM_verticalGrid.F90

Use RHO_KV_CONVERT instead of RHO_0 to set the non-Boussinesq version of GV%m_to_H, so that there is a mechanism for testing the independence of the fully non-Boussinesq mode from the Boussinesq reference density.  With this change, GV%Z_to_H is not guaranteed to be equal to (GV%Z_to_m*GV%m_to_H), with the latter expression preferred when setting parameters. By default the two parameters are the same, and they will probably only ever differ in testing the code.  All Boussinesq solutions are bitwise identical, but there are differences in the description of RHO_KV_CONVERT that will appear in MOM_parameter_doc files.

(*)+Use RHO_KV_CONVERT to set non-Boussinesq GV%H_to_m

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_forcing_type.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_sponge.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Add new arguments to 7 routines that will be needed for the non-Boussinesq capability, but do not use them yet, so that there will be fewer cross file dependencies as the various changes are being reviewed simultaneously.  The impacted interfaces are MEKE_int, vertvisc_coef, sumSWoverBands, KPP_calculate, differential_diffuse_T_S, set_BBL_TKE, and apply_sponge In the three step_MOM_dyn_... routines and in calculateBuoyancyFlux1d, this change includes calls to thickness_to_dz to calculate the new vertical distance arrays that will be passed into vertvisc_coef or sumSWoverBands.  The only place where the new arguments are actually used is in sumSWoverBands and set_opacity where the changes are particularly simple.  All answers are bitwise identical, but there are new non-optional arguments …

+Add new (not yet used) arguments to 7 routines

---

.testing/tc3/MOM_input
src/parameterizations/vertical/MOM_vert_friction.F90

Sorts out warnings about KVML being deprecated when KVML is not provided.
- We were reading KV_ML_INVZ2 without logging, then checking for KVML and finally logging based on a combination of the two. This had the side effect that we get warnings about not using KVML even if KVML was not present.
- The fix checks for KVML first, and then changes the default so that when KVML=1e-4 is replaced by KV_ML_INVZ2=1e-4 we end up with no warnings and KVML can be obsoleted safely. Note: this commit alone does not remove all warnings from the MOM6-examples suite because we still need to fix the MOM_input in configurations that still use KVML. That [PR](https://github.com/NOAA-GFDL/MOM6-examples/pull/401) has been submitted and should be handled first to avoid unnecessary updates to the parameter doc …

Fix logic for setting KV_ML_INVZ2 from KVML

---

src/core/MOM_PressureForce_FV.F90

Use the new runtime parameter RHO_PGF_REF instead of RHO_0 to set the reference density that is subtracted off from the other densities when calculating the finite volume pressure gradient forces.  Although the answers are mathematically equivalent for any value of this parameter, a judicious choice can reduce the impacts of roundoff errors by about 2 orders of magnitude.  By default, RHO_PGF_REF is set to RHO_0, and all answers are bitwise identical.  However, there is a new runtime parameter that appears in many of the MOM_parameter_doc.all files.

+Use RHO_PGF_REF for the pressure gradient forces

---

src/diagnostics/MOM_sum_output.F90

The message that a file is being created was issued as a WARNING when we all agree it should really be a NOTE. Depth_list.nc is read if it is present to avoid recomputing a sorted list, but the absence of the file is not an error and does not warrant a warning.
Changes:
- Changed WARNING to NOTE.
- Removed MOM_mesg from imports since it wasn't being used.

Converted warning about depth_list to a note

---

src/ALE/MOM_regridding.F90

The interpolation scheme for state-dependent diagnostic coordinates was incorrectly registering as the same parameter as for the main model ("INTERPOLATION_SCHEME"). This meant it was never possible to change the diagnostics vertical interpolation scheme from the default (which was not the same as the main model).
This fix registers the generated parameter name which was always computed but not used. A typical example of the generated parameter is "DIAG_COORD_INTERP_SCHEME_RHO2".
Affects these doc files:
- ice_ocean_SIS2/Baltic_OM4_025/MOM_parameter_doc.all
- ice_ocean_SIS2/Baltic_OM4_05/MOM_parameter_doc.all
- ice_ocean_SIS2/OM4_025/MOM_parameter_doc.all
- ice_ocean_SIS2/OM4_05/MOM_parameter_doc.all
- ice_ocean_SIS2/OM_1deg/MOM_parameter_doc.all
The fix removes one of the many warnings …

Correct diagnostic coordinate interpolation scheme

---

src/diagnostics/MOM_wave_speed.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90

Fixed a bug in which wave_speed_init was effectively discarding any values of mono_N2_depth passed to it via the optional argument mono_N2_depth, but also changed the default value of RESOLN_N2_FILTER_DEPTH, which was previously being discarded, to disable the monotonization and replicate the previous results. There were also clarifying additions made to the description how to disable RESOLN_N2_FILTER_DEPTH.  This will change some entries in MOM_parameter_doc files, and it will change solutions in cases that set RESOLN_N2_FILTER_DEPTH to a non-default value and have parameter settings that use the resolution function to scale their horizontal mixing.  There are, however, no known active simulations where the answers are expected to change.

+(*)Fix wave_speed_init mono_N2_depth bug

---

src/diagnostics/MOM_sum_output.F90
src/initialization/MOM_coord_initialization.F90

Revised the calculation of gprime and the coordinate densities (GV%Rlay) in fully non-Boussinesq mode to use the arithmetic mean of adjacent coordinate densities in the denominator of the expression for g_prime in place of RHO_0. Also use LIGHTEST_DENSITY in place of RHO_0 to specify the top-level coordinate density in certain coordinate modes.  Also made corresponding changes to the fully non-Boussinesq APE calculation when CALCULATE_APE is true.
This commit will change answers in some fully non-Boussinesq calculations, and an existing runtime parameter is used and logged in some new cases, changing the MOM_parameter_doc file in those cases.

*+Revise non-Boussinesq gprime expressions

---

src/parameterizations/lateral/MOM_thickness_diffuse.F90

Refactored thickness_diffuse when in non-Boussinesq mode to avoid any dependencies on the Boussinesq reference density, and to translate the volume streamfunction into the mass streamfunction using an appropriately defined in-situ density averaged to the interfaces at velocity points.  This form follows the suggestions of Appendix A.3.2 of Griffies and Greatbatch (Ocean Modelling, 2012) when in non-Boussinesq mode.  Thickness_diffuse_full was also revised to work properly in non-Boussinesq mode (and not depend on the Boussinesq reference density) when no equation of state is used.
As a part of these changes, the code now uses thickness-based streamfunctions and other thickness-based internal calculations in MOM_thickness_diffuse.  For example, the overturning streamfunctions with this …

*Non-Boussinesq revision of MOM_thickness_diffuse

---

config_src/external/drifters/MOM_particles.F90
src/core/MOM.F90

This commit brings the drifters interface up-to-date with the current version of the drifters package, which requires h (layer thickness) to calculate the vertical movement of particles. The interfaces in the code and in config_src/external are updated to pass this information to the drifters package.

+add h to drifters interface

---

src/core/MOM.F90
src/core/MOM_isopycnal_slopes.F90
src/core/MOM_stoch_eos.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

Pass dt_kappa_smooth to calc_isoneutral_slopes and vert_fill_TS in units of [H Z ~> m2 or kg m-1] instead of [Z2 ~> m2] for consistency with the units of other diffusivities in the code and to reduce the depenency on the  Boussinesq reference density in non-Boussinesq configurations.  In addition to the changes to the units of these two arguments, there is a new unit_scale_type argument to vert_fill_TS and MOM_calc_varT and a new verticalGrid_type argument to MOM_stoch_eos_init.  The units of 4 vertical diffusivities in the control structures in 4 different modules are also changed accordingly.
All answers are bitwise identical in Boussinesq mode, but they can change for some non-Boussinesq configurations.  There are new mandatory arguments to three publicly visible routines.

+*Revise units of arguments to vert_fill_TS

---

src/core/MOM_forcing_type.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90

Added the new public interface find_ustar to extract the friction velocity from either a forcing type argument, or a mech_forcing_type argument, either directly or from tau_mag, and in non-Boussinesq mode by using the time-evolving surface specific volume.  Find_ustar is an overloaded interface to find_ustar_fluxes or find_ustar_mech_forcing, which are the same but for the type of one of their arguments.  For now, the subroutines bulkmixedlayer, mixedlayer_restrajt_OM4, mixedlayer_restrat_Bodner and mixedlayer_restrat_BML are calling find_ustar to avoid code duplication during the transition to work in fully non-Boussinesq mode, but it will eventually be used in about another half dozen other places.
All Boussinesq answers are bitwise identical, but non-Boussinesq answers will change and …

+*Add and use find_ustar

---

src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_wave_speed.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90

Changed the units of the optional mono_N2_depth argument to wave_speed, wave_speed_init and wave_speed_set_param in thickness units instead of height units.  Accordingly, the units of one element each in the diagnostics_CS and wave_speed_CS and a local variable in VarMix_init are also changed to thickness units.  The unit descriptions of some comments describing diagnostics were also amended to also describe the non-Boussinesq versions.  Because this is essentially just changing when the unit conversion occurs, all answers are bitwise identical, but there are changes to the units of an optional argument in 3 publicly visible routines.

+wave_speed arg mono_N2_depth in thickness units

---

src/core/MOM_barotropic.F90

Added the new runtime parameter BT_RHO_LINEARIZED to specify the density that is used to convert total water column thicknesses into mass in non-Boussinesq mode with linearized options in the barotropic solver or when estimating the stable barotropic timestep without access to the full baroclinic model state. The default is set to RHO_0 and answers do not change by default.  This new parameter is used in non-Boussinesq mode with some options in btcalc and find_face_areas, when LINEARIZED_BT_CORIOLIS = True or BT_NONLIN_STRESS = False, and in the unit conversion of the ice strength with dynamic pressure.
Also cancelled out factors of GV%Z_to_H in MOM_barotropic.F90 to simplify the code and reduce the dependence on the value of GV%Rho_0 in non-Boussinesq mode. This involved changing the …

*+Add BT_RHO_LINEARIZED to MOM_barotropic.F90

---

src/core/MOM.F90
src/tracer/DOME_tracer.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/dye_example.F90
src/tracer/ideal_age_example.F90
src/tracer/nw2_tracers.F90

Use thickness_to_dz to convert layer thicknesses to depths in 4 tracer modules (DOME_tracer, dye_example, ideal_age_example and nw2_tracers) so that this conversion is done correctly in non-Boussineq mode, and there is no longer any dependency on the Boussinesq reference density in that mode.
This change includes the addition of a thermo_var_ptrs argument to 5 routines (initialize_DOME_tracer, initialize_dye_tracer, dye_tracer_column_physics, ideal_age_tracer_column_physics and count_BL_layers) and changes to the units of some internal variables, and the addition of 6 new 2-d or 3-d arrays with the vertical distance across layers.  An unused param_file_type argument to initialize_DOME_tracer was also eliminated.
Comments were also added to describe the units of 5 of the variables in the …

+*Use thickness_to_dz in tracer modules

---

src/parameterizations/vertical/MOM_diabatic_aux.F90

Changed a recently added OMP directive for plume_flux from private to firstprivate to reflect how this variable is actually used.  This bug was introduced with PR #401, but was causing sporadic failures in some of our pipeline tests with the intel compiler (essentially due to initialized memory when openMP is used) for subsequent commits.

Fix a bug in the OMP directive for plume_flux

---

config_src/drivers/FMS_cap/ocean_model_MOM.F90
config_src/drivers/mct_cap/mom_ocean_model_mct.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
config_src/drivers/solo_driver/MOM_driver.F90
src/core/MOM.F90
src/framework/MOM_get_input.F90
src/framework/posix.F90
src/framework/posix.h
src/user/MOM_wave_interface.F90

This PR refactors the implementation of `save_MOM6_internal_state` by also including the MOM6 `save_restart` function, and renaming it to `save_MOM_restart`, which now acts as a generic placeholder for all MOM restart operations.
The `restart_CS` is now wholly contained within the top-level MOM control structure (usually `MOM_CS`) and all restart operations must be routed through `MOM_CS`.
This PR also includes a commit which creates the restart directory (usually `RESTART`) if it is missing.

Refactor of `save_MOM6_internal_state`

---

src/parameterizations/lateral/MOM_hor_visc.F90

Cancelled out factors of GV%Z_to_H in MOM_hor_visc.F90 to simplify the code and reduce the dependence on the value of GV%Rho_0 in non-Boussinesq mode.  This involved changing the units of 3 internal variables in horizontal_viscosity and one element in the hor_visc_CS type to use thickness units or their inverse. Because GV%Z_to_H is an exact power of 2 in Boussinesq mode, all answers are bitwise identical in that mode, but in non-Boussinesq mode this conversion involves multiplication and division by GV%Rho_0, so while all answers are mathematically equivalent, this change does change answers at roundoff in non-Boussinesq mode.

*Cancel out Z_to_H factors in MOM_hor_visc.F90

---

src/core/MOM_variables.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_CVMix_conv.F90
src/parameterizations/vertical/MOM_CVMix_ddiff.F90
src/parameterizations/vertical/MOM_CVMix_shear.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/user/user_change_diffusivity.F90

This PR includes a series of 3 commits that revise the units of viscosity in the transparent vert_visc_type to those of a dynamic viscosity in non-Boussinesq more or a kinematic viscosity in Boussinsq mode, with analogous changes to other elements of the transparent vert_visc_type, and of a number of other diapycnal diffusivities and turbulent kinetic energies that are passed between routines or used internally within the routines that set these diffusivities.  Dozens of unit conversion factors were also cancelled out with these changes, including using that GV%Z_to_H/GV%Rho_0 = GV%RZ_to_H and GV%Rho_0*GV%H_to_Z = GV%H_to_RZ for both Boussinesq or non-Boussinesq configurations.
Because GV%Z_to_H is an exact power of 2 in Boussinesq mode, all answers are bitwise identical in that mode, but …

+*Thickness-based viscosity and diffusivity units

---

src/initialization/MOM_state_initialization.F90
src/user/Rossby_front_2d_initialization.F90

Revised the Rossby_front initialization routines to work directly in thickness units and added completely separate algorithms to initialize the Rossby_front thicknesses and velocities consistently when the Boussinesq approximation is not being made.
To accommodate this change, error handling was added to detect when the THICKNESS_CONFIG and TS_CONFIG settings are incompatible.  As a part of this commit the units of the h arguments to Rossby_front_initialize_thickness and Rossby_front_initialize_temperature_salinity are changed. MAXIMUM_DEPTH is now read in and rescaled via get_param in the Rossby_front routines rather than simply being pulled from the ocean grid type.
There are are also changes to the units of 13 internal variables and 14 new internal variables in the Rossby_front …

+*Non-Boussinesq Rossby_front initialization

---

src/core/MOM_interface_heights.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90

This PR consists of a set of commits that calculates the actual density averaged over a near-bottom region when in non-Boussinesq mode via the new subroutine find_rho_bottom, and then uses this calculate the bottom drag experienced by the internal tides.  As a part of this, there are new arguments to propagate_int_tide, itidal_lowmode_loss and find_N2_bottom, and changes to the units of a handful of internal variables, as well as a new array in the transparent int_tide_input_type.
All answers are bitwise identical in Boussinesq mode, but some solutions will change in non-Boussinesq mode with this change, and there are new arguments to publicly visible subroutines and a new element in a transparent type.
- NOAA-GFDL/MOM6@c0e9b26b6 +*Non-Boussinesq internal …

+*Use actual density for internal tide bottom drag

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/core/MOM.F90
src/core/MOM_barotropic.F90
src/core/MOM_porous_barriers.F90
src/diagnostics/MOM_diagnostics.F90
src/framework/MOM_diag_mediator.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_regularize_layers.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/MOM_neutral_diffusion.F90
src/user/MOM_wave_interface.F90

Set a minimum answer date of 20230701 when the model is known to be in non-Boussinesq mode, and ignore all ANSWERS_2018 flags in that same mode.  This change only applies to the code called from the src directories, and not to code within or called directly from the config_src/drivers directories or from another component model like SIS2 where the information about whether the model is in non-Boussinesq mode is not available.  A verticalGrid_type arguemnt was added to porous_barriers_init to support one of these changes.  This commit will change answers in some non-Boussinesq configurations, but all answers in existing test cases appear to be bitwise identical.  There are fewer entries logged in non-Boussinesq MOM_parameter_doc files.

+(*)Minimum non-Boussinesq answer date of 20230701

---

src/framework/MOM_file_parser.F90

`MOM_file_parser`'s `open_param_file()` contains explicit `inquire()` calls when assessing the correctness of opening such a file.  As written, these could be called by any rank, and are not thread safe.  In rare cases (usually related to testing), this would cause a race condition and raise an error.
Even ignoring the errors, it is probably better if only one rank makes these calls, rather than all of them.
The following patch modifies the function so that only root PE invokes `inquire()`.
There is not much to celebrate about this patch; it does not try to clean up the intrinsic weirdness of the IO handling.  But it does appear to fix some of the most apparent problems.

Move file parser inquire calls to root PE

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/user/MOM_wave_interface.F90

The surface gravity waves invariably work with depths in meters to match the units of the horizontal wavenumbers, even in non-Boussinesq mode, so several of the variables that are passed to or used in the MOM_wave_interface module have been revised to use units of [Z ~> m] and not [H ~> m or kg m-2].  There are changes to the names or units of a total of 8 arguments to Stokes_PGF, Update_Stokes_Drift, Get_StokesSL_LiFoxKemper, Get_SL_Average_Prof and get_Langmuir_Number, and a new argument to StokesMixing.  To accommodate these changes, there are now calls to thickness_to_dz that precede the Update_Stokes_Drift or Stokes_PGF calls and a new 3d array in step_MOM.
Additionally, four hard-coded dimensional constants in Stokes_PGF were given the needed scaling factors to pass dimensional …

+Non-Boussinesq revisions to wave_interface

---

src/ice_shelf/MOM_ice_shelf.F90

**Two fixes to the ice shelf melt parameterization in `MOM_ice_shelf.F90`:**
(1) the removal of an extra von Kármán constant which differs from the Holland and Jenkins (1999) formulation. My working is detailed in [this](https://github.com/claireyung/sharing/blob/main/PR%20(3).pdf) document.
(2) a modification to the it3 loop in `shelf_calc_flux` subroutine, which currently does not iterate because `wB_flux` does not get updated to its new value via the Newton solver method. Instead, the loop either runs 30 times with the same value, or is below the threshold and exits on the first loop. I added a line to update the value of `wB_flux`.

Ice shelf melt parameterization fixes

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_hybgen_unmix.F90
src/ALE/MOM_regridding.F90

Use SpV_avg in both hybgen_unmix and regridding_main to estimate the nominal ocean bottom depth in thickness units when in fully non-Boussinesq mode.  This change eliminates certain dependencies on the Boussinesq reference density via GV%Z_to_H.  Also added a call to calc_derived_thermo in ALE_regrid_accelerated that is necessary for the specific volume to be updated, along with tests for the validity of the specific volume with the 1-point halos that are currently used with ALE regridding and remapping.
Also, use the total thickness place of the nominal depth in build_grid_rho and build_grid_sigma when in fully non-Boussinesq mode.  This is mathematically equivalent but changes answers at roundoff.
All answers are bitwise identical in Boussinesq mode, but ALE-based solutions change in …

*Use tv%SpV_avg in non-Boussinesq regridding

---

src/parameterizations/vertical/MOM_diabatic_driver.F90

This commit completes the non-Boussinesq revision of the diabatic_driver code. The revised code uses thickness_to_dz and works with internal variables in vertical distances in the denominator of diffusive flux calculations in diabatic_ALE_legacy, diabatic_ALE and layered_diabatic.  The code now uses find_ustar to extract the friction velocities passed to KPP_compute.  The (tiny) boundary layer tracer diffusivity is also rescaled to [H2 T-1].  With this set of changes, all implicit references to Boussinesq reference density are eliminated from the calculations in diabatic_driver when in non-Boussinesq mode.
A total of 14 thickness rescaling factors were cancelled out, and there are 15 new or renamed variables in the diabatic routines.  4 new checksum calls are also added to …

*Non-Boussinesq revision of diabatic_driver

---

src/core/MOM.F90
src/core/MOM_interface_heights.F90

Ignore SURFACE_ANSWER_DATE in non-Boussinesq mode and always allocate tv%SpV_avg in fully non-Boussinesq mode, setting it to the inverse of the layer densities in calc_derived_thermo() if there is no equation of state.  Also when in fully non-Boussinesq mode cancelled out some rescaling factors in dz_to_thickness_EOS and dz_to_thickness_tv.  Also revised dz_to_thickness_simple in non-Boussinesq and non-layered mode to use RHO_KV_CONVERT instead of RHO_0 to rescale vertical distances to thicknesses.  Also set the default value of CALC_RHO_FOR_SEA_LEVEL to true when fully non-Boussinesq.  All Boussinesq answers are bitwise identical, but some non-Boussinesq answers do change and become less dependent on the Boussinesq reference density.  Because SURFACE_ANSWER_DATE is no longer being used …

+*Ignore SURFACE_ANSWER_DATE when non-Boussinesq

---

src/parameterizations/vertical/MOM_full_convection.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

This commit revises full_convection to avoid any dependency on the Boussinesq reference density when in non-Boussinesq mode.  Specifically, it changes the units of the Kddt_smooth argument to full_convection and its counterpart in smoothed_dRdT_dRdS to use units of [H Z ~> m2 or kg s-1], which becomes a mass based diffusivity when in non-Boussinesq mode.  This change also uses vertical distances for internal calculations in smoothed_dRdT_dRdS, and includes a call to thickness_to_dz in the full_convection routine.
This commit also revises the unit conversion of the (absurdly large) mixing length in unstable points in full_convection and of the (tiny) added smoothing distance used in the denominators of some expressions in smoothed_dRdT_dRdS to avoid division by zero with massless layers so …

+*Non-Boussinesq revision of full_convection

---

src/diagnostics/MOM_PointAccel.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Revised the code in MOM_vertvisc.F90 to work internally with thickness-based units for the viscous coupling between layers, which eliminates any dependence on the value of GV%Rho_0 in non-Boussinesq mode.  Various kinematic viscosities are replaced with dynamic viscosities in non-Boussinesq configurations, including revising the scaled units of the viscosities to [H Z T-1 ~> m2 s-1 or Pa s].  This commit also modifies the code to explicitly use vertical distances rather than thicknesses when calculating the vertical viscous coupling coefficients in vertvisc_coef and find_coupling_coef.
This commit involves changing the units of numerous variables to use thickness, vertical distance, dynamic viscosity or other related units, including:
- 14 elements in the vertvisc_CS type
- 6 arguments to …

+*Non-Boussinesq revision of MOM_vertvisc.F90

---

src/core/MOM_forcing_type.F90

Added the new tau_mag_gustless element to the forcing type, and set this array in set_derived_forcing_fields if it is associated.  Also added new tau_mag optional arguments to the public routines allocate_forcing_by_group() and allocate_mech_forcing_by_group(), with similar mandatory arguments added to the private subroutines get_forcing_groups() and get_mech_forcing_groups().  Tests for an associated pointer were added before all calls setting the ustar, tau_mag or ustar_gustless arrays, preparing for these ustar pointers only to be set when the model is run in Boussinesq mode when the ustar actually make sense.
Also use specific volume derivatives to calculate non-Boussinesq mode buoyancy fluxes in calculateBuoyancy_Flux1d, leaving the Boussinesq buoyancy flux calculations unchanged. …

*+Add forcing%tau_mag_gustless & tau_mag opt args

---

src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

This commit has a set of changes that set the tidal mixing in non-Boussinesq mode without reference to the Boussinesq reference density, by converting thicknesses to depths via a call to thickness_to_dz, by calculating an average near-bottom density explicitly via a call to find_rho_bottom, and by working with an appropriate mix of layer vertical extents and thicknesses.
The contents of find_N2, calculate_tidal_mixing, calculate_CVMix_tidal and add_int_tide_diffusivity are all revised to work directly with vertical distances, set via thickness_to_dz, rather than rescaled thicknesses.  This includes replacing the 3-d layer thickness argument to calculate_tidal_mixing, calculate_CVMix_tidal and add_int_tide_diffusivity with a 2-d slice of vertical distances across layers.  For find_N2, the …

+*Non-Boussinesq revision of tidal_mixing and find_N2

---

src/core/MOM_forcing_type.F90

Added the name to the do_taumag argument in a call to allocate_forcing_type in allocate_forcing_by_ref to account for the fact that there are unused wave-related optional arguments in this interface.  When this was omitted in the current code, the wrong arrays are being allocated during rotation tests with resultant segmentation faults in those tests.  This commit corrects a bug that was recently added with MOM6 dev/gfdl PR #445.

*Fix allocate_forcing_by_ref tau_mag_gustless bug

---

src/parameterizations/vertical/MOM_regularize_layers.F90

Add missing dimensional rescaling factors for hard-coded temperature and salinity offsets in debugging conservation checks in regularize_surface.  All answers are bitwise identical, but without this change some configurations can erroneously give fatal errors for some rescaling settings when DEBUG=True.

Fix rescaling in regularize_surface debugging

---

src/parameterizations/vertical/MOM_CVMix_conv.F90
src/parameterizations/vertical/MOM_CVMix_ddiff.F90
src/parameterizations/vertical/MOM_CVMix_shear.F90

This commit revises MOM_CVMix_conv, MOM_CVMix_ddiff and MOM_CVMix_shear to work in an appropriate mixture of thickness and vertical extent variables to enable their use in non-Boussinesq mode, using thickness_to_dz to convert between the two, while retaining the previous answers in Boussinesq mode.  This includes the use of a layer thicknesses rather than a vertical distance in the denominator of the calculation of the buoyancy frequency and to the units of the internal rescaled gravity variable in CVMix_conv.  This commit eliminates any direct or indirect dependency on the Boussinesq reference density in these 3 modules when in non-Boussinesq mode.
This set of changes includes changing the units of 7 internal variables and the addition, renaming, or change in the dimensions of 4 internal …

*Non-Boussinesq revision of 3 MOM_CVMix modules

---

src/parameterizations/vertical/MOM_CVMix_KPP.F90

This commit revises MOM_CVMix_KPP to work in an appropriate mixture of thickness and vertical extent variables to enable their use in non-Boussinesq mode, using thickness_to_dz to convert between the two, while retaining the previous answers in Boussinesq mode.  This includes the use of a layer thicknesses rather than a vertical distance in the denominator of the calculation of the buoyancy frequency and the replacement of the layer thickness argument (h) to KPP_smooth_BLD with a layer vertical extent (dz).  When in non-Boussinesq mode, the buoyancy difference between layers is normalized by the average of the density of the two layers rather than the Boussinesq reference density. This commit eliminates any direct or indirect dependency on the Boussinesq reference density in CVMix_KPP …

*Non-Boussinesq revision of MOM_CVMix_KPP

---

src/parameterizations/lateral/MOM_interface_filter.F90

Refactored interface_filter when in non-Boussinesq mode to avoid any dependencies on the Boussinesq reference density, and to translate the volume streamfunction into the mass streamfunction using an appropriately defined in-situ density averaged to the interfaces at velocity points.  This form is similar to the one that is used in thickness_diffuse.
No public interfaces are changed, and all answers are bitwise identical in Boussinesq or semiBoussinesq mode, but they will change in non-Boussinesq mode cases that use the interface filter.

*Non-Boussinesq interface_filter

---

src/core/MOM_isopycnal_slopes.F90

Revise calc_isoneutral_slopes to eliminate any dependence on the Boussinesq reference density when in non-Boussinesq mode.  This includes the addition of two new arrays to hold the rescaled product of the gravitational acceleration and the specific volume interpolated to the interfaces at velocity points. The answers change in non-Boussinesq mode when one of several parameterizations that use the isoneutral slopes are in use, but are bitwise identical in Boussinesq or semi-Boussinesq mode.

*Non-Boussinesq revision of calc_isoneutral_slopes

---

src/tracer/MOM_CFC_cap.F90

Rescaled CFC flux diagnostics in the CFC cap via a conversion factor in their register diag_field calls, rather than by doing array syntax math in their post_data calls.  All answers are bitwise identical.

Refactor rescaling of CFC_cap flux diagnostics

---

src/parameterizations/vertical/MOM_set_diffusivity.F90

This commit revises the internal routines called by set_diffusivity to work in fully non-Boussinesq mode, eliminating all dependencies on the Boussinesq reference density when in non-Boussinesq mode.  The publicly visible interfaces to this module and the external routines it calls have already been revised, so only this file needs to be updated.  The specific changes include:
- Refactored add_LOTW_BBL_diffusivity, add_MLrad_diffusivity, and set_BBL_TKE to work in units of layer vertical extent rather than layer thickness to give results in non-Boussinesq mode that avoid dependence on the Boussinesq reference density.
- Work with internal variables in vertical distances in the denominator of diffusive flux calculations in find_TKE_to_Kd, while other expressions in this routine are recast …

*Non-Boussinesq revision of set_diffusivity

---

src/parameterizations/vertical/MOM_entrain_diffusive.F90

This commit refactors entrainment_diffusive to avoid any dependencies on the Boussinesq reference density when in non-Boussinesq mode, including using calculate_specific_vol_derivs for one diagnostic when non-Boussinesq.
This commit includes making the formerly optional arguments kb_out, Kd_Lay and Kd_int to entrainment_diffusive non-optional, as they have been used in all calls to this routine for many years.
Layer target density differences are now used in place of g_prime in entrainment_diffusive in mathematically equivalent expressions for the density difference ratios when non-Boussinesq.
The non-Boussinesq upper layer buoyancy flux with entrainment_diffusive was revised to avoid using the Boussinesq reference density when the model is in layered mode but there is no equation of …

*Non-Boussinesq refactoring of entrain_diffusive

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/drivers/solo_driver/MESO_surface_forcing.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
config_src/drivers/solo_driver/user_surface_forcing.F90
src/ice_shelf/MOM_ice_shelf.F90
src/user/Idealized_Hurricane.F90
src/user/SCM_CVMix_tests.F90
src/user/dumbbell_surface_forcing.F90

This PR includes a series of commits that set the new runtime parameters RESTORE_FLUX_RHO and TKE_TIDAL_RHO when in non-Boussinesq mode to reduce the dependency on the Boussinesq reference density, and also ensure that tau_mag is being allocated and set properly with some cases where it had been omitted previously.  The specific changes include:
- Added the new runtime parameters RESTORE_FLUX_RHO and TKE_TIDAL_RHO to specify the densities that are used to convert the piston velocities into restoring heat or salt fluxes and to translate tidal velocities into tidal TKE input.  Their defaults are set to RHO_0 to reproduce previous answers.  There are new rho_restore elements in the FMS and solo_driver versions of surface_forcing_CS and in MESO_surface_forcing_CS, user_surface_forcing_CS, …

+Add RESTORE_FLUX_RHO and set tau_mag

---

src/user/benchmark_initialization.F90

The units of S_REF were first registered in "PSU" and then later by benchmark in "ppt" which led to a WARNING. Although there is no uniformity to the units of S_REF throughout the user code (currently PSU, ppt, and 1e-3, are all used), benchmark is the only one that leads to a warning in the current suite and changing all to be consistent would 1) unnecessarily update the doc files, and 2) not be correct for all models. Bottom line, I'm punting on the best way to handle units of salinity. This commit resolves the only WARNING we currently get in the MOM6-examples suite.

Resolve warning about S_REF units

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

- Update for missing halo update of field wpup_filtered in MOM_mixed_layer_restrat.F90 during initialization.
- The missing halo update caused the model to diverge when running from restart files.
- With the halo update the model now reproduces from restart files.

Bugfix in MLE for reproducible restarts with USE_BODNER23 = True

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

Revised the code in MOM_mixed_layer_restrat.F90 to work internally with thickness-based units for the restratification timescale calculation and other internal calculations, which eliminates the dependence in this module on the value of the Boussinesq reference density in non-Boussinesq mode.  Several other minor issues (which might not change any answers in production runs) were also fixed.  The changes with this commit include:
- When in non-Boussinesq mode, the mixed layer buoyancy gradients are determined from the average specific volume referenced to the surface pressure, rather than from the average potential density.
- Use find_ustar to set the friction velocities in the appropriate units in the various mixed_layer_restrat routines.
- A logical branch was added based on the correct …

*+Non-Boussinesq form of mixedlayer_restrat

---

src/parameterizations/vertical/MOM_kappa_shear.F90

Remove dependency on the Boussinesq reference density in MOM_kappa_shear when in fully non-Boussinesq mode.  This is done by using calls to calculate_density and calculate_specific_vol_derivs to calculate the thermal expansion and haline contraction coefficients, and by using thickness_to_dz to convert layer thicknesses to vertical distances.
A large part of the changes to the kappa_shear code involved refactoring it to differentiate between thicknesses and geometric heights by working internally with dynamic viscosities and diffusivities in non-Boussinesq mode, and to keep thicknesses in thickness units rather than converting them to distances in height units.  The internal variable dz was renamed to h_lay in Calculate_kappa_shear and Calc_kappa_shear_vertex for greater clarity.
The …

*Non-Boussinesq revision of kappa_shear

---

src/parameterizations/vertical/MOM_sponge.F90

Use tv%SpV convert thicknesses to vertical distances in apply_sponge when it is allocated to replace multiplication by GV%H_to_Z, thereby eliminating the dependence on GV%RHo_0 in this modue in non-Boussinesq mode.  The new internal array dz_to_h is used to reduce the code duplication as a result of these changes.  All answers in Boussinesq test cases are bitwise identical, but answers change in fully non-Boussinesq mode.  In semi-Boussinesq mode answers are mathematically equivalent but change at roundoff unless RHO_0 is an integer power of 2.

+*Non-Boussinesq revision of MOM_sponge code

---

src/user/DOME_initialization.F90

Set DOME inflow properties using the average density rather than RHO_0 when in non-Boussinesq mode.  The existing Boussinesq solutions are unchanged, but this changes the non-Boussinesq DOME solutions, which no longer depend on the Boussinesq reference density.

*Non-Boussinesq expressions for DOME inflow rates

---

src/core/MOM_PressureForce.F90
src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_barotropic.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/diagnostics/MOM_obsolete_params.F90
src/parameterizations/lateral/MOM_load_love_numbers.F90
src/parameterizations/lateral/MOM_self_attr_load.F90
src/parameterizations/lateral/MOM_spherical_harmonics.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90

Calculation for self-attraction and loading (SAL) is taken out from `MOM_tidal_forcing` and housed in a new module (`MOM_self_attr_load`) as SAL is a process not limited to tides.
The new module includes both online spherical harmonics method and scalar approximation. Read-in method (TIDAL_SAL_FROM_FILE) is kept in the tidal forcing module as it is specific to tides. For the iterative method (USE_PREV_TIDES), the updating part that is tied to the scalar approximation is moved to the new SAL model, while the read-in part remains in the tidal_forcing module.
Module `MOM_tidal_forcing` is designated only to calculations of the astronomical forcing and periodic tidal SAL that is based on previous solutions from input files. This makes the tidal forcing module now only contain calculations …

Separate self-attraction and loading as a new module

---

src/core/MOM.F90

This commit revises the internal code in step_MOM and extract_surface_state to work in fully non-Boussinesq mode without any dependencies on the Boussinesq reference density and provide updates needed to reproduce answers across restarts in non-Boussinesq mode.  The subroutine calls from this module have already been revised, so only this file needs to be updated.  The specific changes include:
- Rescaled the nominal mixed layer depth variables HFREEZE, HMIX_SFC_PROP and HMIX_UV_SFC_PROP for determining surface properties to eliminate unit conversion factors during the run.  This changes the units of 3 elements of the MOM_control_struct and one internal variable and adds 3 new internal variables.
- Call calc_derived_thermo to update SpV_avg at the start of step_MOM if the internal ocean …

*Non-Boussinesq revision of MOM.F90 for restarts

---

src/user/BFB_initialization.F90
src/user/BFB_surface_forcing.F90

Revised BFB_set_coord and BFB_buoyancy_forcing to be consistent with other instances of a linear equation of state, and to set g_prime in non-Boussinesq mode similarly to how it is set in other places.   Also use RESTORE_FLUX_RHO in place of RHO_0 when to specify the densities that are used to convert the piston velocities into restoring heat or salt fluxes with BFB_buoyancy_forcing, like in other places in the MOM6 code.  This change will change answers by default when BFB_set_coord is used, but the old Boussinesq answers can be recovered by setting the reference salinity S_REF to 38.75 ppt or by setting RHO_T0_S0 to 1003.0 kg m-3.

*Revise BFB_set_coord and BFB_buoyancy_forcing

---

src/core/MOM_PressureForce_Montgomery.F90
src/core/MOM_porous_barriers.F90
src/diagnostics/MOM_diagnostics.F90

Use the minimal vertical distance GV%dZ_subroundoff in 8 spots in 2 files in place of GV%H_to_Z*GV%H_subroundoff.  Four internal variables were renamed for clarity of purpose in porous_widths_layer and PressureForce_Mont_Bouss.  Also modified the non-Boussinesq units in a description of two integrated energy diagnostics from [H L4 T-3 ~> kg m2 s-3] to [H L4 T-3 ~> W]; these units are equivalent but the latter is more informative.  Answers in all Boussinesq test cases and the existing non-Boussinesq test case in the MOM6-examples test suite are bitwise identical.

Use GV%dZ_subroundoff

---

src/ALE/MOM_ALE.F90
src/core/MOM.F90
src/tracer/MOM_offline_aux.F90
src/tracer/MOM_offline_main.F90

Rescale the units diapycnal diffusivity used in the offline tracer mode to work in [H Z T-1 ~> m2 s-1 or kg m-1 s-1], making it consistent with what has already been done for other diapycnal diffusivities.  This change involves changes to the units of arguments to update_offline_from_files and ALE_offline_inputs and to two elements of offline_transport_CS.   It also includes a new thermo_vary_type argument to offline_diabatic_ale, as well as a call to thickness_to_dz in that same routine to set the values of the newly added 3-d array of the vertical distances across layers and a change in name and units of the inverse thickness variable used to find the fluxes.  All answers are bitwise identical in Boussinesq mode, but in offline tracer calculations in non-Boussinesq mode they will change …

+*Revise non-Boussinesq offline tracer diffusivity

---

ac/deps/m4/ax_fc_check_c_lib.m4
ac/deps/m4/ax_fc_check_lib.m4

This patch updates the macros used in the `ac/deps` directory.  It includes a bugfix in the library testing, and also bundles the macro for testing Fortran links to C libraries.  Both of these macros were already in `ac/m4` but unused by `ac/deps`.
No problems were observed in any recent FMS builds, although in principle they could have been affected by these errors.  The issues were only detected when the macros were used in an unrelated project (LM3 land model).
These issues are due to code duplication in `ac/m4` and `ac/deps/m4`. This separation was intended to draw a clear logical separation between MOM6 and its FMS dependency, and only provide what is required by each respective build.  But perhaps there are some flaws in this thinking, and may warrant further discussion.

Autoconf: Update deps m4 macros

---

config_src/drivers/ice_solo_driver/atmos_ocean_fluxes.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

This pull request fixes a combination of ice-shelf bugs related to halo update errors, improperly-defined iteration bounds, and an unexpected change in ice-shelf bed_elev after a restart. These issues caused crashes during the ice-shelf velocity (SSA) solution, and ice shelf dynamics restarts were not bitwise identical. The issues were resolved with the following changes:
-Added bed_elev to the ice shelf restart file (previously, bed_elev was instead calculated incorrectly after a restart). Also fixed the subsequent bed_elev pass_var call, where the halo update was failing due to an error in how an optional argument (CENTER) was passed.
-Added additional pass_var/pass_vector calls upon ice shelf restarts to guarantee that all halos are properly filled.
-Disabled the additional ice shelf …

Ice-shelf bugfixes for restarts and halo updates

---

config_src/infra/FMS1/MOM_io_infra.F90
src/core/MOM.F90
src/framework/MOM_io.F90
src/framework/MOM_restart.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

* add a call to register restart diabatic in MOM
* register restart diabatic call register restart internal tides
* internal tides restart uses the extra_axes optional argument
* support for extra_axes added to MOM_restart/MOM_io
* support for 4d array read with FMS1
* works with FMS2
* writes 4d restarts for horizontal, propagation angle and tidal frequency
* writes 5 restart variables for all the propagating vertical modes

implement restart for internal tides

---

src/parameterizations/lateral/MOM_MEKE.F90

This commit revises MOM_MEKE to work in with total depths in thickness units to avoid any dependence on the Boussinesq reference density in non-Boussinesq mode, while retaining the previous answers in Boussinesq mode.  It also adds the new runtime parameter MEKE_TOTAL_DEPTH_RHO to specify the density that is used to convert the bathymetric depth into a nominal ocean mass in non-Boussinesq mode when MEKE is enabled and MEKE_FIXED_TOTAL_DEPTH is true.
There is a new element in the MEKE_CS type, and the scaled units of two other elements (cdrag and MEKE_min_depth_tot) are altered.  The units of a total of 5 arguments to the private routines MEKE_equilibrium, MEKE_equilibrium_restoring, MEKE_lengthScales and MEKE_lengthScales_0d where changed consistently with the broader changes here.  There …

*+Non-Boussinesq MEKE and add MEKE_TOTAL_DEPTH_RHO

---

.gitlab-ci.yml
.testing/Makefile
.testing/tools/report_test_results.sh

The test.summary rule was causing errors in our Gitlab testing due to multiple runs (concurrent or otherwise) in the same workspace directory. This patch removes the WORKSPACE directory variable, and each .testing run happens in its own directory.
Other minor changes:
- The script to generate the summary was moved out of the Makefile and into a separate script.
- Unrelated to these changes, error output was extended from 20 to 40 lines, to provide more readable backtrace output.

CI: Run test (and test.summary) locally

---

ac/makedep

The current version of makedep uses the existence of program units (module or program) to determine whether a file contains globally accessible external functions.  It incorrectly ignores files with externals it happens to contain both externals and a program unit.
We resolve this by tracking whether we are inside or outside of a program unit while parsing each line.  We ignore keywords which may appear in comments, as well as tokens which may contain `function` or `subroutine` as substrings.  This method is not perfect; there are cases which will incorrectly report entering a block, but this method appears sufficient for all of our known codebases.
This issue was detected when attempting to parse the AM2 source.  While still far from a general solution, it is sufficient to handle a few …

makedep: Support externals alongside program units

---

src/core/MOM_interface_heights.F90

Add tests to stop iterating when converged to roundoff in dz_to_thickness_EOS() when in fully non-Boussinesq mode.  Also modified the code to keep track of the layer thickness directly in non-Boussinesq mode rather than setting the layer thickness based on a difference between interface pressures.  Boussinesq answers are bitwise identical, but non-Boussinesq answers change.

*Test for convergence in dz_to_thickness_EOS

---

src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_opacity.F90

This pull request includes two commits with a series of distinct changes that enable the use of the bulk mixed layer code in non-Boussinesq mode, including an option to do the non-Boussinesq energetic calculations even when the model itself is in Boussinesq or semi-Boussinesq mode.  When in fully non-Boussinesq mode, there is no longer any dependence on the Boussinesq reference density.
The first commit adds the optional argument SpV_avg to extract_optics_slice for use along with an appropriate value for opacity_scale to convert the units of opacity from [Z-1] to [H-1] in non-Boussinesq mode without making use of the Boussinesq reference density.
Among other things, the second commit rescales the units of turbulent kinetic energy in the bulk mixed layer code to [H L2 T-2 ~> m3 s-2 or J …

+*Non-Boussinesq bulk mixed layer calculations

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90

Modified MOM_surface_forcing_gfdl.F90 and  MOM_surface_forcing.F90 to allocate either ustar or tau_mag, but not both, in the forcing and mech_forcing types, depending on whether the model is in Boussinesq mode.  Also added tests to convert_IOB_to_forces in the FMS_cap code and to routines in MOM_surface_forcing in the solo_driver code to ensure that only arrays that are associated are set. All answers are bitwise identical, but checksum statements for the unused arrays are eliminated when DEBUG = True.

Do not allocate ustar and tau_mag together

---

src/diagnostics/MOM_wave_speed.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

Modified the internal wave speed calculation to work in non-Boussinesq mode without any dependencies on the Boussinesq reference density (RHO_0).  Many factors of GV%H_to_Z or its inverse are cancelled out in MOM_wave_speed.F90 by working directly in thickness units.  The code now uses specific volume derivatives to set the values of g_prime at interfaces when in non-Boussinesq mode, regardless of whether an equation of state is used.
This commit also modifies the wave structure calculations in wave_speeds, which includes the use of thickness_to_dz, changes to the units of three arguments to wave_speeds and their counterparts in int_tide_CS, and a number of duplicated calculations of vertical extents mirroring the calculations of thicknesses.  Some diagnostic conversion factors were …

+*Non-Boussinesq wave_speed calculations

---

ac/makedep

Nested includes are tracked for the purpose of include flags (-I), but not with respect to the content within those files.  This patch tracks the module usage statements (`use ...`) inside of any include files and adds them to the Makefile rules of the top-level file.
This was implemented within the `nested_inc` function by adding a new argument.

makedep: Module dependency in nested includes

---

src/initialization/MOM_state_initialization.F90

Changed the default value of Z_INIT_REMAP_GENERAL to true for fully non-Boussinesq configurations.  All existing fully non-Boussinesq cases that use INIT_LAYERS_FROM_Z_FILE = True use this setting, and it is likely that such cases will not work at all if this is false.  This change reduces the parameters that need to be changed to go between equivalent Boussinesq and non-Boussinesq configurations to just BOUSSINESQ and SEMI_BOUSSINESQ.  The previous default (false) is being retained for any Boussinesq or semi-Bousssinesq cases so that all answers and output are bitwise identical in those cases, but by default some non-Boussinesq solutions change answers, and there are changes to the MOM_parameter_doc files for those non-Boussinesq cases.

+(*)Non-Boussinesq default of true for Z_INIT_REMAP_GENERAL

---

src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90

This commit revises lateral_mixing_coeffs to work in an appropriate mixture of thickness and vertical extent variables to avoid any dependence on the Boussinesq reference density in non-Boussinesq mode, while retaining the previous answers in Boussinesq mode.
This commit adds the new runtime parameter FULL_DEPTH_EADY_GROWTH_RATE to indicate that the denominator of an Eady growth rate calculation should be based on the full depth of the water column, rather than the nominal depth of the bathymetry.  The new option is only the default for fully non-Boussinesq cases.
A primordial horizontal indexing bug was corrected in the v-direction slope calculation.  Because it only applies for very shallow bathymetry, does not appear to impact any existing test cases and went undetected for at least 12 …

+*Non-Boussinesq revision of lateral_mixing_coeffs

---

.github/workflows/coverage.yml
.testing/Makefile

Anonymous uploads to Codecov are throttled (though it is not clear if this is happening on the Codecov or the GitHub Actions side). Regardless, the advice to get around this throttling seems to be to use the Codecov token associated with the project.
The .testing Makefile was modified to use this token if provided, and the GitHub Actions environment now attempts to fetch this from the secrets of the repository.
Hopefully individual groups can set this for their own projects, and it will fall back to anonymous upload if unset, but I guess we'll have to see how this plays out.

.testing: Codecov upload uses Github Actions token

---

src/core/MOM_barotropic.F90
src/core/MOM_boundary_update.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_interface_heights.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90
src/user/Kelvin_initialization.F90
src/user/tidal_bay_initialization.F90

This sequence of 5 commits extends the MOM6 open boundary condition capabilities to work in fully non-Boussinesq mode.  This includes the addition of the new subroutine find_col_avg_SpV, the addition or renaming of elements in the transparent OBC_segment_type to emphasize that they are always sea surface heights, and a change to the dimensional rescaling of variables in several user modules.  With this change, test cases that worked previously only in Boussinesq mode now also work in non-Boussinesq mode, while all Boussinesq solutions are bitwise identical.  The specific changes in this PR include:
- Renamed OBC related variables to emphasize that they are sea surface heights,
and not sea surface heights or total column mass depending on the Boussinesq
approximation.  Also changed the …

+Non-Boussinesq open boundary conditions

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

Previously, ice-shelf Dirichlet boundary conditions only allowed u-velocity and v-velocity to be set to the same value (which is enforced by setting the value of parameters u_face_mask or v_face_mask to 3). This functionality is retained here, but now setting u_face_mask or v_face_mask to 5 enforces a Dirichlet boundary for u-velocity only along the respective cell face. Similarly, setting u_face_mask or v_face_mask to 6 enforces the Dirichlet boundary for v-velocity only along the respective cell face. This functionality is required for most ice-sheet modeling configurations, e.g. the idealized MISMIP+ configuration requires setting v-velocity only to 0 along its lateral boundaries, but with free-slip conditions enforced for u-velocity. Adding this capability required changes throughout …

New treatment of ice shelf boundaries 

---

.github/workflows/coverage.yml
.testing/Makefile

The codecov token was added to the tc* test upload, but not the unit test upload.  This patch adds the token to the unit testing.

.testing: Codecov token for unit test upload

---

src/core/MOM_barotropic.F90

Corrected the non-Boussinesq calculation of the total depth used by the v-component of the Flather open boundary condition, making the v-component consistent with the u-component and correcting an oversight with a recent commit.  This commit could change answers in some non-Boussinesq cases with Flather open boundary conditions.

*Fix non-Boussinesq Flather BT_OBC%dZ_v bug

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90

Previously, when ice_viscosity_compute == MODEL, ice shelf viscosity was calculated using 1 quadrature point per cell; however, this quadrature point was not centered in the cell.
-Added a routine bilinear_shape_fn_grid_1qp, which is used to instead calculate viscosity for a single, cell-centered quadrature point
-Also added an option to define parameter ice_viscosity_compute = MODEL_QUADRATURE, where viscosity is instead calculated at the same four quadrature points used during the SSA solution (the typical approach in finite element codes, which should be more accurate).
The effective stress, Ee, varies between each quadrature point.  If using one quad point, Ee is incorporated directly into ice_visc(:,:), but if using 4 quad points, it is saved in a separate array CS%Ee(:,:,:). In the …

Modify quadrature used for ice shelf viscosity

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90

Added an option NONLIN_SOLVE_ERR_MODE=3 to check for convergence of the ice shelf SSA solution by testing the change of norm, i.e. 2*abs(|u_{t}|-|u_{t-1}|) / (|u_{t}|+|u_{t-1}|)

SSA convergence based on change of norm 

---

src/user/dumbbell_initialization.F90

Use thickness_to_dz to convert thicknesses from thickness units to height units in dumbbell_initialize_sponges with the traditional (non-ALE) sponges. Boussinesq answers are identical, but non-Boussinesq answers with an equation of state will change to be less dependent on the value of RHO_0.

*Use thickness_to_dz in dumbbell_initialize_sponges

---

config_src/external/drifters/MOM_particles.F90
src/core/MOM.F90

The particle code has so far used the same velocity has was used in the dynamics step. I would like to add the option for the particle code to use uhtr/h and vhtr/h, so that the velocities used to advect particles may include the effects of parameterized eddies.
To make this work, I have added a flag that controls which velocity to use and moved the particles_run step to take place after uhtr and vhtr are defined. The interfaces in the code and in config_src/external are updated to pass this information to the drifters package.

+Add particle code option to advect with uhtr

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90

Added ice shelf Coulomb friction law (Schoof 2005, Gagliardini et al 2007) needed for MISMIP+ experiments (Asay-Davis et al 2016).

Ice shelf Coulomb friction law

---

src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_open_boundary.F90

- Only when REMAP_AUXILIARY_VARS is true.
- Addresses #495 
- There is still a problem with diffu and diffv when REMAP_AUXILIARY_VARS is true. The first call to horizontal_viscosity after the first REMAP returns with a tile boundary mismatch.

+REMAP_AUX needs at least one more halo update.

---

src/parameterizations/vertical/MOM_diapyc_energy_req.F90

Refactored diapyc_energy_req_test and diapyc_energy_req_calc to remove the dependence on the Boussinesq reference density when in non-Boussinesq mode. This includes changes to the scaled units of the Kd_int argument to diapyc_energy_req_calc and the Kd argument to diapyc_energy_req_calc and the addition of a new argument to diapyc_energy_req_calc.  A call to thickness_to_dz is used for the thickness unit conversions.  There are 5 new internal variables, and changes to the units of several others.
These routines are not actively used in MOM6 solutions, but instead they are used for testing and debugging new code, so there are no changes to solutions, but the results of these routines can differ in fully non-Boussinesq mode.

+Refactored diapyc_energy_req_test

---

src/parameterizations/lateral/MOM_Zanna_Bolton.F90
src/parameterizations/lateral/MOM_hor_visc.F90

This PR updates the code of Zanna-Bolton-2020 mesoscale parameterization and seeks three purposes:
* Include features required to run NW2 simulations.
* Accelerate the code for many CPUs. Depending on configuration, the new code is **4-100 times faster**.
* Add measurement of runtime.
Simulations in NW2 at 1/4 resolution are now available with namelist parameters:
```
SMAG_BI_CONST = 0.06
USE_ZB2020 = True
ZB_SCALING = 2.5
ZB_SCHEME = 0
STRESS_SMOOTH_PASS = 4
ZB_KLOWER_R_DISS = 1.
```
The code was **significantly** restructured. The full list of commits is available in a separate branch [PR_ZB_2020_NW2_and_acceleration](https://github.com/Pperezhogin/MOM6/tree/PR_ZB_2020_NW2_and_acceleration).
The following namelist parameters are no longer available and set to default values:
``` …
```

Acceleration of Zanna-Bolton-2020 parameterization and new features required for NW2

---

config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
config_src/drivers/solo_driver/MOM_driver.F90
src/framework/MOM_diag_mediator.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

-Several edits to the ice shelf solo driver so that it works with the rest of the current MOM6
-Added capability to initialize a surface mass balance (SMB) that is held contstant over time when running from the ice-shelf solo driver (see new subroutine initialize_ice_SMB). This is required for MISMIP+. A constant SMB can also be used from the MOM driver for coupled ice-shelf/ocean experiments (e.g. MISOMIP).
-The new, constant SMB is passed into solo_step_ice_shelf, where change_thickness_using_precip is called
-Added capability to save both non-time-stamped and time-stamped restart files when using the ice shelf solo driver. This is useful for debugging.
-slight reorganization to when ice shelf post_data calls are made

Ice-shelf solo driver and MISMIP+ updates

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90

Previously, when an ice-shelf cell transitioned from partially-full to full, it was assigned a "reference thickness" equal to the average thickness of surrounding filled cells. In this PR, this average is instead weighted by the flux from each filled cell into the partially-filled cell. This flux-weighted average is more accurate.
Also fixed the incorrect computational bounds used during advection of the ice-shelf front.
The PR has been tested by running the flow-band ice shelf test for 300 years, where the modeled ice-shelf evolution sufficiently matched the analytical solutions for ice-shelf thickness, velocity, and front advection.

Update and bugfix to movement of the ice-shelf front

---

src/core/MOM_PressureForce_FV.F90
src/core/MOM_PressureForce_Montgomery.F90
src/parameterizations/lateral/MOM_self_attr_load.F90
src/parameterizations/lateral/MOM_spherical_harmonics.F90

Corrected dimensional rescaling bugs in the spherical harmonics SAL code.  An issue with horizontal length scaling was corrected by using G%Rad_Earth_L in place of G%Rad_Earth in spherical_harmonics_init.  There are new optional tmp_scale arguments to calc_SAL and spherical_harmonics_forward to allow the rescaling to be undone before calling the reproducing sums.
This commit also modifies the call to the reproducing sums in spherical_harmonics_forward so that all real or imaginary components are calculated with a single call, which reduces the cost of the SAL calculation reproducing sums from about 6.7 times the cost with non-reproducing sums to just 5.5 times as much in testing with the tides_025 test case.
There is also code added to avoid NaNs arising from a square root operating on a …

+Fix dimensional rescaling with HARMONICS_SAL

---

src/core/MOM_barotropic.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_forcing_type.F90
src/core/MOM_grid.F90
src/core/MOM_interface_heights.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_opacity.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_tracer_diabatic.F90
src/tracer/dyed_obc_tracer.F90
src/tracer/oil_tracer.F90

Added standard-format unit descriptions for 31 real variables in comments scattered across 14 modules in the core, tracer, and both parameterizations directories.  Only comments are changed and all answers are bitwise identical.
This a limited subset of the changes in (NOAA-GFDL/MOM6/pull/510) with one of the altered files omitted to avoid creating a conflict if the dimensional consistencies in that file are corrected via dev/ncar rather than dev/gfdl.

Document 31 real variables units

---

config_src/drivers/STALE_mct_cap/mom_ocean_model_mct.F90
config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
config_src/drivers/nuopc_cap/mom_ocean_model_nuopc.F90
src/core/MOM.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90

Added feature to write an ice_shelf.stats file, which outputs the kinetic energy and mass of the ice sheet according to the same parameters used to write the ocean.stats file (TIMEUNIT, ENERGYSAVEDAYS, and ENERGYSAVEDAYS_GEOMETRIC).

ice_shelf.stats

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90

This PR finishes implementing the "GL_couple" feature. Setting GL_couple=.true. determines ice-sheet grounding based on ocean column thickness, which is advantageous over the typical hydrostatic equilibrium condition for grounding (GL_couple=.false.) because it accounts for changes in sea level, tides, etc.  However, the ocean-thickness approach has not yet been thoroughly tested for dependence of grounding line movement on grid resolution.

Fix ice-sheet grounding based on ocean column thickness

---

src/core/MOM.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_state.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

This PR includes the remaining changes needed to successfully run the MISOMIP IceOcean tests for a coupled ocean and dynamic ice-sheet.
Several changes rwere equired for perfect restarts during coupled ice-sheet/ocean runs: (1) added visc%taux and visc%tauy to the ocean restart file; (2) ice sheet geometry is now updated before (rather than after) calculating ice shelf fluxes and pressure to ocean; and (3) corrected the calculation of ISS%mass_shelf for ice-shelf cells that are partially-filled with ice during advection of the ice front.
Also modified the scheme that maintains a nearly constant sea level in coupled ice-sheet/ocean runs by applying ocean balancing fluxes to offset changes in ice-sheet pressure on the ocean. This scheme now accounts for the case where some of the ice sheet …

ice-sheet/ocean coupling for misomip

---

.testing/Makefile
ac/deps/Makefile
ac/deps/Makefile.fms.in
ac/makedep

This PR updates our default FMS to 2023.03 in our autoconf builds, which includes our CI testing used in GitHub Actions.
There is also an upgrade to makedep which excludes directories (using the `-s` flag, for "skip"; all other good letters were taken).  This was required to removed the programs in `test_fms` which require preprocessor macros.  While we could have included them, we don't want to become obliged to maintain a list of required macros.
It also fixes a bug in `.testing/Makefile` which prevented the "target" (or regression) build from using the FMS2 framework API.

Update default FMS to 2023.03 in ac/deps and CI testing

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/framework/MOM_restart.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/tracer/MOM_tracer_advect.F90

Try again at fixing #506. Everything matched at a halo point two in except for h at the very top. Just above this in the code, there is a halo update on h, but just with halo=1.

Obc tracer fix

---

.github/workflows/coverage.yml
.github/workflows/perfmon.yml
.testing/Makefile
.testing/README.rst
.testing/tools/disp_timing.py
config_src/drivers/timing_tests/time_MOM_EOS.F90
config_src/drivers/unit_tests/test_MOM_EOS.F90
config_src/drivers/unit_tests/test_MOM_file_parser.F90
config_src/drivers/unit_tests/test_MOM_mixedlayer_restrat.F90
config_src/drivers/unit_tests/test_MOM_string_functions.F90
src/equation_of_state/MOM_EOS.F90
src/framework/MOM_error_handler.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

- Added simple single-thread program to invoke EOS unit tests
- Added not-as-simple program to time the cost of calculate_density() and calculate_spec_vol() for both scalar and array APIs
- Placed in new directory config_src/drivers/timing_tests/
- Renamed MOM_unit_test_driver.F90 to test_MOM_file_parser.F90
- Updated .testing/Makefile
- Added list of programs in config_src/drivers/unit_tests - These are added to BUILDS if DO_UNIT_TESTS is not blank. (DO_UNIT_TESTS was an existing macro but it might be unneeded) - These programs are compiled with code coverage
- Added list of programs in config_src/drivers/timing_tests
- These programs are compiled with optimization and no coverage
- Fixed rule for building UNIT_EXECS (which did not re-build properly because the central Makefile was …

Adds stand alone test_MOM_EOS and time_MOM_EOS

---

src/ALE/MOM_ALE.F90
src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90

Refactored ALE_remap_velocities to separate the code setting the thicknesses at velocity points from the code that actually does the remapping.  This includes the creation of the new public routines ALE_remap_set_h_vel and ALE_remap_set_h_vel_via_dz and the replacement the pair of tracer point thickness arguments to ALE_remap_velocities and remap_dyn_split_RK2_aux_vars with a pair of the old and new thicknesses at the velocity points and the elimination of several arguments to these routines that are no longer being used.  There are also new internal routines ALE_remap_set_h_vel_partial and ALE_remap_set_h_vel_OBC to apply modifications to the velocity point thicknesses with OBCs and one runtime option.  The runtime variable REMAP_UV_USING_OLD_ALG has effectively been moved from …

+Refactor ALE_remap_velocities

---

src/core/MOM_open_boundary.F90

This commit fixes a bug to ensure that OBC%debug is always being set when OBCs are in use.  After a recent commit, the value of OBC%debug was not being set and was being left in an indeterminate whenever DEBUG_OBC=False or DEBUG=False and DEBUG_OBC was unspecified.  This would lead to the model writing out a number of checksums in some cases with open boundary conditions enabled, depending on what value was inherited by the uninitialized OBC%debug.   Although this does not
change any answers, it will avoid a problem that will write out a large volume of undesired output and greatly slow down configurations with open boundary conditions.

Fix a bug that left OBC%debug uninitialized

---

src/tracer/MOM_CFC_cap.F90

The most recent NCAR -> GFDL merge created an error (courtesy of myself) which left the CFC concentration units in the post_data call, even though these are now handled at registration.
This patch restores this expression and removes the unit conversion from post_data.

Revert post_data fix to CFC concentration

---

.github/workflows/perfmon.yml
.testing/Makefile
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Jackett06.F90
src/equation_of_state/MOM_EOS_Roquet_SpV.F90
src/equation_of_state/MOM_EOS_Roquet_rho.F90
src/equation_of_state/MOM_EOS_TEOS10.F90
src/equation_of_state/MOM_EOS_UNESCO.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_Wright_full.F90
src/equation_of_state/MOM_EOS_Wright_red.F90
src/equation_of_state/MOM_EOS_base_type.F90
src/equation_of_state/MOM_EOS_linear.F90
src/tracer/MOM_neutral_diffusion.F90

We've speculated that branching (`select case` or deeply nested `if` trees) are contributing to poor performance. The equation of state (EOS) is a part of MOM6 where the module functions are called many times from all over the code and we have multiple choices to select from. I did try out procedure pointers but the code got messy quickly. Writing each EOS as an extension of a base class allows selection of the EOS when allocating/constructing the instance. This does manage to deliver a branch-free code and seem to deliver a performance improvement with the caveat that I've only evaluated performance using a new micro test (see section below). I suggest some proper performance analysis by a professional before we commit to this approach.
- Added a base class in MOM_EOS_base_type.F90
- All …

Refactors the EOS modules to use classes

---

src/core/MOM_open_boundary.F90

Fix unpaired parentheses in the format statement used in an error message about OBC segment data not being on the supergrid.  All answers are bitwise identical, but there is one less compile-time warning.

Fix unpaired parentheses in a formatting string

---

src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

update from #529 
attempting to solve problem raised by @gustavo-marques in https://github.com/mom-ocean/MOM6/pull/1616

change target to pointer and check for association

---

src/core/MOM_continuity.F90
src/core/MOM_continuity_PPM.F90
src/diagnostics/MOM_obsolete_params.F90

This pull request consists of a series of eight commits that uses the MOM_continuity module as a simple pass-through with some renaming for the MOM_continuity_PPM module and adds a total of 14 new publicly visible routines or types so that the various sub-steps within the continuity update can be called from outside.  These changes will provide greater flexibility as we reconsider the coupling between the baroclinic and barotropic modes, and perhaps allow for greater reuse of intermediate steps in the calculations (e.g., the PPM reconstructions) for computational efficiency.
The new publicly visible routines include: `continuity_fluxes()`, `continuity_adjust_vel()`, `zonal_mass_flux()`, `meridional_mass_flux()`, `zonal_edge_thickness()`, `meridional_edge_thickness()`, …

+(*)Added finer grained continuity interfaces

---

ac/Makefile.in
ac/makedep

This patch adds support to makedep for handling most #ifdef-like condition blocks. The following preprocessing commands are handled:
* #define / #undef
* #ifdef / #else / #endif
A new flag is added to provide defined macros (-D), and is chosen to match the `cpp` flag, so that flags can be shared across programs.
Macros are tracked in a new internal variable and are used for #ifdef testing.  Nested condition blocks are supported by using an internal stack of the exclusion state.
Certain cases are still not handled.
* #if blocks containing logical expressions are not parsed.
* CPP content inside of #include is ignored.
No doubt many other cases are still unconsidered, such as exotic macro names.
The autoconf builds use this feature by passing the generated $(DEFS) argument to makedep.  This …

makedep: Include support for CPP condition blocks

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_linear.F90
src/initialization/MOM_coord_initialization.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/tracer/MOM_tracer_Z_init.F90
src/user/DOME2d_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/Rossby_front_2d_initialization.F90
src/user/SCM_CVMix_tests.F90
src/user/adjustment_initialization.F90
src/user/benchmark_initialization.F90
src/user/dense_water_initialization.F90
src/user/dumbbell_initialization.F90
src/user/dumbbell_surface_forcing.F90
src/user/seamount_initialization.F90
src/user/sloshing_initialization.F90

Standardized the syntax for the units of salinities that are read via get_param calls to be uniformly 'units="ppt"' or similar units for derivatives with salinity.  The only exceptions are places where practical salinity is used specifically, which occurs for several arguments in the MOM_EOS code.  All answers are bitwise identical, but there are changes to a number of MOM_parameter_doc files.

+Standardize input salinity units as "ppt"

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/STALE_mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
config_src/drivers/solo_driver/MOM_surface_forcing.F90

Renamed the runtime parameter FIX_USTAR_GUSTLESS_BUG to USTAR_GUSTLESS_BUG (with a switch between the meanings of true and false for the two parameters) for consistency with the syntax of other bug-fix flags in MOM6 and to partially address dev/gfdl MOM6 issue #237.  Input parameter files need not be changed right away because MOM6 will still work if FIX_USTAR_GUSTLESS_BUG is specified instead of USTAR_GUSTLESS_BUG, but USTAR_GUSTLESS_BUG will be logged, so there are changes to the MOM_parameter_doc files.   By default or with existing input parameter files, all answers are bitwise identical, and there is error handling if inconsistent settings of FIX_USTAR_GUSTLESS_BUG and USTAR_GUSTLESS_BUG are both specified.

+FIX_USTAR_GUSTLESS_BUG is now USTAR_GUSTLESS_BUG

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

This PR guarantees consistency of the ice sheet code under rotated/flipped input and grids, and under dimensional rescaling to the +/-140 power. Bitwise identical results were achieved under rotation/rescaling using standard 2D test cases such as MISMIP+. Major changes include the following:
- Specified order of operations throughout, and modified the implementation of FEM integration,  h-point-to-node operations, etc for consistency under rotation (see MOM_ice_shelf_dynamics.F90 subroutines calc_shelf_driving_stress, CG_action, CG_action_subgrid_basal, matrix_diagonal, shelf_advance_front, and interpolate_h_to_b).
- Added an ice-shelf version of 'first_direction' and 'alterate_first_direction', allowing users to control the order in which the x- and y-direction ice-shelf advection calls …

Ice sheet: consistency under dimensional rescaling and rotation

---

src/core/MOM_dynamics_split_RK2.F90

Renamed the arguments `u` and `v` to `step_MOM_dyn_split_RK2()` as `u_inst` and `v_inst` to more clearly differentiate between the instantaneous velocities (`u_inst` and `v_inst`) and the velocities with a time-averaged phase in the barotropic mode (`u_av` and `v_av`).  A comment is also added at one point where the wrong velocities are being used to calculate and apply the Orlanski-style radiation open boundary conditions, with the intention of adding the option to correct this in a subsequent commit.  This commit only changes the name of a pair of internal variables in one routine, and all answers are bitwise identical.

Rename u arg to step_MOM_dyn_split_RK2 as u_inst

---

src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90

Renamed the runtime parameter FIX_UNSPLIT_DT_VISC_BUG to UNSPLIT_DT_VISC_BUG (with a switch between the meanings of true and false for the two parameters) for consistency with the syntax of other bug-fix flags in MOM6 and to partially address dev/gfdl MOM6 issue #237.  Input parameter files need not be changed right away because MOM6 will still work if FIX_UNSPLIT_DT_VISC_BUG is specified instead of UNSPLIT_DT_VISC_BUG, but UNSPLIT_DT_VISC_BUG will be logged, so there are changes to the MOM_parameter_doc files.   By default or with existing input parameter files, all answers are bitwise identical, and there is error handling if inconsistent settings of FIX_UNSPLIT_DT_VISC_BUG and UNSPLIT_DT_VISC_BUG are both specified.

+FIX_UNSPLIT_DT_VISC_BUG is now UNSPLIT_DT_VISC_BUG

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2b.F90

This pull request consists of two commits that add the new module MOM_dynamics_split_RK2b and then revise it to give a new split time-stepping scheme.  This new scheme is enabled by setting the new runtime parameter `SPLIT_RK2B = True`.
With this new scheme, the velocity that is passed back and forth to the driver is averaged over the phases of the barotropic stepping, rather than being an instantaneous velocity.  The instantaneous velocities can be regenerated from the phase-averaged velocities using a stored barotopic velocity increment.  It is hoped that this new scheme will be slightly more robust than before, although this will be more expensive than the other (previous) split time stepping scheme, with two calls to horizontal_viscosity per baroclinic dynamics time step (instead of …

+*Add and revise step_MOM_dyn_split_RK2b

---

src/framework/MOM_intrinsic_functions.F90

Modified the cuberoot function to do 3 iterations with Halley's method before switching to Newton's method as before, which saves about 2 iterations.  Also added a check for a perfect solution as a stopping point during the Newton's method iterations, because this prevents about half the instances where we would compare successive solutions, avoiding some divisions and extra iterations. This changes answers at roundoff for code that uses the cuberoot function, so ideally this PR would be dealt with before the cuberoot becomes widely used.

*Use Halley method iterations in cuberoot function

---

docs/forcing.rst

I've added a summary of how to use the `data_table` to the `forcing` page of the docs. I think this might be helpful for new users, as otherwise they need to know to look in the FMS / data_override repository and find the readme there.

Data table documentation

---

src/framework/MOM_file_parser.F90

This patch adds `do_not_log` to `openParameterBlock`, to prevent logging of `BLOCK%` `%BLOCK` entry and exit calls.
The argument was not added to `closeParameterBlock`, since this state can be tracked inside the `block` with a new `log_access` field in `parameter_block`.
This flag does not extend to parameters within the block, since (as far as I know) there is no way for a `get_param` to know if it is within a block or not.  Even if it could know this, there would need to be some careful handling of nested blocks.
The potential block/parameter inconsistency should be supported at some point, but for now it is the user's responsibility to consistently apply `do_not_log` to blocks and its contents.

Params: Add do_not_log to param block open/close

---

src/tracer/oil_tracer.F90

Added a missing unit conversion factor to a hard-coded 10 m distance in oil_tracer_column_physics.  This will not change answers in Boussinesq cases without any dimensional rescaling, but it will correct answers in a hypothetical non-Boussinesq case.  Also made some white space in expressions near this fix more closely match the MOM6 style guide. No answers are affected in any known existing regression test cases or other runs.

(*)Oil_tracer_column_physics unit conversion fix

---

src/diagnostics/MOM_spatial_means.F90
src/framework/MOM_diag_remap.F90

Use GV%H_to_MKS instead of GV%H_to_m when undoing the dimensional rescaling of thicknesses when taking weighted averages in horizontally_average_diag_field, global_layer_mean and global_volume_mean.  In Boussinesq mode, these are identical, but in non-Boussinesq mode using GV%H_to_m introduced a multiplication and then division by the Boussinesq reference density, whereas GV%H_to_MKS avoids this by rescaling to a volume or mass-based coordinate depending on the mode.  Several comments were also updated to reflect these conditional changes in the units of some internal variables.  All expressions are mathematically equivalent, and this does not impact any solutions, but there can be changes in the last bits in some non-Boussinesq averaged diagnostics.

(*)Avoid using RHO_0 in non-Boussinesq averaging

---

src/framework/MOM_intrinsic_functions.F90

This patch replaces the intrinsic-based exponent rescaling with explicit bit manipulation of the floating point number.
This appears to produce a ~2.5x speedup of the solver, reducing its time from embarassingly slow to disappointingly slow.  It is slightly faster than the GNU cbrt function, but still about 3x slower than the Intel SVML cbrt function.
Timings (s) (16M array, -O3 -mavx -mfma, obviously many details omitted...)
| Solver              |  -O2  |  -O3  |
|---------------------|-------|-------|
| GNU x**1/3          | 0.225 | 0.198 |
| GNU cuberoot before | 0.418 | 0.412 |
| GNU cuberoot after  | 0.208 | 0.187 |
| Intel x**1/3        | 0.068 | 0.067 |
| Intel before        | 0.514 | 0.507 |
| Intel after         | 0.213 | 0.189 |
At least one issue here is that Intel SVML is …

Intrinsics: Faster cuberoot scaling functions

---

src/parameterizations/vertical/MOM_energetic_PBL.F90

Use the new cuberoot() function in place of **(1./3.) to calculate the turbulent velocity vstar in ePBL_column when EPBL_ANSWER_DATE is 20240101 or higher.  This is mathematically equivalent to the previous version, but it does change and answers at roundoff and it allows several dimensional scaling factors that had previously been required to be eliminated.  All answers are mathematically equivalent, but answers do change if EPBL_ANSWER_DATE is 20240101 or higher and the description of EPBL_ANSWER_DATE changes in some MOM_parameter_doc files.

(*)Use cuberoot in ePBL_column

---

src/equation_of_state/MOM_EOS.F90

Fixed two bugs on a single line of `convert_temp_salt_for_TEOS10()`.  The first bug was a reversal in the order of the temperature and salinity arguments to `poTemp_to_consTemp()`, resulting in temperatures that closely approximate the salinities.  The second bug that was fixed on this line was temperatures being rescaled with a factor that is appropriate for salinities. This bug-fix will change answers dramatically for any cases that use the `ROQUET_RHO`, `ROQUET_SPV` and `TEOS10` equations of state and initialize the model with `INIT_LAYERS_FROM_Z_FILE = True`.

*Fix two bugs in convert_temp_salt_for_TEOS10

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/MOM_tracer_flow_control.F90

The series of 3 commits in this pull request adds the ability to remap and initialize tracers and similar scalars using input and output grids that are defined in depth space or other arbitrary vertical grids, rather than assuming that we are working with thicknesses (in H units).  The specific changes to enable this new capability include adding new optional arguments to `ALE_remap_scalar()` and `MOM_initialize_tracer_from_Z()`, along with the new functions `set_h_neglect()` and `set_dz_neglect()` in the `MOM_regridding` module.  This new capability is exercised for temperatures and salinities that are initialized with `MOM_temp_salt_initialize_from_Z()` when `Z_INIT_REMAP_GENERAL = False`.
The MOM_generic tracer code was also revised to use `thickness_to_dz()` to convert the models grid …

+*Non-Boussinesq tracer initialization in Z-units 

---

src/diagnostics/MOM_wave_speed.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90

Eliminated some unused calculations in wave_speed and thickness_diffuse_full that would use the Boussinesq reference density when in non-Boussinesq mode, either by adding logical flags around the calculations so that they only occur in Boussinesq mode.  All answers are bitwise identical.

Remove some unused calculations if non-Boussinesq

---

src/ALE/MOM_regridding.F90
src/ALE/coord_adapt.F90
src/ALE/coord_rho.F90
src/ALE/coord_sigma.F90

Added or amended comments describing about 90 variables in the MOM_regridding, coord_adapt, coord_rho, and coord_sigma modules to document the purpose and units of real variables using the MOM6 standard syntax.  A missing doxygen comment was also added to describe `inflate_vanished_layers_old()`.  A few unused internal variables were also eliminated, including the `max_depth_index_scale` element of the `regridding_CS` type.  All answers are bitwise identical and only comments are changed.

Document MOM_regridding and coord variable units

---

src/core/MOM.F90
src/core/MOM_check_scaling.F90
src/core/MOM_forcing_type.F90
src/core/MOM_isopycnal_slopes.F90
src/core/MOM_verticalGrid.F90
src/equation_of_state/MOM_EOS_linear.F90

Modified comments to document the units of 17 variables in 5 files in the core directory and another 5 variables in MOM_EOS_linear.F90.  Only comments are changed and all answers are bitwise identical.

Document core and linear EOS variable units

---

src/core/MOM.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

Revised the ALE_sponge code to convert the model's thicknesses (in thickness units of [H ~> m or kg m-2]) into layer vertical extents (in height units of [Z ~> m]) to match how the input datasets vertical grids are specified and to avoid using the Boussinesq reference density to do the opposite conversion when in non-Boussinesq mode.  The internal conversion in `apply_ALE_sponge()` between layer thicknesses and layer vertical extents matches those in `thickness_to_dz()`, and uses the layer-averaged specific volumes when in non-Boussinesq mode.
As a part of these changes, 12 internal variables in MOM_ALE_sponge were renamed (e.g., from `data_h` to `data_dz`) to more clearly reflect that they are the layer vertical extents instead of thicknesses, and there are new 3-d variables `dz_model`, …

+(*)non-Boussinesq ALE_sponges work in Z units

---

src/parameterizations/vertical/MOM_bkgnd_mixing.F90

Use `thickness_to_dz()` to convert the layer thicknesses into the geometric depths used to set the Bryan-Lewis background diffusivities instead of multiplication by GV%H_to_m, thereby avoiding division by the Boussinesq reference density in non-Boussinesq mode. No answers are changed in any Boussinsesq configurations, but answers will change in non-Boussinesq configurations that have BRYAN_LEWIS_DIFFUSIVITY = True.

(*)Use thickness_to_dz with BRYAN_LEWIS_DIFFUSIVITY

---

src/tracer/MOM_tracer_Z_init.F90

Added the new optional `scale` argument to `tracer_Z_init()` to allow the units of the tracers that it initializes from a z-space file to be rescaled, similarly to what is already done in `tracer_z_init_array()`.  This also required the addition of the new `missing_scale` argument to the private routine `read_Z_edges()` to specify how the missing values are rescaled. Comments were also added or modified describing 28 real variables or their units in this module.  By default all answers are bitwise identical, but when this new option is exercised, answers could change at roundoff for some non-Boussinesq cases.

+tracer_Z_init can rescale tracers

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

Inside the `MLE%` ... `%MLE` parameter block, the default answer date was being read while inside the block.  Since the namespaces inside blocks are not shared or inherited, this was creating a new parameter, `MLE%DEFAULT_ANSWER_DATE`, whose value differed from the global `DEFAULT_ANSWER_DATE`.  This was causing unintuitive behavior of `MLE%ML_RESTRAT_ANSWER_DATE`, which ignored this global answer date.
This patch reads `DEFAULT_ANSWER_DATE` outside of the block, so that `ML_RESTRAT_ANSWER_DATE` now defaults to the global value.

MLE: Use default answer date outside of block

---

src/framework/MOM_diag_remap.F90

Added explicit names to the `h_neglect` and `h_neglect_edge` arguments in a call to `build_rho_column()` in `diag_remap_update()`.  These were problematic because these arguments were previously in the wrong positions and hence were being used for the wrong (unused) variables inside of `build_rho_column()`.  In Boussinesq mode, the results will be the same as long as there is no dimensional rescaling being applied to thicknesses, and it this were being tested it would have resulted in a dimensional consistency test failure.  In non-Boussinesq mode, the values of `H_subroundoff` as used for this coordinate will be off by a factor of RHO_KV_CONVERT (usually 1035), but these thicknesses are so small that they do not matter unless ANGSTROM is explicitly set to zero (when no dimensional …

(*)Fix bug in h_neglect used to remap diagnostics to density space

---

src/core/MOM_open_boundary.F90

Revised `update_OBC_segment_data()` to keep the z-space input data in height units ([Z ~> m]) rather than rescaling them to thickness units.  This change means that the non-Boussinesq open boundary condition calculations avoid using the Boussinesq reference density.  Associated with this change, 5 internal variables in `update_OBC_segment_data()` were renamed to reflect that they are layer vertical extents instead of thicknesses.  Answers are bitwise identical in any Boussinesq cases.  However, answers will change in any non-Boussinesq cases that use open boundary conditions that use `time_interp_extrnal()` to read in Z-space data.

(*)non-Boussinesq Z unit update_OBC_segment_data

---

src/tracer/MOM_CFC_cap.F90

Removed the duplicative multiplication by the Boussinesq density and related unit conversion factors in the calculation of the diagnosed mole concentration of the "cfc11" and "cfc12" diagnostics.  This unit rescaling is duplicative of the conversion factors in the `register_diag_field()` calls for these diagnostics (at about line 263).  This will change these two diagnostics by a factor of RHO_0.  This bug arose from separate and independent changes coming from GFDL and NCAR to add the same missing rescaling factor, and it might have gone undetected because of the vast range of valid values for CFC concentrations or because all of our regression testing uses calendar dates that precede the invention and first release of CFCs in the 1930s.  Although this commit will correct the code that …

*Corrected CFC diagnostics and non-Bous CFC fluxes

---

docs/requirements.txt

Minor version updates to multiple packages used in the generation of the documentation introduce dependencies needing Sphinx >= 5.0, which breaks the sphinx extensions we use in documenting the MOM6 APIs. I have added versions for all the packages needed to keep things working with Sphinx4 for now, but we really do need to find a way to work with the newer versions.
More pinningaof of requirements for readthedocs
More pinning of requirements for readthedocs

Pinning package requirements for readthedocs

---

.github/actions/testing-setup/action.yml
.testing/Makefile
ac/configure.ac

This patch introduces two new macros, `BUILD` and `WORK`, to permit relocation of the `build/` and `work/` directories.  It also makes the following smaller changes:
* `deps/` is now defined by the `DEPS` macro.  If unset, `deps/` is placed in the `BUILD` directory.
* `results/` is moved into `WORK`.
* Compiler flags which track directories now use `$(abspath ...)` to allow for arbitrary paths.
* GitHub CI paths were adjusted to support these new settings.
* `DO_*` flags are now used as on/off with `ifdef` testing, rather than checking for `true` values.
* mkmf macros have been removed from the coupled test config.
* The default FMS infra has been changed to FMS2 in all components, including the `configure.ac` outside of `.testing`.
This work will enable testing of multiple FMS libraries …

Create BUILD and WORK directory macros

---

src/parameterizations/vertical/MOM_set_viscosity.F90

The series of 3 commits in this pull request refactors set_viscous_BBL to separate out some of the calculations related to the channel drag parameterizations and added an option to calculate L_open in the concave case without using trigonometric functions, thereby addressing dev/gfdl MOM6 issue #483.  This new option in the new subroutine `find_L_open_concave_iterative()` is more accurate than the mathematically equivalent trigonometric version, and it is enabled by setting the new runtime parameter TRIG_CHANNEL_DRAG_WIDTHS = False.  There is also extensive code that can be used via a debugger to verify that the new option is both correct and more accurate that its predecessor.  This debugging code could perhaps be removed in a subsequent commit.  By default all answers are bitwise …

+Refactor set_viscous_BBL and add non-trigonometric find_L_open option

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/tracer/MOM_tracer_advect.F90

- It was blowing up with "forrtl: error (65): floating invalid" when accessing dz in the halo at the boundary, but just sometimes. My default layout is trouble while my testing layout of 48 cores is not.

 Compute dz in the halo for OBC segments

---

src/initialization/MOM_shared_initialization.F90

Corrected bugs in the horizontal indexing in `apply_topography_edits_from_file()` that led to differing answers depending on the value of `GLOBAL_INDEXING`.  This change gives identical results when `GLOBAL_INDEXING` is used, as can be seen by noting that `G%idg_offset = G%isd_global + G%isd` and that without global indexing `G%isd = 1`, but with global indexing the new expressions give the same answers as without them.  Because global indexing is not typically used, answers are not changed for any cases in the MOM6-examples test suite.

(*)Fix apply_topography_edits_from_file indexing

---

src/core/MOM.F90
src/framework/MOM_diag_mediator.F90
src/framework/MOM_diag_remap.F90

The series of 3 commits in this pull request revise how the remapping of diagnostics are handled, including correcting bugs that lead to segmentation faults when global indexing is used and working in depth (z-) space with for some remapping of non-Boussinesq diagnostics.  This required the reordering of the halo updates for temperatures, salinities and thicknesses during the initialization in MOM.F90 and the subsequent calculation of derived thermodynamic quantities so that they are available for remapping diagnostics.
For `REMAPPING_ANSWER_DATES` later than 20240201, `diag_remap_updated()` does an explicit sum to determine the total water column thickness, rather than using sum function, which is indeterminate of the order of the sums.  For some compilers, this could change the vertical …

+(*)Revise remapping of diagnostics

---

src/framework/MOM_diag_mediator.F90

Corrected indexing problems in `downsample_mask()` that would cause masked reduced-resolution diagnostics to work improperly when the model is in symmetric memory mode or when global indexing is used.  This involves passing the starting index in memory of the native-grid field being downsampled in all calls to `downsample_mask()`.  In global-indexing mode, this change avoids a series of segmentation faults that stopped the model runs when compiled for debugging. All solutions are bitwise identical in all cases but some down-scaled diagnostics will change in some memory modes, hopefully becoming consistent across all memory modes (although this has yet to be tested in all modes).

+(*)Fix downsample_mask indexing bugs

---

src/user/MOM_wave_interface.F90

Replaced the `IIm1` and `JJm1` variables in `Update_Stokes_Drift()` with `I-1` and `J-1` .  The previous expressions could give incorrect solutions at the southern and western edges of the global domain with global indexing and serve no purpose when global indexing is not used.  In addition, the i-, j- and k- index variables in `Update_Surface_Waves()`, `Update_Stokes_Drift()`, `get_Langmuir_Number()` and `Get_SL_Average_Prof()` were changed from `ii` to `i`, `jj` to `j`, and `kk` to `k` to follow the patterns used elsewhere in the MOM_wave_interface module and throughout the rest of the MOM6 code.  All answers are bitwise identical in cases that do not use global indexing.

(*)Eliminate IIm1 and JJm1 in Update_Stokes_Drift

---

src/ALE/MOM_hybgen_regrid.F90
src/ALE/MOM_hybgen_remap.F90
src/ALE/MOM_remapping.F90
src/ALE/P1M_functions.F90
src/ALE/PCM_functions.F90
src/ALE/PLM_functions.F90
src/ALE/PPM_functions.F90
src/ALE/PQM_functions.F90
src/ALE/coord_zlike.F90
src/ALE/polynomial_functions.F90
src/ALE/regrid_edge_values.F90
src/ALE/regrid_solvers.F90
src/ALE/remapping_attic.F90

Added or amended comments to document the mostly arbitrary units of about 108 variables in 5 low-level remapping modules.  Only comments are changed and all answers are bitwise identical.

Document remapping function variable units

---

src/tracer/MOM_generic_tracer.F90

#520 has successfully addressed layout and restart reproducibility concerns in physics-only runs with OBC, resulting in a runtime increase of approximately `3%` in regional cases. Building on this progress, the PR further resolves reproducibility issues for generic tracer runs with OBC, ensuring tracer values at OBC are correctly read from restart files.
We also added a new RT case based on Northwest Atlantic configuration with generic CFC tracers, [NWA12.CFC](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/actions/runs/8115574767/job/22184400255), to the [CEFI-regional-MOM6](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/tree/bug/tracer_repro/exps/NWA12.CFC) repro.  The RT case consists of three steps::
1. A 2 hrs run with a 16x8 layout
2. A 1hr run with a 16x8 layout
3. A 1hr run with …

Restore repro across restarts and layout in generic tracer runs with OBC

---

src/core/MOM_forcing_type.F90
src/core/MOM_porous_barriers.F90
src/core/MOM_variables.F90
src/framework/MOM_io_file.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

This patch contains several bugfixes associated with the rotational grid testing.
The following checksums are declared as scalar pairs, rather than vectors:
* eta_[uv] (in porous barrier)
* por_face_area[UV]
* por_layer_width[UV]
* Ray_[uv] (Rayleigh drag velocity)
Fluxes and surface fields are now permitted to contain tracer fluxes (tr_fluxes) when rotation is enabled.  The fields are retained in their unrotated form, since these are accessed and handled outside of MOM6.
The rotated p_surf_SSH pointer in forces now correctly points to either p_surf or p_surf_full.
read_netcdf_nc() now correctly uses the unrotated horizontal index struct HI, used to access the contents of the file.  Previously, it was using the model HI, which may be rotated.
Reading chlorophyll with time_interp_external …

Rotation bugfixes

---

src/tracer/MOM_neutral_diffusion.F90

Added the option to do neutral tracer diffusion with expressions that satisfy rotational symmetry.  This option is enabled by setting the new runtime parameter `NDIFF_ANSWER_DATE` to be greater than 20240229.  By default, this parameter is set to use the previous expressions, although the default may be changed later to follow `DEFAULT_ANSWER_DATE`.  By default all answers are bitwise identical, but there are changes to some MOM_parameter_doc files due to the introduction of a new runtime parameter.

+Rotationally symmetric neutral diffusion option

---

src/core/MOM_dynamics_split_RK2.F90
src/parameterizations/lateral/MOM_hor_visc.F90

Runtime parameter `USE_CONT_THICKNESS` is added in horizontal viscosity to let it use velocity-point thickness consistent with the continuity solver. Thickness at velocity points simply uses h[uv] in BT_cont type. So the option only applies to split mode. 
The purpose of this PR is to open the way for tests. A more general (and careful) implementation can be added later.

Add an option in hor_visc to adopt velocity thickness from continuity solver

---

src/core/MOM.F90

When ROTATE_INDEX is true, the model keeps both its rotated internal grid and an unrotated grid for setting initialization and forcing.  When the model is run in symmetric memory mode, there is an auxiliary non-symmetric domain that is needed for reading in fields at velocity points.  The auxiliary domain in the unrotated grid (G_in) was not being set previously, causing the model to fail to run some cases when ROTATE_INDEX was true.  That auxiliary domain in the unrotated grid is now being set up properly.  All answers and output are bitwise identical for any cases that worked previously.

Set up auxiliary domain for unrotated grid

---

config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90

Added code to tht two versions of clone_MD_to_MD in the FMS1 and FMS2 versions of MOM_domain_infra.F90 to properly change the flags when a tripolar grid is rotated, so that it does not lead to misleadingly incorrect answers.  With the current versions of FMS, doing grid rotation testing with a tripolar grid will lead to error messages about the incomplete implementation of FMS, but these failures are preferable to the model silently working incorrectly.  All answers are bitwise identical in cases that worked correctly before.

Set flags properly for rotated tripolar grids

---

src/framework/MOM_io_file.F90
src/framework/MOM_netcdf.F90

Add `get_netcdf_filename()` and use it to add useful details (the field and filenames in question) to a fatal error message in `get_field_nc()`.  All answers are bitwise identical, but there is a new public interface and some output is changed in cases where `get_field_nc()` is failing.

+Add get_netcdf_filename for a get_field_nc error

---

src/tracer/MOM_tracer_hor_diff.F90

Added the option to do epipycnal tracer diffusion between a bulk mixed layer and the interior ocean with expressions that satisfy rotational symmetry.  This option is enabled by setting the new runtime parameter HOR_DIFF_ANSWER_DATE to be greater than 20240330.  By default, this parameter is set to use the previous expressions, although the default may be changed later to follow DEFAULT_ANSWER_DATE.  Also corrected two bugs with the tracer limits used to repartition the fluxes between layers within tracer_epipycnal_ML_diff; this correction is enables by setting the new HOR_DIFF_LIMIT_BUG to .false., but to retain previous answers by default it is set to true. By default all answers are bitwise identical, but there are changes to some MOM_parameter_doc files due to the introduction of two …

+Rotationally symmetric epipycnal diffusion option

---

config_src/drivers/nuopc_cap/mom_cap.F90
config_src/drivers/nuopc_cap/mom_cap_methods.F90
config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_coms_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90
src/core/MOM.F90
src/framework/MOM_domains.F90
src/framework/MOM_netcdf.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_hor_visc.F90

Merge of main to dev/gfdl.
This is a bookkeeping PR which will be handled via git. Do not merge via GitHub.

Main to dev/gfdl (2024-04-05)

---

src/initialization/MOM_state_initialization.F90
src/user/DOME2d_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/RGC_initialization.F90
src/user/dense_water_initialization.F90
src/user/dumbbell_initialization.F90

Pass vertical extents (`dz` in `[Z ~> m]`) instead of thicknesses (`h` in `[H ~> m or kg m-2]` and use `data_h_is_Z` flag in calls to `initialize_ALE_sponge()` calls from 5 user modules and avoid extra calls to `dz_to_thickness()` in these routines.  All Boussinesq solutions are bitwise identical, but in any non-Boussinesq configurations using ALE sponges, the previous conversion from `dz` to thickness and back again can change `dz` in the last bits, so some non-Boussinesq answers could change.

(*)Pass dz to user initialize_ALE_sponge calls

---

src/core/MOM_checksum_packages.F90
src/diagnostics/MOM_PointAccel.F90
src/tracer/MOM_tracer_registry.F90

When in non-Boussinesq mode, write out mass-based tracer inventories from calls to `MOM_tracer_chkinv()` and mean thicknesses in mass per unit area from calls to `MOM_state_stats()`, rather than the approximate volumes that depend on the Boussinesq reference density.  Similarly the thicknesses and transports output by `write_u_accel()` and `write_v_accel()` are in mass per unit area or mass flux per unit face length in non-Boussinesq mode.  This is done specifically by using `GV%H_to_MKS` in place of `GV%H_to_m`; these are identical in Boussinesq mode, but `GV%H_to_MKS` avoids rescaling by the Boussinesq reference density in non-Boussinesq mode.  Several comments were also updated to reflect these changes.  All solutions are identical, but there are changes in the units of several …

(*)Avoiding using RHO_0 in non-Boussinesq debugging

---

config_src/drivers/timing_tests/time_MOM_EOS.F90
src/ALE/coord_adapt.F90
src/ALE/regrid_interp.F90
src/core/MOM_open_boundary.F90
src/diagnostics/MOM_spatial_means.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/stochastic/MOM_stochastics.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/ISOMIP_tracer.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/MOM_offline_aux.F90
src/tracer/MOM_offline_main.F90
src/tracer/MOM_tracer_registry.F90
src/tracer/MOM_tracer_types.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/dyed_obc_tracer.F90
src/tracer/ideal_age_example.F90
src/tracer/nw2_tracers.F90
src/tracer/oil_tracer.F90
src/tracer/pseudo_salt_tracer.F90

Added or corrected the units in comments describing about 115 real variables scattered across 14 tracer modules and 10 other modules.  All answers are bitwise identical, and only comments are changed.

Add units to the descriptions of 115 variables

---

ac/deps/Makefile.fms.in
ac/makedep

This patch adds a relatively robust parser for C preprocessor expressions inside of an #if statement.
The following are supported:
* Nearly all operators, including arithmetic, logical, and bitwise,
* Parentheses within expressions,
* defined() evaluations.
The following are explicitly not supported:
* Function macros,
* Multiline preprocessors.
No doubt there are other lingering issues, but this is comprehensive enough to handle both MOM6 as well as current and legacy FMS source codes.
Existing Makefile.dep output files appear to be mostly unchanged.  One rule (data_override.o) had its arguments reordered but is otherwise unchanged.  mpp_data.o had its rule corrected to use mpp_util_mpi.inc rather than mpp_util_nocomm.inc.
Some fixes and adjustments were made to the overall makedep …

CPP expression parser for makedep

---

src/user/MOM_wave_interface.F90

Eliminated unneeded rescaling factors when setting the surface Stokes drift spectrum variables (`UStk_Hb` and `VStk_Hb`) from `forces%[UV]Stkb` in `Update_Surface_Waves()`.  This bug appears to have been introduced when merging in code that updates the Stokes drifts that was added on one branch (dev/ncar) separately from changes in how these Stokes drifts are scaled in the `mech_forcing` type on anther branch (dev/gfdl), although it might just have been an oversight during refactoring.  All answers are bitwise identical when no dimensional rescaling is being used, but answers could change for some uncommon cases using the Stokes drift spectrum when dimensional rescaling is applied.

(*)Fix Stokes drift spectrum rescaling

---

src/parameterizations/vertical/MOM_set_viscosity.F90

Setting `BBL_USE_TIDAL_BG` in OM5_b003 revealed non-conservation and non-reproducibility across layouts. A local scalar variable was correctly being set based on the tidal amplitude but was being re-used after a break between loops.
- Replaced the scalar variable U_bg_sq with a vector u2_bg(:) that is set to either a constant or the square of the tidal amplitude.
- The module parameter CS%drag_bg_vel was not set if using the tidal amplitude but WAS being used for conditionals. We now set it to 1e30 because it should NOT be used or impact the solution. Setting it to zero, or anything meaningful would allow code to use it inadvertently. This "constant" does not need to satisfy any dimensional testing.

Fix for using tidal amplitude when determining the BBL thickness

---

.testing/tools/parse_perf.py

Print the line and its tokenization in parse_perf.py if the tokenization fails for any reason.  This is most likely to occur if the fourth token is not an integer.
This is possibly a platform-dependent issue, and not something easily replicated on any machine we are using, so it is easier to simply integrate it into the codebase.

Perf: Better error report for failed parsing

---

src/user/Neverworld_initialization.F90
src/user/basin_builder.F90
src/user/tidal_bay_initialization.F90

Added descriptions or added or corrected the units in the descriptions of 72 variables in the Neverworld_initialization and basin_builder modules.  This includes minor refactoring to avoid reusing scalar variables with completely different units.  Also refactored tidal_bay_set_OBC_data by moving the multiplication by rescaling factors at one point so that the units of a variable agree with their documented units.  All answers are bitwise identical.

Better document variable units in 3 user modules

---

src/parameterizations/vertical/MOM_bkgnd_mixing.F90

Adds a maximum absolute latitude above which to reduce the background diffusion to the minimum value.
This was used in OM5 run odiv-263 and greatly reduces the Arctic salinity biases. Ultimately this option will be replaced with the prognostic internal wave parameterization but for the interim this code mode is needed for OM5.

Cricital latitude modification of Henyey

---

src/parameterizations/vertical/MOM_vert_friction.F90

Added standard-format unit descriptions for 34 real variables in comments in the subroutine `vertPFmix()`.  Another 6 comments were added noting dimensionally inconsistent expressions in `vertFPmix()`.  Only comments are changed and all answers are bitwise identical.

Document units of 34 real variables in vertFPmix

---

src/core/MOM_density_integrals.F90

Refactored 4 routines (`int_density_generic_pcm()`, `int_density_generic_ppm()`, `int_spec_vol_generic_pcm()` and `int_spec_vol_generic_plm()`) in density integrals for greater computational efficiency by doing fewer calls to the equation of state routines but calculating entire rows of densities at subgrid locations with each each call, replicating what was already being done `int_density_dz_generic_plm()`. To accomplish this, a number of variables now use larger arrays than previously.  The total computational cost of the non-Boussinesq pressure gradient force calculation was more than 50% greater with the previous code in some tests.  All answers are bitwise identical.

Refactoring density integrals for efficiency

---

src/ALE/MOM_ALE.F90
src/core/MOM.F90

Adds `INIT_BOUNDARY_EXTRAP` parameter and function, so that `REMAP_BOUNDARY_EXTRAP` can just be used in the initialisation and not in the model dynamics, as required for an ice shelf in ALE mode.
*Background:*
When an ice shelf is initialised in ALE mode, `MOM_state_initialization` first initialises the ocean thickness and T/S with topography, but without an ice shelf. It then calls the function `trim_for_ice`, which takes in input of the ice shelf pressure, and in turn calls `cut_off_column_top` which truncates the columns (and adds vanishing layers) to account for the pressure of the ice depressing the free surface. The output of this is a grid with the ice shelf boundary treated in a ALE z-coordinate fashion with vanishing layers at the surface, and @adcroft's upcoming changes will …

Add INIT_BOUNDARY_EXTRAP parameter and function to allow ALE boundary extrapolation behaviour to differ at initialisation and in model run

---

src/parameterizations/vertical/MOM_CVMix_KPP.F90

Added the option of using rotationally symmetric expressions in KPP_smooth_BLD().  This is enabled by setting the new runtime parameter KPP%ANSWER_DATE to a value of 20240501 or higher.  For now the default is to use the older symmetry-breaking expressions, but the default value for KPP%ANSWER_DATE should be revised to use DEFAULT_ANSWER_DATE.  By default, all answers are bitwise identical but there is a new entry in some MOM_parameter_doc files.

+Rotationally symmetric KPP_smooth_BLD option

---

src/core/MOM_CoriolisAdv.F90
src/diagnostics/MOM_diagnostics.F90
src/parameterizations/lateral/MOM_Zanna_Bolton.F90

Refactored 10 diagnostics related to terms in the kinetic energy budgets and 2 diagnostics of nonlinear relative-vorticity related accelerations to respect rotational symmetry.  These diagnostics are mathematically equivalent but will change at roundoff due to changes in the order of arithmetic.  Only diagnostics are changed, and the solutions themselves are bitwise identical in all cases.

(*)Revise 13 diagnostics for rotational symmetry

---

src/parameterizations/lateral/MOM_thickness_diffuse.F90

Fix several bugs when `MEKE_GM_SRC_ALT` is True, including corrections to two dimensional rescaling factors, and optionally fix a bug that sets a limit only on positive slopes but leaving negative slopes unlimited.  This bug is corrected when the new runtime parameter `MEKE_GM_SRC_ALT_SLOPE_BUG` is false.  Additionally there is a new runtime parameter `MEKE_GM_SRC_ANSWER_DATE` that specifies the use of rotationally symmetric expressions for `PE_release_h` when it is set to 20240601 or higher, but it should be noted that rotational symmetry also requires that `MEKE_GM_SRC_ALT_SLOPE_BUG` is false.  Four new checksum calls were also added to verify the correctness of the calculation of `MEKE%GM_src` when `MEKE_GM_SRC_ALT` and `DEBUG` are true.  By default, all answers are bitwise identical …

+Fix multiple bugs when MEKE_GM_SRC_ALT is True

---

src/parameterizations/vertical/MOM_set_viscosity.F90

Vector u2_bg(:) was introduced in commit 6c44c5f38 (Fix for using tidal amplitude in determining the BBL thickness, 2024-04-04). It replaces a scalar in set_viscous_ML, but was not defined, causing crashes. This commit sets the values of u2_bg(:) to match those given given in set_viscous_BBL.

Added missing values for vector u2_bg(:) within set_viscous_ML

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90

This commit includes a series of changes that get MOM6 to reproduce across processor counts, layouts and restarts when USE_QG_LEITH_VISC = True and also to implement related changes to the QG Leith code to be consistent with not making the Boussinesq approximation when in non-Boussinesq mode.  These changes include:
- Adding a `thermo_var_ptrs` and a timestep argument to to the interfaces to `horizontal_viscosity()`, `initialize_dyn_split_RK2()` and `initialize_dyn_split_RK2b()`
- Correcting a bug in the powers of `H_subroundoff` in the denominators of some expressions for the effective thicknesses associated with interfaces, thereby correcting some dimensionally inconsistencies in these expressions
- Adding the new publicly visible routine `calc_QG_slopes()`
- Adding the arguments …

+(*)Fix USE_QG_LEITH_VISC = True reproducibility

---

src/parameterizations/lateral/MOM_self_attr_load.F90

For reasons not entirely clear, deallocation of the RK2 control structure caused a segmentation fault when compiled by Nvidia.  A deeper investigation suggested that the compiler was attempting to deallocate a nullified pointer during automatic cleanup of RK2->SAL->sht.  Apparently deallocation of a NULL pointer is an error (even though free() is not supposed to care).
By redefining `sht` as an allocatable component rather than a local component of the SAL_CS instance, it seemed to satisfy the compiler that nothing was needed and the error went away.
There are still some lingering questions behind the cause of the segfault, but for now I am going to put this under "compiler bug".
This patch also initializes some of the logical flags in the SAL_CS type.  This is possibly unnecessary, but …

SAL: Explicitly allocate sht variable in SAL_CS

---

.testing/tools/parse_perf.py

This patch fixes errors in the parser of perf output.  Previously, each record was assumed to be separated by spaces, but this failed for more generic records (usually from C++) which included signatures (such as `f(a, b)`) or templates (`f<a, b>`).  Nested constructed were also possible.
This is fixed by introducing a simple tokenizer which extracts <, (, and whitespace from the output , then rebuilds the records by combining any whitespace which appears inside of delimiters.
This patch should hopefully resolve the CI errors in GitHub Actions.

Testing: Correct perf parsing of C++ output

---

.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml

- MacOS builds have been failing recently
- This is apparently due to a recent break in gfortran 14.1 which is now incompatible with FMS2
- A proposed (@marshallward) workaround is to revert to FMS1 for the MacOS builds, which indeed appears to work
- This commit sets FRAMEWORK=fms1 and FMS_COMMIT=2019.01.03 only for the MacOS builds
- It leaves all other builds on FMS2

Use FMS1 for MacOS builds

---

src/core/MOM_density_integrals.F90
src/parameterizations/vertical/MOM_vert_friction.F90

Adds a maximum number of iterations to the subroutine `find_depth_of_pressure_in_cell` in `MOM_density_integrals`
This subroutine is called in `MOM_state_initialization` and calculates the pressure within a cell to determine where the ice shelf should be positioned vertically. It takes a z tolerance (controlled by the runtime parameter `TRIM_IC_Z_TOLERANCE`) and then iterates until the pressure anomaly from the reconstruction in the cell to the target pressure is sufficiently small (controlled by pa_tol = g x rho x z_tol).
Currently, the model just has a while loop for the tolerance, which means if the `TRIM_IC_Z_TOLERANCE` is set to a very small number e.g.1e-15, and convergence cannot be achieved due to numerical precision, then the model will hang and continue looping forever. 
I added …

Add maximum number of iterations in find_depth_of_pressure_in_cell

---

src/diagnostics/MOM_obsolete_params.F90
src/framework/MOM_diag_mediator.F90

- For runs using grid space diagnostic axes, the registration of the cell centered axes fails with symmetric memory with a runtime error when posting diagnostics. This patch fixes this error.

Fix error in diagnostic axis registration for grid space axes

---

src/framework/MOM_horizontal_regridding.F90

Within fill_miss_2d, there are 2 sets of masked values used for remapping - masked values in neighboring points in arbitrary units (with names like "south") and the updated valid mask with values of 0 or 1 (with names like "gs").  At one point in the code, the former were being used where the latter were more appropriate.  This commit changes this to help with the understandability of the code.  All answers and output are bitwise identical.

Better variables for updated masks in fill_miss_2d

---

src/tracer/MOM_tracer_advect.F90

- Fix logic so tracer advection diagnostics are computed correctly for symmetric memory mode
- Addresses Issue #646

Bugfix for tracer advection diagnostic in symmetric memory mode

---

.github/workflows/macos-regression.yml
.github/workflows/macos-stencil.yml
.testing/Makefile
.testing/README.rst

This patch fixes ``FMS_COMMIT`` and ``FMS_URL`` so that they are properly exported to ``ac/deps/Makefile`` and used in the .testing FMS build.
It also removes any references to the FRAMEWORK flag, which is no longer needed to identify the FMS API.

CI: Fix FMS_COMMIT, remove FRAMEWORK

---

src/initialization/MOM_tracer_initialization_from_Z.F90

Corrected an argument to the call to `ALE_remap_scalar()` when `h_is_in_Z_units` is true in `MOM_initialize_tracer_from_Z()`, to avoid the problems documented in github.com/NOAA-GFDL/MOM6/issues/589.  A comment was also added explaining the logic of what is going on in this fork of the code.  This commit will change answers with some generic tracers that are initialized from a Z-space input file, restoring them to previous values that worked previously (before about Feb. 1, 2024 on dev/gfdl) in Boussinesq configurations without dimensional consistency testing, but in a new form that does pass the dimensional consistency testing for depths and thicknesses.  All answers are bitwise identical in any cases that do not use generic tracers.

*Fix ALE_remap_scalar call with h_in_Z_units

---

config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
config_src/drivers/solo_driver/MOM_driver.F90
config_src/infra/FMS1/MOM_diag_manager_infra.F90
config_src/infra/FMS2/MOM_diag_manager_infra.F90
src/framework/MOM_diag_mediator.F90

These are updates needed for the new diag manager (FMS2024.01+):
- Adds `diag_send_complete_infra` and `diag_manager_set_time_end_infra` subroutines to the FMS1/FMS2 infra. 
The subroutines in FMS1 do nothing and are there just for backwards compatibility.
- `diag_send_complete_infra` is called inside `disable_averaging`
- `diag_manager_set_time_end_infra` is called in the solo and ice_solo_drivers (without this, the solo tests will crash with an error like `diag_manager_set_time_end must be called before diag_send_complete`)

Add diag send complete calls

---

src/initialization/MOM_state_initialization.F90
src/user/soliton_initialization.F90

Refactored the code in `soliton_initialization.F90` to more accurately reflect the nondimensionalization that was applied in developing this test case.  This change includes reading in the maximum depth and beta, and using them to calculate the equatorial deformation radius and the external gravity wave speed.  The references to the papers describing the test case in the module were added to the doxygen comments describing the routines in this module.   This commit also includes adding comments documenting the nature and units of all the internal variables in this module.  There are two new arguments each (`param_file` and `just_read`) to `soliton_initialize_thickness()` and `soliton_initialize_velocity()` to accommodate these changes, bringing them into line with the interfaces for other …

(*)Refactor and document soliton_initialization

---

src/core/MOM_forcing_type.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/tracer/pseudo_salt_tracer.F90

This series of two pull requests replicates the calculation of the surface salt flux used with KPP inside of the pseudo-salt column physics code, correcting a mismatch in the dimensional rescaling between salinities and the pseudo-salt tracer.  Having eliminated the only instance where `fluxes%KPP_salt_flux` was being used, this element was removed from the forcing type, and 5 allocatable elements of `diabatic_CS` were replaced with simple arrays in the 3 routines where they are used.  This change could reduce the high-water memory footprint of the model when KPP is in use, and it simplifies inter-module dependencies.  This pull request partially addresses the issue noted at github.com/mom-ocean/MOM6/issues/1226.  All answers are bitwise identical when no dimensional rescaling is being …

+(*)Pseudo-salt tracer flux fix with KPP

---

src/core/MOM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_interface_heights.F90
src/core/MOM_variables.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_CVMix_ddiff.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/tracer/MOM_hor_bnd_diffusion.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/MOM_tracer_flow_control.F90
src/tracer/MOM_tracer_hor_diff.F90
src/tracer/ideal_age_example.F90

This PR includes a series of commits that standardize how the depth of active surface mixing is passed around and how and where that depth is converted into a thickness when in non-Boussinesq mode.  This is accomplished via calls to the new routine `convert_MLD_to_ML_thickness()` and by accessing the new variable `visc%h_ML` in the various places where the mixed layer thickness is used. Because this variable may be used from a previous timestep, it has been added to the restart file in cases where it is in use.  These changes make the use of the surface boundary layer thickness much more consistent with how it is calculated when in non-Boussinesq mode, without changing anything in Boussinesq mode.
This PR includes a number of changes to public interfaces.  There is a new argument to …

+*More consistent non-Boussinesq mixed layer thicknesses

---

config_src/drivers/FMS_cap/ocean_model_MOM.F90
src/core/MOM.F90
src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_state.F90

Added variables for the accumulated iceberg mass and heat flux due to calving from ice shelves (flux through the static ice front). These variables will be passed to the coupler and SIS2/iceberg module to initialize bergs.
See related changes in:
Coupler: https://github.com/alex-huth/FMScoupler/commit/3e80bbc
SIS2: https://github.com/NOAA-GFDL/SIS2/pull/209
It was easiest to tag a few other changes onto this PR as well:
-fixed the ice-shelf SMB override
-reorganized ice-shelf post data calls so that they do not strictly have to be called at multiples of the ice velocity time step.
-Added ice-shelf scalar diagnostics related to volume-above-floatation and surface/basal mass balance.

Flux through static ice-shelf to icebergs/new diagnostics

---

src/user/Idealized_Hurricane.F90

Refactored the Idealized_Hurricane module to clean up strange or unscaled variable units and eliminate dimensional scaling factors with the latest answer dates.  This includes the introduction of 18 new runtime variables to replace hard-coded dimensional constants and two runtime logical flags to reproduce existing bugs.  An inconsistency in the sign convention for the distance from the hurricane center with idealized_hurricane_wind_forcing in (the probably not yet used) single column mode was also corrected. Also added descriptions with units for all the variables in this module.  By default or with appropriate parameter settings all answers are bitwise identical.

+(*)Refactor Idealize_Hurricane

---

src/parameterizations/vertical/MOM_kappa_shear.F90

Add a parameter (beta) to rescale the distance to the nearest solid boundary that is used within calculation of kappa shear. While rescaling this value is nonphysical, this adjustment can be thought of as not allowing shear instabilities to grow up to the full distance to the nearest boundary because of other turbulent processes which would disrupt their growth. By default, this parameter is 1.0 and should not impact existing solutions. 
This modification to the kappa shear parameterization was developed by Wei Cheng, Al Hermann, and Vivek Seelanki and tested in simulations of the North East Pacific regional model developed by Liz Drenkard. In the Bering Sea, which is shallow and has strong tides, the well observed cold pool and seasonal stratification were being disrupted because of …

Add rescaling parameter to kappa shear

---

src/framework/MOM_horizontal_regridding.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90

This PR addresses issue #644 by introducing a logic change when calling `get_external_field_info` in `MOM_interp_infra.F90`. Since the axis, dimension, and missing value information for nudging are time-independent, there is no need to read this information from the NetCDF file at every time step when using `FMS2`. With this fix, the runtime of nudging experiments with `FMS1` and `FMS2` are now comparable:
FMS2 with new fix one year run:
```
hits          tmin          tmax          tavg          tstd  tfrac grain pemin pemax
Total runtime                            1   9425.780744   9425.898127   9425.820889      0.036968  1.000     0     0  1645
(Ocean sponges)                      17520    445.104094   1139.163714    580.620263     63.931211  0.062    31     0  1645
```
FMS1 with new …

Refactor Axis Information Handling for Improved Performance in ocean_sponge

---

src/user/MOM_wave_interface.F90

Added the new runtime parameters `ROBUST_STOKES_PGF` and `LA_MISALIGNMENT_BUG` to allow for the selection of Stokes pressure gradient force calculations that work properly in the limit of vanishingly thin layers and to correct a sign error in the calculations of the misalignment between the waves and shears in the Langmuir number calculations when `LA_MISALIGNMENT` is true.  By default, all answers are bitwise identical, but as these options are not yet widely used it might make sense to move aggressively to obsolete the previous code once more extensive testing has take place.  There will be new entries in the MOM_parameter_doc files for some cases, but there are not yet any such cases in the MOM-examples regression suite.

+Add ROBUST_STOKES_PGF and LA_MISALIGNMENT_BUG

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90

-Updated subroutines to account for re-entrant boundary conditions and non-symmetric grids
-Optimized the SSA CG algorithm to eliminate unneeded loops and pass_var calls 
-Added a missing pass_var call to fix a bug that was sometimes preventing reproducibility on different PE layouts
-Updated initialization so that when ice-shelf velocity data is loaded, it is immediately adjusted to agree with assigned BCs
-Changed some ice-shelf mass units from mass per grid area (incorrect) to mass per ice-shelf area (correct). This only affected partially-full cells at the ice front, which typically only arise when allowing ice-shelf fronts to move.

Ice-shelf dynamics updates

---

config_src/drivers/ice_solo_driver/atmos_ocean_fluxes.F90
config_src/drivers/ice_solo_driver/ice_shelf_driver.F90
config_src/drivers/solo_driver/atmos_ocean_fluxes.F90
src/core/MOM_variables.F90
src/framework/MOM_coms.F90
src/framework/MOM_coupler_types.F90
src/framework/MOM_intrinsic_functions.F90
src/framework/MOM_random.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/user/RGC_initialization.F90

This commit improves the documentation of the remaining real variables with previously undocumented units in the framework directory, with some other similar unit documentation improvements in other files.  Units were added to comments describing about 79 real variables in 4 framework modules, `atmos_ocean_fluxes.F90` for 2 drivers, `MOM_oda_incupd.F90`, `MOM_oda_driver.F90` and `MOM_variables.F90`.
The variable `nhours_incupd` in `initialize_oda_incupd()` was renamed to `incupd_timescale` and the factor of 3600.0 that converts `ODA_INCUPD_NHOURS` from hours into seconds was moved from where this variable is used into the scale argument where it is set to help document the meaning and units of this variable as simply and clearly as possible.
The unused variable `smb` was removed from …

Add units to the descriptions of 79 variables

---

src/core/MOM_isopycnal_slopes.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90

Corrected the sign convention used for the `neutral_slope_x` and `neutral_slope_y` diagnostics in cases when there is not an equation of state being used to match the usual sign convention (interfaces sloping up to the east or north is a positive slope) and to match what is done when an equation of state is being used to calculate neutral density slopes rather than just basing the slopes of the interfaces alone.  The same correction was made to the `slope_x` and `slope_y` arguments returned from `calc_isoneutral_slopes()`, and self-consistent changes were made to the overturning streamfunction calculations in `thickness_diffuse_full()`.
In addition, there were some corrections made to the documentation at the end of MOM_thickness_diffuse.F90, and the `calculate_slopes` argument to …

+(*)Fix sign of neutral_slope_x diagnostic with no EOS

---

src/tracer/MOM_tracer_Z_init.F90

Added the new runtime parameter `DETERMINE_TEMP_CONVERGENCE_BUG` to avoid using layout-dependent tests for temperature and salinity tolerances to determine when to stop iterating in `determine_temperature()`.  Also added logic that correctly determines when iterations can be stopped because no further changes occur, and rearranged to loops to avoid revisiting layers that have converged.
Because the default tolerances for the temperature, salinity and density changes are set to be the same and the partial derivatives of density with temperature and salinity are less than 1 in the MKS units used here for a realistic equation of state of seawater, this bug does not impact any of the existing regression test cases, but this bug could lead to non-reproducibility with non-default values.
This …

+Add DETERMINE_TEMP_CONVERGENCE_BUG parameter

---

src/parameterizations/vertical/MOM_diabatic_driver.F90

Corrected the field being posted for the `Kd_interface` diagnostic inside of `diabatic_ALE()` to be the minimum of `Kd_heat` and `Kd_salt`, which includes the contributions from ePBL, but excluding any extra double-diffusive mixing, making it analogous to the diagnostic that is currently being posted from `layered_diabatic()` or `diabatic_ALE_legacy()`.  `Diabatic_ALE()` is used when `USE_REGRIDDING=True` and `USE_LEGACY_DIABATIC_DRIVER=False`, in which case a diagnostic will change, correcting the issue noted at NOAA-GFDL/MOM6/issues/398.  All solutions are bitwise identical.

(*)Fix Kd_interface diagnostic in newer diabatic_ALE

---

src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/core/MOM_variables.F90
src/framework/MOM_coupler_types.F90
src/ice_shelf/MOM_ice_shelf.F90
src/tracer/DOME_tracer.F90
src/tracer/ISOMIP_tracer.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/advection_test_tracer.F90
src/tracer/boundary_impulse_tracer.F90
src/tracer/dye_example.F90
src/tracer/ideal_age_example.F90
src/tracer/oil_tracer.F90
src/tracer/tracer_example.F90

This commit adds the necessary information about the turns of the model grid relative to the (unrotated) `coupler_type` data fields that are inside of the `forcing` type and `surface_state` type and are used with passive tracers, so that certain tracer packages can now be used with rotated grids.  The previous version had problems where the model would not run when `ROTATE_INTEX = True` and the CFCs (and probably other passive tracers) were being used, as noted at NOAA-GFDL/MOM6/issues/621.  These problems have now been fixed.
There are new calls to `coupler_type_spawn()` in `allocate_forcing_by_ref()` and `allocate_surface_state()` that manage the creation of the `coupler_2d_bt_types` for unrotated types based on information from their rotated counterparts.
There is a new optional …

+(*)Fix rotation of coupler_type variables

---

src/core/MOM.F90
src/core/MOM_barotropic.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/parameterizations/lateral/MOM_hor_visc.F90

This PR aims to solve the problem that `visc_rem` term is incorrectly applied in the split mode. There are three issues identified:
1. `vertvisc_remnant`() call at the end of the predictor stage uses `dt_pred`, while the calculations `visc_rem_[uv]` is applied to (`continuity`() and `btstep`()) use `dt`. This results in undercounting (baroclinic) vertical viscous term in the barotropic solver.
2. In barotropic solver, `wt_[uv]`, a function of `visc_rem_[uv]`, is not normalized by the vertically-integrated vertical viscosity. This results in doublecounting (baroclinic) vertical viscous term in the barotropic solver.
3. In continuity solver, velocity cell thickness BT_cont%`h_[uv]` from `zonal_flux_thickness`() and `meridional_flux_thickness`() calls are multiplied by `visc_rem_[uv]` if …

Fixes for visc_rem in split mode

---

src/core/MOM_PressureForce_FV.F90

Refactored `PressureForce_FV_nonBouss()` and `PressureForce_FV_Bouss()` to use more 3-dimensional arrays in preparation for the changes that we are expecting from Claire Yung to reduce the pressure gradient errors in ice shelf cavities.  These anticipated changes will involve selecting an internal interface at which to define the shape of the interfaces with depth when there is an ice shelf, rather than assuming that the top surface pressure varies linearly with depth between the two top corners.  In `PressureForce_FV_nonBouss()`, this refactoring includes turning `za`, `intx_za` and `inty_za` into 3-d arrays and moving the code setting these arrays outside of the k-loop setting the pressure gradient forces. Changes in `PressureForce_FV_Bouss()` are analogous but involve turning 7 arrays …

Refactor PressureForce_FV before ice shelf fixes

---

src/ALE/MOM_regridding.F90

It was noted in NOAA-GFDL/MOM6/issues/491 that the call to `initialize_regridding()` for diagnostics gives a segmentation fault when the maximum depth of the ocean is greater than 9250 m unless `DIAG_COORD_DEF_Z` is explicitly set.  This commit fixes this problem by (1) adding an extra layer to the bottom of the hard-coded WOA09 list of diagnostic depths when the ocean is deeper than the 9250 m maximum depth in that file, and (2) changing the default behavior for diagnostic grids to be be uniform when the maximum ocean depth is deeper than 9250 m, for which WOA09 is no longer likely to be a convenient choice.  With this change, MOM6 no longer has segmentation faults for the configuration described in NOAA-GFDL/MOM6/issues/491.  All solutions are bitwise identical, but some z-space …

(*)Avoid diagnostic seg fault in a 10km deep ocean

---

src/parameterizations/lateral/MOM_hor_visc.F90

Added the new runtime parameter `BACKSCATTER_UNDERBOUND` that can be set to false to avoid a potential source of numerical instabilities from excessively large biharmonic viscosities due to overly generous bounds where there are negative Laplacian viscosities due to backscatter parameterizations.  Setting this to true reproduces the previous solutions, while setting it to false treats negative and zero Laplacian viscosities the same way when bounding the biharmonic viscosity.  When the Laplacian viscosities are all non-negative, the value of `BACKSCATTER_UNDERBOUND` makes no difference.  The default is true for historical reasons, but this option probably should be set to false to avoid certain numerical instabilities from the horizontal viscosities.  By default, all answers are bitwise …

+Add BACKSCATTER_UNDERBOUND

---

src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/parameterizations/lateral/MOM_hor_visc.F90

Corrected the computation of FrictWork in MOM_hor_visc.F90. The domain integral of FrictWork should exactly match the total energy dissipation rate by horizontal viscosity (KE_horvisc) computed in MOM_diagnostics. However, the previous version of  FrictWork (realized by setting FRICTWORK_BUG = True, which is the default) overestimates the magnitude of total KE_horvisc.  The new code (realized by setting FRICTWORK_BUG = False) fixes this issue by using the thickness flux rather than the velocity to compute FrictWork. The figure below shows a comparison between the domain integral of KE_horvisc (blue solid line) and FrictWork (dashed lines). Orange and green dashed lines show the FrictWork computed by the old and new codes, respectively. The new code computes the FrictWork that exactly …

Correct the computation of FrictWork in MOM_hor_visc

---

.testing/tools/parse_perf.py

Bracket counter for `<..>` was correct but `(..)` was broken, it was counting `(` but not `)`.  I can only presume that such cases were very rare.
This patch fixes the closed parenthesis count.

CI: parse_perf.py bugfix

---

.testing/Makefile
config_src/drivers/timing_tests/time_MOM_remapping.F90
config_src/drivers/unit_tests/test_MOM_remapping.F90
src/ALE/MOM_ALE.F90
src/ALE/MOM_remapping.F90
src/core/MOM_open_boundary.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_wave_speed.F90
src/framework/MOM_diag_mediator.F90
src/framework/MOM_diag_remap.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/tracer/MOM_hor_bnd_diffusion.F90
src/tracer/MOM_neutral_diffusion.F90

This a significant refactor of the core remapping algorithm, with a patch at the end that fixes a bug for some situations mostly encountered when initializing from observations.
Commits include:
- Cleaning up compiler warnings in MOM_remapping.F90
- Added stand alone drivers for timing and unit tests of MOM_remapping.F90
- Re-factor of unit_tests() in MOM_remapping.F90 to use helper class making cleaner/shorter
- New tests of parts of `remap_via_sub_cells()` algorithm, added as `remap_via_sub_cells()` was deconstructed into three functions: intersect_src_tgt_grids(), remap_src_to_sub_grid(), and remap_sub_to_tgt_grid()
- The fix for reconstructions in top/bottom layers implemented as an alternative version of the remap_src_to_sub_grid() function (not an flag or optional argument)
- Nine …

Remapping refactor and fix for mismatched ocean depths

---

config_src/external/drifters/MOM_particles_types.F90
config_src/infra/FMS1/MOM_diag_manager_infra.F90
config_src/infra/FMS2/MOM_diag_manager_infra.F90
src/framework/MOM_coms.F90
src/framework/MOM_intrinsic_functions.F90
src/framework/MOM_restart.F90

This patch replaces references to kind=8 with the corresponding Fortran kind identifiers as defined in iso_fortran_env.
Although these are widely equal to 8, there are a number of compilers (notably NAG, also others) which set it to a different value.
This improves the portability of the code (albeit in a rather minor way).

Replace kind=8 with iso_fortran_env kinds

---

src/parameterizations/vertical/MOM_diabatic_driver.F90

Five fields associated with KPP were previously initialized during allocation (using `source=0.`).  It was found that the allocations were unnecessary, and the fields were redefined as local variables within functions, without the initialization to zero.
Although the uninitialized points were masked and unused in the rest of the model, they were still able to change the checksums and were being reported as regressions.  This patch restores the original checksums by re-implementing the zero initialization.
Thanks to Bob Hallberg (@Hallberg-NOAA) for diagnosing this issue.

Re-initialize fields within KPP

---

config_src/external/GFDL_ocean_BGC/generic_tracer_utils.F90
src/tracer/MOM_generic_tracer.F90
src/tracer/MOM_tracer_flow_control.F90

Revise `MOM_generic_tracer_min_max()` and `array_global_min_max()` to fix several problems that had previously been noted, and to make the location arguments optional, reflecting that they are optional in the calling routine.  This requires a revision to the order of arguments to `MOM_generic_tracer_min_max()`. The interface to `array_global_min_max()` was extensively revised and simplified to replace several previous arguments with a single new `ocean_grid_type` argument, to make the location arguments optional, and add an optional `unscale` argument.
This commit fixes a number of problems that had previously been noted with `array_global_min_max()`, including that:
(1) It actually returns the global minimum and maximum values of the tracer;
(2) It gives a position that is independent of …

+(*)Fix problems with generic_tracer_min_max

---

.testing/Makefile
ac/configure.ac
ac/deps/configure.fms.ac

Certain compilers would expect values passed to ld which cannot be passed to the C compiler.  This caused the autoconf C configuration to fail, since it uses to CC for linking rather than LD.
Since we never use the C compiler for linking, this is not something we need to be concerned about, and the LDFLAGS is disabled when testing the C compiler.
This is only a concern when using certain GPU-related flags in the Nvidia compiler, and is only a problem for libraries with a significant amount of C code, such as FMS.

Autoconf: Disable LDFLAGS for C testing

---

src/parameterizations/vertical/MOM_ALE_sponge.F90

Corrected a bug in `rotate_ALE_sponge()` that incorrectly set the starting number of sponge fields that prevented any cases with fixed ALE sponges from working when `ROTATE_INDEX = true`, even if `INDEX_TURNS = 0`.  With this correction, the code is now working (and giving identical answers) with rotation enabled for cases with fixed ALE_sponges.  All answers are bitwise identical in cases that worked before, but some cases that did not work at all are now working both with and without grid rotation.

(*)Fix bug in rotate_ALE_sponge for fixed sponges

---

src/framework/MOM_horizontal_regridding.F90

Renamed the optional `scale` argument to `myStats()` to `unscale`, mirroring the
recent additions of `unscale` arguments to the various `chksum()` routines.  This included changes to 6 calls to `myStats()` in the two `horiz_interp_and_extrap_tracer()` routines.  Although `myStats()` is public, it really is only used in MOM_horizontal_regridding in the main version of MOM6, apart from a single call in `MOM_initialize_tracer_from_Z()` that does not use the optional `(un)scale` argument, so rather than adding a second optional argument, this case seemed to be safe enough to rename the argument in place.  If there were any unanticipated problems with this argument name change, they would be manifest in code that does not compile.  All answers are bitwise identical, but an optional argument …

+Renamed myStats scale argument to unscale

---

src/parameterizations/vertical/MOM_set_diffusivity.F90

Added a refactored version of the code in `add_LOTW_BBL_diffusivity()` that is more accurate by avoiding a subtraction of two large numbers to determine the distance from the surface and more reproducible by avoiding the use of the Fortran `sum()` function.  This new version of the code is mathematically equivalent to the original, and it is selected by setting the new runtime parameter `LOTW_BBL_ANSWER_DATE` to be greater than 20240630.  This probably could have been done reusing the existing parameter `SET_DIFF_ANSWER_DATE`, but this would have meant answer changes for some cases that set this to a high value.  By default the original code is used, but the default should be changed later to follow the value of `DEFAULT_ANSWER_DATE`.  By default, all answers are bitwise identical but …

+Add a better variant of add_LOTW_BBL_diffusivity

---

src/core/MOM_checksum_packages.F90
src/core/MOM_forcing_type.F90
src/diagnostics/MOM_spatial_means.F90
src/framework/MOM_checksums.F90

Added an optional `unscale` argument to 16 checksum and 9 spatial_mean or spatial_integral routines.  These are synonymous with the existing optional scale arguments to these routines, and if both are provided, the new `unscale` arguments take precedence.
All this is done to come up with a more systematic nomenclature for the various scaling and unscaling arguments, so that the factors passed to them will follow a more regular pattern.  With this change, the `scale=` argument to a `get_param()` or `read_data()` call will take the opposite setting to the `unscale=` argument used in a checksum call.  For example, for a velocity, these arguments would be `scale=US%m_s_to_L_T` and `unscale=US%L_T_to_m_s`, but the reverse values of `scale=US%L_T_to_m_s` and `unscale=US%m_s_to_L_T` would only …

+Add optional unscale arguments to checksums

---

src/tracer/MOM_neutral_diffusion.F90

Cleaned up the error messages when there are fatal problems in `interpolate_for_nondim_position()` in the MOM_neutral_diffusion module to explicitly give an indications of all the problems.  These had previously triggered fatal errors (or should have), but had less explicit or incorrect error messages in some cases, so all solutions and behavior are identical in any cases that worked previously.

Better error messages in interpolate_for_nondim_position

---

src/core/MOM_barotropic.F90
src/core/MOM_isopycnal_slopes.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_spatial_means.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/user/RGC_initialization.F90

Corrected the case of the do-loop index variable in 10 places in 6 files, initialized two whole diagnostic arrays to 0 instead of having shared loops initializing u- and v-point arrays, and shortened two loops initializing pressures to the size that is actually used in the corresponding equation of state calls.  With these changes, there are no i- or j- loops with extents that are inconsistent with the stagger-based index case convention used throughout the MOM6 code.  All answers are bitwise identical in all cases.

Correct 10 do-loop index cases

---

src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Wright.F90

This commit restores the effectiveness of the runtime parameter `USE_WRIGHT_2ND_DERIV_BUG` in determining whether a bug is corrected in the calculation of two of the second derivative terms returned by `calculate_density_second_derivs_elem()` with the "WRIGHT" equation of state, recreating the behavior (and answers) that are currently on the main branch of MOM6.  To do this, it adds and calls the new routine `set_params_buggy_Wright()` when appropriate, and adds the new element "three" to the `buggy_Wright_EOS` type. When the bug is fixed, `buggy_Wright_EOS%three = 3`, but `...%three = 2` to recreate the bug.  This commit does change answers for cases using the "WRIGHT" equation of state and one of the "USE_STANLEY_..." parameterizations from those on the dev/gfdl branch of MOM6, but in …

(*)+Restore USE_WRIGHT_2ND_DERIV_BUG functionality

---

src/core/MOM.F90

Moved a check for whether to initialize an uninitialized `visc%h_ML` field from `visc%MLD` outside of the test for the value of `CS%mixedlayer_restart`.  This change will prevent answer changes between code versions for certain cases that initialize from a restart file, use the `surface_state%melt_potential` field and have `MLE_USE_PBL_MLD = True` but also have `MIXEDLAYER_RESTRAT = False`.  This commit corrects a very specific oversight that was introduced when the roles of `visc%h_ML` and `visc%MLD` were separated, and it can change answers (reverting them to answers from older versions of the main branch of MOM6) in very specific cases where MOM6 is initialized from a restart file from an older versions of the code, including the 5x5-degree test case in the dev/emc regression suite.

*Possibly initialize h_ML from MLD in restart file

---

src/core/MOM.F90
src/core/MOM_checksum_packages.F90

Added checksum calls for the `melt_potential`, `ocean_mass`, `ocean_heat` and `ocean_salt` elements of the surface state in `MOM_surface_chksum()` if these fields are allocated for more comprehensive debugging.  Also added the symmetric optional argument to the call to `MOM_surface_chksum()` from `extract_surface_state()` so that all of the surface velocity values that could contribute to the ocean surface velocities that are seen by the coupler are checksummed.  All solutions are bitwise identical, but there are enhancements to the MOM6 debugging capabilities.

Improve MOM_surface_chksum

---

src/tracer/MOM_generic_tracer.F90

This PR is related to another [PR](https://github.com/NOAA-GFDL/ocean_BGC/pull/34) made in the NOAA-GFDL/ocean_BGC repo.
In the past, setting `DO_GEOTHERMAL = True` was necessary for COBALT to function correctly. Failure to enable geothermal heating will lead to segmentation faults if someone turned it off accidently.
We have now made `internal_heat` an [optional argument](https://github.com/NOAA-GFDL/ocean_BGC/blob/048ac6811232c006a6ff2d63f7063911822ba3ef/generic_tracers/generic_COBALT.F90#L6455) in the `generic_COBALT_update_from_source`. The `if(present())` [check](https://github.com/NOAA-GFDL/ocean_BGC/blob/048ac6811232c006a6ff2d63f7063911822ba3ef/generic_tracers/generic_COBALT.F90#L7856) will determine if `internal_heating` is a null pointer. However, in the unit conversion case, the …

In generic_tracer_source call, perform unit conversion for internal heat only when it is applicable

---

src/core/MOM.F90
src/core/MOM_checksum_packages.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/framework/MOM_diag_mediator.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/tracer/MOM_tracer_advect.F90

This incorporates the patches to gfdl-to-main_2024-05-31 made after the original branch was made on dev/gfdl.
The last commit, merging main into main-to-gfdl_2024-05-31 resolves conflicts in src/core/MOM_checksum_packages.F90.
c3349ab37 Merge branch 'main' into main-to-gfdl_2024-05-31
aacb90989 Merge pull request #1631 from NOAA-GFDL/gfdl-to-main-2024-05-31
ee686c8d7 Improve MOM_surface_chksum
40f472123 *Possibly initialize h_ML from MLD in restart file
00f7d231a (*)+Restore USE_WRIGHT_2ND_DERIV_BUG functionality
3fac1c5ab Allow incorrect PPM:H3 tracer advection stencil
ac2b642f4 Re-initialize fields within KPP
b4ae2b752 Disable nonrepro FMAs in convex BBL solver
0578393e4 Remove diag_send_complete from disable_averaging

Main to gfdl 2024 05 31

---

src/tracer/MOM_tracer_advect.F90

Two logicals can be unset when using PLM in MOM_tracer_advect.F90. This was leading to random behavior in the doc files because a third parameter was only being read and logged depending on whether PLM:H3 was used.
This commit sets `CS%usePPM = .false.` and `CS%useHuynh = .false.` before processing the run-time parameter.

Set logicals in MOM_tracer_advect.F90

---

src/ALE/MOM_remapping.F90

This PR addresses a `\todo` added in NOAA-GFDL/MOM6#662, namely that the functions remap_via_sub_cells() and remap_via_sub_cells_om4() could, and should, be moved up into remapping_core_h(), as well as into the obsolete remapping_core_w().
In that PR, the function remap_via_sub_cells() had been modularized into three other functions, and the near-duplicate remap_via_sub_cells_om4(), called two of the same functions as well as an out-of-date version of the third function.
Since the remapping_core_h() function calls is already brief, calling one function in addition to remap_via_sub_cells(), and since remap_via_sub_cells() is only called from remapping_core_*(), we can remove a level of call-tree depth depth by copying remap_via_sub_grid() into reampping_core_h() and removing the unused …

Removes remap_via_sub_cells(), moving code into remapping_core_h()

---

src/ALE/MOM_regridding.F90

Adds two new coordinates, designed for z*-space diagnostics:
- WOA09INT is a more consistent set of z-level thicknesses for use with WOA09. The current WOA09 coordinate matches the WOA09 depths for most levels, but six differ by necessity. The new WOA09INT coordinate uses the depths as interface positions, so has one less level, and thus requires interpolation (mid-point averaging) of WOA09 data for direct comparison, but is more consistent.
- WOA23INT takes the same approach as WOA09INT but uses the finer-newer WOA grid. For OM4, with a maximum depth of 6500m, WOA23INT yields 111 levels of output, instead of 34 for WOA09INT or 35 for WOA09.

New diagnostic grids for comparing with WOA

---

src/core/MOM_isopycnal_slopes.F90

- In the previous version, GxSpV_u and GxSpV_v were only set when use_EOS was true
- Now initialize GxSpV_u and GxSpV_v to be G_Rho0

Fix bugs in setting GxSpV_u and GxSpV_v in MOM_isopycnal_slopes

---

src/diagnostics/MOM_spatial_means.F90
src/diagnostics/MOM_sum_output.F90
src/tracer/MOM_generic_tracer.F90

This PR comprises two commits that first move the publicly visible routine `array_global_min_max()` from MOM_generic_tracer to MOM_spatial_means, and then optionally use this routine to determine the maximum and minimum values of temperature and salinity and the locations of their extrema and write them to stdout.  The new runtime parameters `WRITE_TRACER_MIN_MAX` and `WRITE_TRACER_MIN_MAX_LOC` determine what is written, as the global reductions in array_global_min_max might be an unnecessary computational expense in some cases.  All solutions are bitwise identical, but the location of a publicly visible routine has changed, there can be some changes to the output to stdout and there will be new entries in the MOM_parameter_doc.debugging files.
- …

+Move array_global_min_max() and use it for Temperature & Salinity

---

src/parameterizations/lateral/MOM_mixed_layer_restrat.F90

- Without this, one can see the tile boundaries in the uhml and vhml fields.

* Fix for spatially varying Bodner fields.

---

src/parameterizations/lateral/MOM_hor_visc.F90

Changes within the last 9 months turned off the computation of vorticity in MOM_hor_visc.F90 which is required as an input to MOM_Zanna_Bolton.F90 module, and so the ZB20 parameterization was working incorrectly. Here I resolved it with another one if statement.

Restore computation of vorticity for ZB20

---

ac/makedep

This patch makes some changes to makedep output:
* Compile commands now end with the source code, rather than the include files.  This makes it easier to see which file is being compiled.
* Blank lines were added inbetween object file rules.
* Redundant spaces from absent include flags is now removed.
Also some minor PEP8-like cleanups:
* Some (but not all) 79+ character lines were reduced or split.
* Some (but not all) single-letter variables were renamed.
* A bad error handler for missing macros was fixed.
Nothing particularly major here, but build output should be more readable.

Makedep output cleanup and PEP8 fixes

---

src/core/MOM.F90
src/core/MOM_interface_heights.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

For better readibility, the PR is split into 3 commits: the first deals with bugfixes and improvements relative to the internal tides energy (changes answers) while the second deals with refactoring of debugging infra. The third commit introduces the TKE loss to diffusivity part.
1st part:
(*)bugfixes for internal tides
- TKE_itidal_input values are set to zero where it is not applied to
the model so that diagnostics are consistent
- removed useless halo updates
- diagnose energy loss terms as dE/dt instead of equivalent loss rate
to properly close energy budget
- tot_vel_btTide2 was already a velocity squared, no need to square again
- Froude loss term was not properly initialized
- add missing halo updates for internal tide speed
- compute residual/critical slopes loss only where it has …

diffusivities from internal tides ray tracing algo

---

src/core/MOM_barotropic.F90
src/parameterizations/lateral/MOM_streaming_filter.F90

In the MOM_streaming_filter module, a system of two coupled ODEs is configured as a streaming band-pass filter that takes the broadband model output as the input and returns the filtered signal at a user specified tidal frequency as the output. It is capable of detecting the instantaneous tidal signals while the model is running, and can be used to impose frequency-dependent wave drag or to de-tide model output. An example of filtering the M2 and K1 barotropic velocities is provided in the MOM_barotropic module.

Streaming filter

---

.testing/tc1/MOM_input
.testing/tc2/MOM_input
.testing/tc4/MOM_input
src/core/MOM_PressureForce_FV.F90
src/core/MOM_density_integrals.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_Wright.F90
src/equation_of_state/MOM_EOS_Wright_full.F90
src/equation_of_state/MOM_EOS_Wright_red.F90
src/equation_of_state/MOM_EOS_linear.F90

This series of 10 commits adds options for correcting the pressure gradient forces in ice-shelf cavities or massive sea-ice or icebergs.  These changes include adding the option of using mass-weighting when interpolating the sub-gridscale distributions of temperature and salinity under ice, analogously to what is done near the topography, along with several different options for changing which interface has an distribution of pressure as a function of depth (or vice-versa in non-Boussinesq mode) that can be determined from a combination of hydrostatic changes and a linear large-scale gradient.  The new runtime parameters that impact this behavior include `CORRECTION_INTX_PA`, `RESET_INTXPA_INTEGRAL`, `RESET_INTXPA_H_NONVANISHED` and `MASS_WEIGHT_IN_PRESSURE_GRADIENT_TOP`.  There are both …

+(*)Pressure gradient corrections under ice shelves

---

.github/actions/ubuntu-setup/action.yml
.testing/Makefile
config_src/drivers/FMS_cap/ocean_model_MOM.F90
src/equation_of_state/MOM_EOS.F90
src/framework/MOM_domains.F90
src/framework/posix.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/tracer/ideal_age_example.F90

This PR contains several commits to ensure Fortran 2023 compliance.
Most changes are related to missing or redundant commas in I/O statements.  Others were related to the ordering of input-dependent arguments in functions.
This should help improve support on other compilers which have more strict I/O syntax requirements.  It will also help prepare us to turn on additional warnings and improve the overall testing of the model.
It also includes modifications to the GitHub CI to provide F2018 testing.  (Unfortunately our compiler of choice is a bit out of day and cannot yet provide 2023 compliance testing.)

Fortran 2023 compliance and testing

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90

This PR adds area-integrated scalar diagnostics for ice sheets that may be requested separately for Antarctica-only (where lat<0) and/or Greenland-only (where lat>0).  The previous approach, which simply integrated quantities over all ice area present in the domain, is still available for polar stereographic or idealized simulations.
This PR also adds a few ice-sheet parameters: MIN_H_SHELF, MIN_BASAL_TRACTION, MAX_SURFACE_SLOPE, and MIN_ICE_VISC. These parameters temporarily adjust the ice thickness, basal traction, surface slope, and ice viscosity, respectively, during the ice dynamics (shallow shelf approximation) solve, which helps avoid unrealistically large ice speeds (e.g. in coastal areas with very steep topography).
Also added ice-shelf surface slopes (sx_shelf, sy_shelf) as …

Separate scalar diagnostics for each ice sheet + parameters to control ice-sheet velocities

---

src/core/MOM.F90

bigthetao refers the the uppercase greek letter theta used for conservative temperature. Salinity so uses the roman alphabet and a bigso is ambiguous as many papers use S for salinity hence absso seems like the most unambiguous.

change CMOR names, fixes #709

---

.testing/Makefile

When WORKSPACE is specified, the recursive make for target code (for regression tests) does not work properly. This PR fixes this bug.

Fix .testing Makefile with WORKSPACE

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90

New diagnostics for ice-shelf flux divergence, strain-rates, deviatoric stresses, speed, surface slope magnitude, and driving stress magnitude. Fixed some misleading units for variables related to ice viscosity

Ice-shelf diagnostics

---

src/core/MOM.F90
src/core/MOM_porous_barriers.F90
src/core/MOM_variables.F90
src/initialization/MOM_fixed_initialization.F90

This PR fixes a minor bug in porous barriers module.
It may change answers for some very rare cases in barotropic runs. For an example I tested with barotropic tides, the answer is unchanged at bit level. 
(PS: this is a redo of PR #726, leaving out the default parameter change part).

Fix a bug in porous barriers

---

.gitlab-ci.yml

This fixes the gitlab pipelines, post c5 OS update:
- Changed gitlab runner to the mom6-account on gaea
- Added gitlab variable MOM6_RUN_JOB_DURATION to control the allowed run duration during bad days for the system. Defaults to 15:00 (15 mins)
- Added FC=ftn MPIFC=ftn CC=cc environment vars when invoking make in .testing
A successful pipeline following these changes can be seen at https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/25306

Switch runner and allow for more run time

---

config_src/drivers/timing_tests/time_MOM_remapping.F90
src/ALE/MOM_ALE.F90
src/ALE/MOM_remapping.F90
src/ALE/P1M_functions.F90
src/ALE/P3M_functions.F90
src/ALE/PLM_functions.F90
src/ALE/PPM_functions.F90
src/ALE/PQM_functions.F90
src/ALE/coord_hycom.F90
src/ALE/coord_rho.F90
src/ALE/regrid_edge_values.F90
src/ALE/regrid_interp.F90
src/ALE/remapping_attic.F90
src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_wave_speed.F90
src/framework/MOM_diag_remap.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90
src/tracer/MOM_hor_bnd_diffusion.F90

Eliminated the previously optional `h_neglect` and `h_neglect_edge` arguments to `remapping_core_h()` and `remapping_core_w()`, and added optional `h_neglect` and `h_neglect_edge` arguments to `initialize_remapping()` for storage in the remapping control structures.  The `answer_date`, `h_neglect` and `h_neglect_edge` arguments to `ALE_remap_scalar()` were also eliminated, as they are no longer used. The new routine `open_boundary_setup_vert()` was added to manage these changes. A new `verticalGrid_type` argument was added to `wave_speed_init()`.
The `h_neglect` argument to 29 routines was made non-optional, because there is no way to provide a consistent hard-coded default for a dimensional parameter. The (mostly low-level) routines where this change to a non-optional `h_neglect` was …

+Eliminated h_neglect argument to remapping_core_h

---

.testing/tc0/MOM_input
.testing/tc1/MOM_input
.testing/tc2/MOM_input
.testing/tc3/MOM_input
.testing/tc4/MOM_input
src/core/MOM.F90

This change should result in some speed up. 
MOM_input in test cases are changed accordingly.

Change default of USE_POROUS_BARRIER to false

---

src/diagnostics/MOM_PointAccel.F90

This patch replaces the `CS%[uv]_file < 0` checks with `CS%[uv]_file == -1`.  FMS1 returns negative file handles for missing or otherwise error-prone files, but the FMS2 IO framework relies on `newunit=` to autogenerate handle IDs, which are always negative and cannot be used with checks for negative values.
The check is replaced with equality with -1.  `newunit` is guaranteed to never return -1 for a valid file, so this is a valid check for a missing file.  It also lets us continue to use -1 as the initial (unopened) value.
Behavior is compatible with `mpp_open()` output, so this can also be used with the FMS1 API.
A better solution would be to introduce some validation function which is defined by each API, but there is not yet any need for such sophistication.

Set truncation file handle check from < 0 to == -1

---

.codecov.yml
.github/workflows/coverage.yml
.testing/Makefile

This commit contains two changes to gcov report generation and codecov upload.
1. Separation of the file parser unit tests from the others was causing them to be exluded from report.cov.unit.
This patch reworks the rules to replace MOM_file_parser_tests.F90.gcov with driver code, build/unit/test_%.F90.gcov.
This does assume at all drivers will look the same (test_*.F90) but that part can be reworked if it ever becomes a problem in the future.
Thanks to @adcroft for multiple suggestions in this PR.
2. Github appears to internally store all its repositories in another directory with the name as the repo (in this case MOM6/).
Normally this is hidden to everyone, but it was causing some confusion with the codecov upload tool, and was unable to match the source code to the .gcov report.
The …

CI: Consolidate unit test rules, codecov pathfix

---

src/core/MOM_barotropic.F90
src/core/MOM_continuity_PPM.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90

This PR reverts a bug fix introduced previously https://github.com/NOAA-GFDL/MOM6/pull/639, related to using `visc_rem_[uv]` for vertical weights `frhat[uv]` in barotropic solver. The change (controlled by runtime parameter `VISC_REM_CONT_HVEL_FIX`),  was demonstrated to be incorrect. Therefore the "fix" is unnecessary.
The other two bug fixes introduced at the same time are still valid. Corresponding runtime parameter names are changed with a suffix "_bug" for consistency. 
This PR introduces no answer changes. There are changes in runtime parameters with one removal and three name/description changes.

Revert a bug fix with visc_rem in continuity solver

---

src/core/MOM_open_boundary.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/ocean_data_assim/MOM_oda_incupd.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90

Most modules that use remapping have their own parameter e.g. Z_INIT_REMAPPING_SCHEME.  However, OBC, ODA and SPONGE currently sliently use the primary ALE REMAPPING_SCHEME parameter.
Added logged parameters OBC_REMAPPING_SCHEME, ODA_REMAPPING_SCHEME and SPONGE_REMAPPING_SCHEME to allow customization.  All take REMAPPING_SCHEME as their default to maintain compatibility.
For ODA, also added ODA_REMAPPING_USE_OM4_SUBCELLS that takes REMAPPING_USE_OM4_SUBCELLS as its default to maintain compatibility, and ODA_BOUNDARY_EXTRAP that takes BOUNDARY_EXTRAPOLATION as its default to maintain compatibility.  Note that BOUNDARY_EXTRAPOLATION is a bug, it should have been REMAP_BOUNDARY_EXTRAP, but the former remains the default for compatibility.
For SPONGE, also added SPONGE_BOUNDARY_EXTRAP that …

Add REMAPPING_SCHEME for OBC, ODA and SPONGE

---

src/core/MOM.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_MEKE_types.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/MOM_tracer_hor_diff.F90

This commit added an surface quasigeostrophy (SQG) vertical structure (sqg_struct) in Varmix (MOM_lateral_mixing_coeffs) to provide a vertical profile for eddy diffusivities. The SQG vertical structure and its parameterization is given by Zhang et al. (2024): https://journals.ametsoc.org/view/journals/phoc/54/6/JPO-D-23-0203.1.xml. 
Also, the vertical structure of all eddy diffusivities/viscosities, including khth, khtr, kh, and kdgl90, are reorganized in Varmix. Two vertical structures are optional for each diffusivity: the equivalent barotropic (ebt_struct) and surface quasigeostrophy (sqg_struct) structures. For example, if one wants to use the SQG structure for the thickness diffusivity Khth, they can set KHTH_USE_SQG_STRUCT=True. 
Detailed changes are summarized below:
- …

Add SQG vertical structure to eddy diffusivities

---

src/diagnostics/MOM_sum_output.F90

This PR fixes a bug with subroutine `write_energy` when using a DT<2. 
Otherwise, the energy outputs could be written at wrong time steps with extremely small time stepping size. 
The reason was that time type divide is essentially a floor. So in the line in question, dt_force/2 = 0 if dt_force<2. And energy is always written at the following time step, rather than when day==CS%write_energy_time.
The patch is a bit ugly. 
1. I believe both `dt_force/2` and  `<=` (rather than <) are necessary for round-off considerations.
2. There is no real divide for `time_type` and a real number. (operator(//) is between `time_type` variables and operator(*) is for a `time_type` and an integer)

Bug fix for subroutine `write_energy` when `DT`<2

---

src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90

The subroutine `compute_global_grid_integrals()` appeared in both the `MOM_state_initialization` and `MOM_shared_initialization` modules, but was only being called from the latter.   This commit removes the extra copy in `MOM_state_initialization`.  It also removes some unnecessary parentheses in the copy that is being retained, in part to facilitate the review of this commit. All answers are bitwise identical, and no publicly visible interfaces are altered.

Remove extra copy of compute_global_grid_integrals

---

src/core/MOM_open_boundary.F90
src/diagnostics/MOM_diagnostics.F90
src/framework/MOM_diag_mediator.F90
src/initialization/MOM_state_initialization.F90
src/initialization/MOM_tracer_initialization_from_Z.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/vertical/MOM_ALE_sponge.F90
src/tracer/MOM_hor_bnd_diffusion.F90
src/tracer/MOM_neutral_diffusion.F90

In addition to REMAPPING_USE_OM4_SUBCELLS, for ALE remapping, there are several parameters of the form XXX_REMAPPING_USE_OM4_SUBCELLS, where XXX identifies the target, and they all currently default to True.
To simplify setting them all to False, which is recommended, the defaults for the XXX versions is changed to the value of REMAPPING_USE_OM4_SUBCELLS.
Answers are only changed if REMAPPING_USE_OM4_SUBCELLS is set to False and the default (now False) is used for one or more of the other parameters. In such cases the original behaviour can be recovered by explicitly setting the other parameters to True.

Make REMAPPING_USE_OM4_SUBCELLS the default

---

src/core/MOM_open_boundary.F90
src/framework/MOM_document.F90
src/framework/MOM_file_parser.F90
src/initialization/MOM_state_initialization.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/user/user_change_diffusivity.F90

The `default=` optional argument to get_param() only provides a uniform value to initialize an array of reals. This commit adds the optional `defaults=` argument that must have the same length as the `values` argument.
I've also added a few instances of this optional argument:
- by adding the `initialize_thickness_param()` procedure, selected by `THICKNESS_CONFIG = "param"`. The procedure was based on the "uniform" method, and uses the parameter `THICKNESS_INIT_VALUES` which defaults to uniform values derived from `MAXIMUM_DEPTH`
- the setting of MLD_EN_VALS in MOM_diabatic_driver.F90 which was previously using a work around to set defaults to 25, 2500, 250000 J/m2.
- two vectors of 4 values in user/user_change_diffusivity.F90
For super repos there will be some doc file changes, but no …

Adds a vector of default values to get_param_real_array()

---

config_src/infra/FMS1/MOM_constants.F90
config_src/infra/FMS2/MOM_constants.F90

Two latent heat constants are imported directly from FMS, which is built independently of MOM6.  Previously, it was a safe assumption that both would be built with double precision, but this is no longer the case since FMS now supports both single and double precision.  This could cause conflicts with mixed-precision builds.
This patch converts the values from FMS-precision to MOM-precision.
Single->double should not affect reproducibility since every single-precision number can be exactly represented in double precision. Double->single could affect reproducibility, but this is not an issue since MOM6 does not run in single precision.

FMS API: Convert real kind of constants

---

src/diagnostics/MOM_harmonic_analysis.F90

Important bug fix:
1) The Cholesky decomposition was operating on entries below the main diagonal of FtF, whereas in the accumulator of FtF, only entries along and above the main diagonal were calculated. In this revision, I modified HA_accum_FtF so that entries below the main diagonal are accumulated instead.
2) In the accumulator of FtSSH, the first entry for the mean (zero frequency) is moved out of the loop over different tidal constituents, so that it is not accumulated multiple times within a single time step.

Inline harmonic analysis

---

src/core/MOM_barotropic.F90
src/core/MOM_open_boundary.F90
src/parameterizations/lateral/MOM_streaming_filter.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90

Tidal frequencies are always angular frequencies to simplify applying sine and cosine.  These have MKS units [rad s-1] but they are all currently listed as [s-1].
Updated dOxygen comments for variables, e.g. [T-1 ~> s-1] becomes [rad T-1 ~> rad s-1].  Updated get_param units. e.g. units="s-1" becomes units="rad s-1".
No answers are changed, but the logged parameter units are different.
There are frequencies in MOM_internal_tides.F90 but these have not been updated because they may be specified incorrectly.  They are used as if they are [T-1] but they are calculated as 2PI/period [rad T-1].
real, allocatable, dimension(:) :: frequency  !< The frequency of each band [T-1 ~> s-1].
real    :: period             ! A tidal period read from namelist [T ~> s]
! The periods of the tidal …

Tidal angular frequency has units [rad s-1]

---

config_src/drivers/solo_driver/MOM_surface_forcing.F90
src/user/Idealized_Hurricane.F90

Changed the code to issue a fatal error message when `WIND_CONFIG = "SCM_ideal_hurr"`, with the message including instructions on how to recover mathematically equivalent solutions, and eliminated the subroutine `SCM_idealized_hurricane_wind_forcing()` from the `Idealized_hurricane` module.  The ocean_only MOM_parameter_doc files have also been modified to reflect that "SCM_ideal_hurr" is no longer a valid setting for `WIND_CONFIG`.   All answers are bitwise identical in any cases that run, but some cases may fail during initialization with instructions on how to fix them.

+*Obsolete WIND_CONFIG = "SCM_ideal_hurr"

---

src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90

This series of six commits adds the option to do energetically consistent bottom boundary layer mixing with the new routine `ePBL_BBL_column()`. `ePBL_BBL_column()` is closely based on the surface-focused ePBL mixing in `ePBL_column()`, but without adding convective instability driven mixing or mean-TKE driven mixing to avoid possible double-counting.  This new option is enabled by setting the new runtime parameter `EPBL_BBL_EFFIC` to be positive.  The changes include the addition of a new mandatory `vertvisc_type` argument to the publicly visible routine `energetic_PBL()`.  If both EPBL_BBL_EFFIC and BBL_EFFIC are set to positive values, there is a risk of double-counting, but this case is not being trapped for now.  The changes that actually adds `ePBL_BBL_column()` is in the fifth of …

*+Add ePBL bottom boundary layer mixing option

---

src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_coms.F90
src/framework/MOM_unit_scaling.F90
src/initialization/MOM_shared_initialization.F90
src/tracer/MOM_offline_main.F90
src/user/tidal_bay_initialization.F90

This PR consists of a series of 4 commits that adds optional `unscale` arguments to the publicly visible `reproducing_sum()` interfaces in `MOM_coms`, and then uses them to refactor the routines in `MOM_sum_output` and 4 other modules to eliminate about 19 dimensional rescaling factors, and to work more broadly in rescaled variables for dimensional consistency testing.
All answers are bitwise identical, but there are new optional arguments to 2 publicly visible interfaces and a new element in the transparent unit_scale_type.  This commits in this PR include:
- NOAA-GFDL/MOM6@193c83ec9 Use reproducing_sum with unscale in 5 places
- NOAA-GFDL/MOM6@842bbf4da Work in rescaled units in write_energy
- NOAA-GFDL/MOM6@4d255baf7 +Add RZL2_to_kg element to unit_scale_type
- NOAA-GFDL/MOM6@9e7e16523 …

+Add and use optional unscale args to reproducing_sum

---

src/core/MOM.F90

This PR contains three minor fixes related to SSH diagnostics and checks, which address the following issues:
1. An indexing error with 1D nominal coordinates 
2. Preventing extreme surface message being trigger with Angstrom=0.0
3. Bug with dynamical step averaged diagnostics `SSH_inst`
All answers are bitwise identical, but a diagnostics that has been unlikely used is recovered.

Bug fixes for sea surface height related diagnostics/checks

---

src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

- The present code only tests BBL_EFFIC when deciding whether to set the bottom TKE and ustar, but this means they are all zero when EPBL_BBL_EFFIC is non-zero and BBL_EFFIC is zero.
- Adds logic to also check EPBL_BBL_EFFIC, thereby allowing non-zero ustar and TKE for EPBL_BBL_EFFIC>0.0
- Fixed BBL_TKE diagnostic in EPBL that was not populated.
- Will change answers when EPBL_BBL_EFFIC>0.0, but won't change answers in any of our existing configurations.

Updates to use EPBL_BBL_EFFIC

---

src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

Several fixes to the candidate PR to main:
* Fixed bugs due to introduction of MEKE biharmonic friction
* Restored performance due to new visc-limit flag in MEKE FrictWork.  This is now applied separately, and only if `EY24_EBT_BR` is enabled.
* Restored performance due to multiple damped MEKE diagnostics.  Nearly every calculation is now conditional.
* Bugfix to an internal tide control struct declaration
There is also a commit to restore answers related to MEKE backscatter, but this is still under some discussion.  I'm leaving it in for now, but we may change or remove this one if NCAR approves.
This needs review from one of the following:
* @wendazhang33
* @elizabethYankovsky
Further testing will eventually be needed from @alperaltuntas and @jiandewang but this can wait until Wenda …

GFDL->main PR regression and bug fixes

---

src/framework/MOM_coms.F90

CEFI's tidal regression tests fail after #767. After debugging, we found that the issue was due to a missing `descale=1.0` setting in the `reproducing_sum_3d` function. This PR addresses the bug. It does not affect any existing baselines.

Forget to set descale in reproducing_sum_3d

---

src/parameterizations/vertical/MOM_ALE_sponge.F90

Corrected the units and conversion factor in `init_ALE_sponge_diags()` for the various `sp_tendency_...` diagnostics.  Previously they had only been correct for the tendencies of nondimensional quantities.  The code also now stores the scaling factor that is set in `set_up_ALE_sponge_field_fixed()` for later use in registering the sponge tendency diagnostics.  Several instances of unusual spacing around semicolons in `MOM_ALE_sponge.F90` were also standardized.  The documented units and conversion factors for some diagnostics were corrected, but all solutions are bitwise identical.

Fix ALE_sponge tendency diagnostic units

---

src/framework/MOM_diag_remap.F90

Refactored the `horizontally_average_field()` routine in `MOM_diag_remap` to work in rescaled units by making use of the `unscale` arguments to the `reproducing_sum()` routines.  A total of 9 rescaling variables were converted into a pair of `unscale` arguments.  All answers and diagnostics are bitwise identical, and no interfaces are changed.

Refactor horizontally_average_field

---

src/framework/MOM_horizontal_regridding.F90
src/initialization/MOM_state_initialization.F90

Refactored the `homogenize_field()` routine in MOM_horizontal_regridding to make use of the `unscale` argument to `reproducing_sum()`, and revised its interface to make it more nearly consistent with the interface to `homogenize_field_t()` in `MOM_forcing_type`.
The interface changes include revising the order of the arguments, making the weight argument options, replacing the scale argument with an optional `tmp_scale` argument that is the inverse of the previous `scale`, and making the default for the use of reproducing sums to be true when the `answer_date` argument is absent. The two `homogenize_field` routines now give equivalent behavior when none of the optional arguments to `homogenize_field()` are absent.  The `homogenize_field()` calls in `MOM_temp_salt_initialize_from_Z()` and …

+Refactor homogenize_field and revise its interface

---

src/ice_shelf/MOM_ice_shelf.F90
src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

This PR consists of two commits that refactor the MOM6 ice_shelf code to work more extensively in rescaled variables, and to do the unscaling of all diagnostics by the conversions arguments to `register_diag_field()` or `register_scalar_field()` calls.
These change make use of the recently added unscale argument to `reproducing_sum()`. Several missing unit conversion factors for rates of mass change were also added, and the diagnostics have now been verified to pass dimensional consistency testing.  After these commits, all of the dimensional scaling factors for diagnostics in the ice_shelf code occur via conversion factors that are immediately adjacent to the declaration of the units of those diagnostics, facilitating comparison for consistency.
The specific changes included refactoring …

Refactor ice shelf rescaling and diagnostic calcs

---

config_src/drivers/solo_driver/MOM_surface_forcing.F90

Refactored the solo_driver version of `MOM_surface_forcing` to modify how the time levels to read from forcing files, with a series of 11 new runtime parameters (`WIND_FILE_DAYS_PER_RECORD`, etc.) giving the user to specify how many days each time record spans (for positive values) or the number of time records in the file per day (for negative values).  If these parameters are set to 31, the month returned by the FMS `get_date()` function sets the time level.  If they are set to 0 (the default) the previous behavior is obtained, in which the time level is determined from the number of records in the file.  To always take the first record in the file, set these parameters to large values (greater than 1000000 will always work, but in practice smaller values do the same thing).  By default …

Users set solo driver forcing time records per day

---

src/core/MOM_PressureForce_FV.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_open_boundary.F90
src/parameterizations/lateral/MOM_self_attr_load.F90
src/parameterizations/lateral/MOM_spherical_harmonics.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90

This PR adds the option of using bottom pressure anomaly to calculate self-attraction and loading (SAL). Currently, sea surface height (SSH) is used for SAL, which is only accurate for barotropic flows. (SSH is the barotropic equivalent of bottom pressure anomaly.) 
* A new runtime parameter `SAL_USE_BPA` is added to use bottom pressure anomaly. The option requires an input file for long term mean reference bottom pressure. 
* The reference bottom pressure field is stored with `SAL_CS` rather than `PressureForce_FV_CS`. 
* When `SAL_USE_BPA` is true, total bottom pressure field is used as the input for subroutine `calc_SAL`(), the reference pressure is subtracted within the subroutine.
* SAL calculation in Boussinesq mode is refactored in order to
1. calculate SAL after bottom pressure is …

Use bottom pressure anomaly for self-attraction and loading

---

src/parameterizations/vertical/MOM_opacity.F90

Refactored `MOM_opacity` to replace hard-coded dimensional parameters for the Manizza and Morel opacity fits with run-time parameters.  By default, these parameters are set to the previous hard-coded values, using the recently added defaults argument to `get_param_real_array()`.  The bounds of the frequency band label arrays with the `MANIZZA_05` opacity scheme were also corrected when `PEN_SW_NBANDS > 3`, but it would not by typical to use so many bands for no purpose and these labeling arrays (`optics%min_wavelength_band` and `optics%max_wavelength_band`) do not appear to be used anywhere.  In addition, the unused publicly visible routines `opacity_manizza()` and `opacity_morel()` were eliminated or made private.  All answers are bitwise identical, but there are new entries in some …

+Refactor MOM_opacity to replace hard-coded params

---

src/parameterizations/lateral/MOM_internal_tides.F90

This allows to change the decay time for different latitudes, tidal harmonic and vertical mode, like is done in Fig 4 of
[de Lavergne 2019](https://www.sciencedirect.com/science/article/pii/S1463500318302890)

implement spatially varying decay rates for internal tides leakage

---

src/core/MOM_density_integrals.F90
src/initialization/MOM_state_initialization.F90

This commit adds a new parameter `FRAC_DP_AT_POS_NEGATIVE_P_BUGFIX` and associated bug fix. This bug occurs when `TRIM_IC_FOR_P_SURF` pressure initialisation is used for ice shelf, whilst in Boussinesq mode and a nonlinear equation of state. The subroutine `trim_for_ice` calls `cut_off_column_top`. This routine in Boussinesq mode calls `find_depth_of_pressure_in_cell` in `MOM_density_integrals.F90`. This subsequently calls the function `frac_dp_at_pos` which calls the density equation of state based on given salinity, temperature and depth, which is incorrectly converted into pressure by z position (which is negative) multiplied by g and rho0, therefore resulting in a large negative pressure. The bug results in incorrect densities from the equation of state and therefore an imperfect …

Add ice shelf pressure initialisation bug fix

---

src/diagnostics/MOM_obsolete_params.F90
src/framework/MOM_file_parser.F90

Added the new optional argument `old_name` to the 8 `get_param()` routines. This new capability allows for an archaic parameter name to be specified and for appropriate warnings encouraging the user to migrate to using the new name while still setting the parameter as intended, or error messages in the case of inconsistent setting via the archaic name and the correct name.  The logging inside of the `MOM_parameter_doc` files only uses the correct parameter name.
Also added the new optional argument set to the 8 `read_param()` routines, to indicate whether a parameter has been found and successfully set.  The new set argument is now being used in `read_param()` calls in `obsolete_int()`, `obsolete_real()`, `obsolete_char()` and `obsolete_logical()`.  `Obsolete_logical()` in particular was …

+Add the optional argument old_name to get_param()

---

src/core/MOM_grid.F90
src/core/MOM_transcribe_grid.F90
src/framework/MOM_dyn_horgrid.F90
src/ice_shelf/MOM_ice_shelf_diag_mediator.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_shared_initialization.F90
src/initialization/MOM_state_initialization.F90
src/user/DOME_initialization.F90
src/user/ISOMIP_initialization.F90
src/user/Idealized_Hurricane.F90
src/user/Kelvin_initialization.F90
src/user/Rossby_front_2d_initialization.F90
src/user/soliton_initialization.F90

Add the new element `grid_unit_to_L` to the `ocean_grid_type` and the`dyn_horgrid_type`, which can be used to convert the units of the `G%geoLat` and `G%geoLon` variables to rescaled horizontal distance units ([L ~> m]) when they are Cartesian coordinates.  When Cartesian coordinates are not in use, `G%grid_unit_to_L` is set to 0.
This new element of the grid type is used to test for inconsistent grids or to eliminate rescaling variables in `set_rotation_beta_plane()`, `initialize_velocity_circular()`, `DOME_initialize_topography()`, `DOME_initialize_sponges()`, `DOME_set_OBC_data()`, `ISOMIP_initialize_topography()`, `idealized_hurricane_wind_forcing()`, `Kelvin_set_OBC_data()`, `Rossby_front_initialize_velocity()`, `soliton_initialize_thickness()`, and `soliton_initialize_velocity()`. …

+Add grid_unit_to_L to the ocean_grid_type

---

src/core/MOM_grid.F90
src/core/MOM_transcribe_grid.F90
src/framework/MOM_dyn_horgrid.F90
src/initialization/MOM_grid_initialize.F90

Remove the unused element `Rad_Earth` from `ocean_grid_type` and `dyn_horgrid_type`. The dimensionally rescaled equivalent element `G%Rad_Earth_L` is extensively used, and it will continue to exist.  `G%Rad_Earth_L` was introduced in November 27, 2021 as a dimensionally rescaled version of `G%Rad_Earth`, while the unscaled version was retained because at the time, the `Rad_Earth` element of the `dyn_horgrid_type` is also used in SIS2.  However, SIS2 has not used `G%Rad_Earth` since December 23, 2021, so after 3 years we can now safely remove this unused element.
Any cases on other branches that might be impacted by this change will not compile.  All answers are bitwise identical, but there is one less element in two transparent types.

+Remove dyn_horgrid_type%Rad_Earth and ocean_grid_type%Rad_Earth

---

src/core/MOM_open_boundary.F90
src/diagnostics/MOM_harmonic_analysis.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90

This commit fixes a few (potential) inconsistencies between open boundary tidal forcing and astronomical tidal forcing.
1. There was an inconsistency in the code that the nodal modulation can be calculated in OBC tidal forcing but not in the astronomical tidal forcing. This commit fixes this bug so that nodal modulation is applied to both forcings.
2. In the previous version of MOM_open_boundary.F90, a different set of tidal parameters can be set for open boundary tidal forcing, leading to potential inconsistency with astronomical tidal forcing. This commit obsoletes those for open boundary tidal forcing.
3. Another important bug fix is that the equilibrium phase is added to the SAL term, which was missing in the original code.

Nodal modulation

---

src/parameterizations/lateral/MOM_hor_visc.F90

Added the missing `conversion` arguments to the `register_diag_field()` calls for the recently added diagnostics `BS_coeff_h` and `BS_coeff_q`.  All answers are bitwise identical, but two diagnostics will have corrected dimensional rescaling when `EY24_EBT_BS = True`.

Correct unit conversion for BS_coeff_h and BS_coeff_q diagnostics

---

src/parameterizations/lateral/MOM_MEKE.F90

Refactored `predict_MEKE()` to include two missing dimensional rescaling factors and correct a third and to clearly indicate the units and the nature of the variables where they are being used, in coordination with Andrew Shao.  Some white spacing around semicolons in the same MOM_MEKE file was also modified to follow the patterns used elsewhere in the MOM6 code.  All answers are bitwise identical in cases that do not use dimensional rescaling.

Fix dimensional rescaling in predict_MEKE

---

src/core/MOM.F90
src/core/MOM_forcing_type.F90
src/core/MOM_grid.F90
src/diagnostics/MOM_spatial_means.F90
src/framework/MOM_dyn_horgrid.F90
src/ice_shelf/MOM_ice_shelf.F90
src/initialization/MOM_shared_initialization.F90

This PR consists of two commits that use the `unscale` arguments to `reproducing_sums()` to refactor the 6 global area mean functions (`global_area_mean()`, `global_area_mean_u()`, `global_area_mean_v()`, `global_layer_mean()`, `global_volume_mean()` and `adjust_area_mean_to_zero()`) and to revise the scaling of the returned values from the two global integral
routines(`Global_area_integral()` and `global_mass_integral()`), and then to use this revised capability to work exclusively with rescaled diagnostics of the surface fluxes.
When `global_area_integral()` and `global_mass_integral()` are called with a `tmp_scale` argument, now it is not just the variable that is being integrated that is returned in rescaled units, but also the area or mass, whereas previously it was only the variable …

+Refactor spatial means and rescale some global integrals

---

src/parameterizations/lateral/MOM_MEKE.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

Corrected the internal tide rescaling arguments so that some of the debugging variables have units that are consistent with their documented units.  This involved changing the `scale` arguments to `global_area_integral()` to `tmp_scale` arguments in 8 places so that the units of the output retain the scaling of the input variable.  The multiplication by the reverse of the scaling factor was also added to 4 debugging output messages.
The documented units of internal wave energies in 5 register_restart_field calls were previously given as "m3 s-2" in non-Boussinesq mode and "J m-2" in Boussinesq mode when the reverse was actually true.  This has now been corrected.
Also replaced the `scale` argument to 35 `chksum()` calls with the equivalent but preferred `unscale` argument, following the …

Fix rescaling of internal tide debugging code

---

src/ALE/MOM_ALE.F90
src/ALE/MOM_regridding.F90
src/core/MOM_barotropic.F90
src/core/MOM_checksum_packages.F90
src/core/MOM_density_integrals.F90
src/core/MOM_interface_heights.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_wave_speed.F90
src/ocean_data_assim/MOM_oda_driver.F90
src/parameterizations/lateral/MOM_MEKE_types.F90
src/parameterizations/lateral/MOM_hor_visc.F90
src/parameterizations/lateral/MOM_internal_tides.F90
src/parameterizations/lateral/MOM_lateral_mixing_coeffs.F90
src/parameterizations/lateral/MOM_mixed_layer_restrat.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_CVMix_ddiff.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_vert_friction.F90
src/tracer/DOME_tracer.F90
src/tracer/MOM_CFC_cap.F90
src/tracer/MOM_OCMIP2_CFC.F90
src/tracer/MOM_offline_aux.F90
src/tracer/MOM_offline_main.F90
src/tracer/MOM_tracer_types.F90
src/user/Rossby_front_2d_initialization.F90

Corrected the descriptions of the units of about 113 variables spread across 30 files.  These were either inconsistent unit descriptions or descriptions using a non-standard syntax.  Only comments are changed, and all answers are bitwise identical.

Corrected many unit descriptions in comments

---

src/parameterizations/lateral/MOM_spherical_harmonics.F90

Refactored the `spherical_harmonics_forward()` routine in `MOM_spherical_harmonics` to work in rescaled units by making use of the `unscale` arguments to `reproducing_sum()`.  A total of 4 rescaling variables were moved into `unscale` arguments, and a block of code that restores the scaling of the output variables was eliminated.  The comments describing the units of several variables in this module were made more explicit.  The two temporary arrays that store un-summed contributions to the transforms were also moved out of the control structure and made into local variables in the `spherical_harmonics_forward()` routine to allow for the reuse of that memory.  All answers and diagnostics are bitwise identical, and no interfaces are changed.

Refactor spherical_harmonics_forward

---

src/ice_shelf/MOM_ice_shelf_dynamics.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90

Changed the rescaling of 6 ice shelf variables to cancel out common conversion factors that appear in several expressions.
The `C_basal_friction` argument to `initialize_ice_C_basal_friction()` is now in partially rescaled units, reflecting the portion that does not cancel out fractional-power units from a power law fit with an arbitrary power.  The `C_basal_friction` array in `ice_shelf_dyn_CS` and the `C_friction` variable in `initialize_ice_C_basal_friction()` were similarly rescaled.  There are new scale factors in a `get_param()` call and a `MOM_read_data()` call and a conversion factor in a `register_restart_field()` call that reflect these changes.
The `KE_tot` and `mass_tot` variables in `write_ice_shelf_energy()`, are kept in scaled units until they are written.
The internal …

Rescale 6 ice shelf variables

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/STALE_mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
src/core/MOM_forcing_type.F90
src/core/MOM_variables.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90

This PR consists of 4 commits that make the purpose and nature of two fields in the forcing type and the `vertvisc_type` clearer, and also adds the option to use the dissipated tidal energy supplied via the fluxes type to drive mixing in `ePBL_BBL_column()`.  It also corrects a bug in the energy being used in the recently added ePBL BBL mixing.
`Visc%TKE_BBL` has been revised to `visc%BBL_meanKE_loss` to reflect that this array contains the mean kinetic energy that has been extracted by the bottom drag, and that the efficiency has not yet been applied.  The units were also changed from `[R Z3 T-3 ~> W m-2]` to `[R Z L2 T-3 ~> W m-2]`, with the extra conversion factors to translate from the units of mean kinetic energy to those of turbulent kinetic energy folded into …

+(*)Clarify turbulent energetics and add EPBL_BBL_TIDAL_EFFIC

---

src/core/MOM_verticalGrid.F90
src/diagnostics/MOM_diagnose_MLD.F90
src/parameterizations/lateral/MOM_thickness_diffuse.F90
src/parameterizations/vertical/MOM_CVMix_KPP.F90
src/parameterizations/vertical/MOM_CVMix_conv.F90
src/parameterizations/vertical/MOM_CVMix_shear.F90
src/parameterizations/vertical/MOM_bulk_mixed_layer.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diapyc_energy_req.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_entrain_diffusive.F90
src/parameterizations/vertical/MOM_internal_tide_input.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_opacity.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/user/MOM_wave_interface.F90

This PR consists of three commits that eliminate 46 instances where there was a need to multiply by `US%L_to_Z` during run-time.  There are 9 instances where there are compensating additions of factors of `US%L_to_Z` to `scale` or `conversion` arguments that are used during model initialization.
The first commit introduces a newly rescaled version of the gravitational acceleration, `GV%g_Earth_Z_T2`, to the `verticalGrid_type` as a copy of `GV%g_Earth` that uses dimensional rescaling of `[Z T-2 ~> m s-2]` instead of `[L2 Z-1 T-2 ~> m
s-2]`.   `GV%g_Earth_Z_T2` is more convenient for single-column energy calculations (for which horizontal scales should be irrelevant), but the two variables will only differ by an integer power of two when dimensional rescaling is applied. This new version …

+Simplify rescaling by US%L_to_Z

---

src/core/MOM.F90

MOM6 separates dynamic and thermodynamic, or diabatic, processes and users have the option to specify a dynamic time step (`DT`) and a thermodynamic time step (`DT_THERM`).  The dynamic time step is limited by the CLF, but`DT_THERM` is not and therefore is often longer than `DT`. Tracer advection is done using accumulated fluxes from one or more dynamic steps, such that the tracers are advected for the length of a thermodynamic step.
However, in higher resolution regional domains we have found that a tracer advective CFL may be providing a practical limit on tracer advection and therefore `DT_THERM`. We also know that model results are depend on the choice of `DT_THERM` (such as in [Issue #773](https://github.com/NOAA-GFDL/MOM6/issues/733)). 
This PR introduces a new time step for tracer …

Add Option to Specify Tracer Advection Time Step

---

src/core/MOM.F90
src/diagnostics/MOM_sum_output.F90
src/framework/MOM_diag_mediator.F90
src/framework/MOM_io.F90
src/framework/MOM_io_file.F90

This PR consists of three commits, the first of which adds the ability to rescale output variables that are written by the `MOM_io_file` routines analogously to what is already available for variables that are written via `MOM_write_field()` or via `MOM_diag_mediator()`.  The second commit uses this new capability in `write_energy()` and revises the internal calculations in `write_energy()` to work almost entirely with rescaled variables.  The third commit corrects 4 conversion arguments to `var_desc()` calls now that they might actually be used.
The specific changes include the addition of a new optional conversion argument to `register_field()`, code to rescale variables in 10 `write_field()` routines, changes to `modify_vardesc()` and `query_vardesc()` to properly store and retrieve …

+Add and use optional conversion argument to register_field in MOM_io_file

---

src/parameterizations/lateral/MOM_self_attr_load.F90
src/parameterizations/lateral/MOM_tidal_forcing.F90

This PR uses the recently introduced `old_name` option in `get_param` to replace runtime parameter `TIDE_SAL_SCALAR_VALUE` with `SAL_SCALAR_VALUE` in a more elegant way.
No answer changes.

Depreciate `TIDE_SAL_SCALAR_VALUE`

---

src/core/MOM_open_boundary.F90
src/diagnostics/MOM_diagnostics.F90
src/diagnostics/MOM_sum_output.F90
src/diagnostics/MOM_wave_speed.F90
src/ice_shelf/MOM_ice_shelf_initialize.F90
src/initialization/MOM_grid_initialize.F90
src/initialization/MOM_shared_initialization.F90
src/parameterizations/vertical/MOM_bkgnd_mixing.F90

This PR consists of four commits that correct the descriptions of the units or purpose of some variables.  Specifically this PR:
- uses rescaled units for the calculation of the `volo` diagnostic
- renames a local variable to `masked_area` for greater clarity
- replaces the unused real placeholder element in `file_OBC_CS` with a logical placeholder
- corrects the syntax or substance of the descriptions of the units of 14 variables.
All solutions and output are bitwise identical, and no interfaces are changed. The specific commits in this PR include:
- NOAA-GFDL/MOM6@1b142bad1 Switched the placeholder element of file_OBC_CS
- NOAA-GFDL/MOM6@320a62fd6 Fix the syntax or substance in 10 comment units
- NOAA-GFDL/MOM6@69ba88dc2 Rename masked_area in compute_global_grid_integral
- …

Rescale volo and clean up the unit descriptions of 17 variables

---

src/parameterizations/vertical/MOM_kappa_shear.F90

- Viscosities at vertices along the coast were incorrectly zero'd out.  This commit removes that mask so the non-zero shear driven viscosities can be interpolated from in the model.  This bug caused diffusivities to be very large in channels and potentially near coastlines.
- A bugfix flag is added with an option to use the current behavior for legacy purposes.
Here is a sample shear driven diffusivity and viscosity at 50m depth in the Gibraltar region from a case with the bug flag as True:
Compared to with the fix:

Correct bug in kappa shear viscosity with vertex shear option.

---

src/user/Phillips_initialization.F90

Add the new runtime parameter PHILLIPS_ANSWER_DATE to enable the option to use mathematically equivalent expressions in `Phillips_initialize_velocity()` that exactly specify the arithmetic to be used, avoid excess divisions and permit full rescaling of the internal variables and the elimination of rescaling variables.  This new slightly answer-changing option is enabled by setting `PHILLIPS_ANSWER_DATE >= 20250101`.  For now, the default for `PHILLIPS_ANSWER_DATE` is set to 20241231 to avoid changing answers without explicitly setting it.
This commit also introduces code to use `G%grid_unit_to_L` to detect and handle various choices for the units of the `G%geolat` and `G%geolon` variables.
By default, all answers are bitwise identical, but there is a new runtime parameter in some …

+Add PHILLIPS_ANSWER_DATE runtime parameter

---

config_src/infra/FMS1/MOM_domain_infra.F90
config_src/infra/FMS2/MOM_domain_infra.F90
src/framework/MOM_io.F90
src/framework/MOM_restart.F90
src/initialization/MOM_state_initialization.F90

This PR consists of 3 commits that together will allow for simulations with grid rotation to properly read restart files and write restart files that are equivalent to those that are generated with an unrotated grid.  The restart are not identical because the FMS `field_chksum()` function is giving different answers for equivalent arrays for reasons that are not yet understood, so for now the use of the restart files with rotated grids will only work in some cases when `RESTART_CHECKSUMS_REQUIRED = False`.  The first two commits add new optional arguments to I/O related framework routines to facilitate these changes, while the third commit makes the necessary changes to `MOM_restart` and the initialization of the model from a re start file.
Added the new `zero_zeros` optional argument to …

+(*)Grid rotation now works with restarts

---

src/core/MOM_open_boundary.F90
src/parameterizations/lateral/MOM_MEKE.F90
src/tracer/MOM_hor_bnd_diffusion.F90
src/tracer/MOM_neutral_diffusion.F90
src/tracer/nw2_tracers.F90
src/user/MOM_wave_interface.F90
src/user/Neverworld_initialization.F90
src/user/basin_builder.F90

Added a description of the units of the return values to the comments describing 33 real functions in 8 modules.  Only comments are changed and all answers are bitwise identical.

Describe the units of 33 real function results

---

src/diagnostics/MOM_obsolete_params.F90
src/parameterizations/lateral/MOM_internal_tides.F90

This commit cleans up several aspects of the MOM_internal_tides code, including the elimination of one runtime option, the correction of some units in comments and a start toward enabling the propagation directions to alternate.
1. Eliminated the internal routine `propagate_corner_spread()`.  This routine was never completely implemented, and it has never been used in any realistic configurations.  In particular, it appears that it will only work on a Cartesian grid in which the position variables (`G%geoLonBu` and `G%geoLatBu`) have the same units as `G%dx`. The comment describing `propagate_corner_spread()` indicates that "it is too numerically diffusive to be of much use as of yet" and that "it is not yet compatible with reflection schemes", so we have no plans to complete its …

+Obsoleted INTERNAL_TIDE_CORNER_ADVECT

---

src/core/MOM_barotropic.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90

This PR recovers an option to use BT_CONT to calculate `dtbt` in subroutine `set_dtbt` by adding a new runtime parameter `SET_DTBT_USE_BT_CONT`. The option to use BT_CONT in `set_dtbt` previously exists but is never used. 
Currently, when `USE_BT_CONT_TYPE` is true (default), dtbt is effectively calculated using topography (i.e. with zero sea surface height).  For example, `eta` in the following call is never used as its usage requires `NONLINEAR_BT_CONTINUITY` is true,  which is by default false with  `USE_BT_CONT_TYPE`=True.
https://github.com/NOAA-GFDL/MOM6/blob/cbb8bfa8b14ea83be1aabb2cd3391df48b6ce962/src/core/MOM_dynamics_split_RK2.F90#L651
With the old setup, the model fails to correctly estimate `dtbt` when the domain has an uneven mean surface height like the Great Lakes system. …

Add option to use BT_CONT to calculate `dtbt`

---

src/framework/MOM_checksums.F90
src/framework/MOM_murmur_hash.F90

This PR adds a new module, `MOM_murmur`, that computes the MurmurHash of an input array.  The `murmur` function computes a unique 32-bit hash of an array.  Hashes are unique to a particular reordering and can also detect presence of negative zeros.  Both cases are currently undetected by current debug tests (mean/min/max/bitcount).
Hash checksums are currently disabled, since our testing reports hash differences for a few diagnostics.  It can be enabled at compile-time when needed, and we can enable this test at some later date after the offending arrays have been investigated.

MOM_murmur: MurmurHash3 implementation

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
config_src/drivers/STALE_mct_cap/mom_surface_forcing_mct.F90
config_src/drivers/nuopc_cap/mom_surface_forcing_nuopc.F90
src/core/MOM_forcing_type.F90

Revised the calculation of the `netFWGlobalAdj`, `vPrecGlobalAdj` and `saltFluxGlobalAdj` elements of the `forcing` type to work in dimensionally rescaled units, making use of the `unscale` argument to `reproducing_sum()`.  This change includes the addition of conversion factors to three `register_scalar_field` calls, and changes to the units of 15 variables to be rescaled.  A total of 27 instances of multiplication by unit conversion factors were eliminated as a part of these changes, with 15 other unit conversion factors added via `unscale` arguments.  All answers and output are bitwise identical, but there are changes to the units of three variables in a transparent type.

+Find fluxes%netFWGlobalAdj in rescaled units

---

src/core/MOM_checksum_packages.F90

`MOM_state_stats()` has been refactored to work primarily in dimensionally rescaled units using the `unscale` argument to `reproducing_sum()`.  As a result of these changes, the units of 8 variables were changed to be rescaled, and six instances of multiplication by rescaling factors were changed into `unscale` arguments.  `MOM_state_stats()` is exercised by setting `DEBUG_CONSERVATION = True`, and it has been verified that `MOM_state_stats()` gives results that are invariant to the use of dimensional rescaling.  All answers and output are bitwise identical.

Dimensional rescaling in MOM_state_stats

---

src/core/MOM_barotropic.F90
src/parameterizations/lateral/MOM_streaming_filter.F90
src/parameterizations/lateral/MOM_wave_drag.F90

Utilizing streaming band-pass filters, the frequency-dependent wave drag can be applied to the narrowband tidal velocities, instead of the broadband barotropic velocity. This allows internal wave drag to be optimized for different frequency bands independently, without affecting the low-frequency, non-tidal motions.
Also fixed the bug that Filt_accum() does not return a valid output if it is called at the corrector step.
This is the updated version of PR #722 and is implemented based on the latest code of dev/gfdl.

Frequency-dependent internal wave drag

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
src/ice_shelf/MOM_ice_shelf.F90

This is the first PR from gfdl-cryopshere group. It includes several changes related to the surface mass flux from the land to the ice sheet, `shelf_sfc_mass_flux`. It is now defined in MOM_surface_forcing_gfdl.F90 and its values are passed to `fluxes%shelf_sfc_mass_flux`. This field can be used in configurations with a static ice sheet. To accommodate that it is now registered as a diagnostic field with `CS%active_shelf_dynamics=.false.`.

Passing shelf_sfc_mass_flux to ice shelf

---

src/parameterizations/vertical/MOM_energetic_PBL.F90

Corrected the indenting in most of the lines of ePBL_column to respect the MOM6 2-space indenting convention, and eliminated the comment explaining why the incorrect indenting had previously been retained to facilitate the review of a pull request with substantial actual changes in this routine.  Apart from a single comment that was removed, only white space is changed, and all answers are bitwise identical.
(When reviewing the code changes in this pull request, I recommend the use of the "Hide whitespace" setting!)

Correct indenting in ePBL_column

---

src/diagnostics/MOM_diagnose_MLD.F90

For COBALTv3 we want to save the mixed layer depth from `diagnoseMLDbyDensityDifference` or `diagnoseMLDbyEnergy`. This PR adds an optional argument to pass the MLD out of these routines. 
This should have no impact on answers or require changes in other parts of the code.
CC: @yichengt900

Add MLD_out to diagnose MLD

---

src/core/MOM_variables.F90
src/parameterizations/vertical/MOM_kappa_shear.F90
src/parameterizations/vertical/MOM_set_viscosity.F90
src/parameterizations/vertical/MOM_vert_friction.F90

This PR refactors a few random lines in vertical viscosity. 
* Remove an unused parameter `Prandtl_turb` in `vertvisc_type`, which also allows the said parameter documented in the correct section in MOM_parameter_doc
* In subroutine `set_viscous_BBL`, move and merge two instances of `u2_bg` calculation to avoid redundancy and if-branch within do-loops.
* In subroutine `set_viscous_BBL`, add a comment on explaining the reason to reset Ray_[uv]
* In subroutine `find_coupling_coef`, replace an if-branch with min()
This PR does not change answers. 
05b1e065abf874b044b9865058ffb0f4bd1e4284: Remove Prandtl_turb from vertvisc_type
d63ea3bca1df34276004608143f51b2fd70a374f: Minor changes to vertical viscosity

A few minor changes in vertical viscosity 

---

src/core/MOM_barotropic.F90
src/core/MOM_boundary_update.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_open_boundary.F90
src/tracer/MOM_tracer_advect.F90

Just the non-rotational parts of PR #752 for now.

Fix interior obcs

---

src/core/MOM.F90

This PR will move the regridding and remapping routines out of the step_MOM_thermo. This is for two reasons: (1) these routines are not related to stepping the thermodynamics and (2) this change will allow a separate timestep for regridding and remapping. 
These changes were mostly straightforward but some routines in step_MOM_thermo after the ALE block were rearranged and moved into another new routine.
These code changes did not change answers in the Baltic 0.25 degree example case. They should be tested in layer mode and with particles before these changes are accepted. It also did not change the diagnostics saved in my Baltic 0.25 degree example, but diagnostics should also be checked carefully. 
Commit:
Move regridding, remapping, and subsequent processes into a new routine …

Move Regridding and Remapping Out of step_MOM_thermo

---

src/core/MOM_barotropic.F90

In Boussinesq mode the eta below bathyT warning includes the location, but in non-Boussinesq mode the corresponding negative eta warning does not.
Added the location to the negative eta warning.
No answers are changed.

Update btstep negative eta warning

---

src/user/Kelvin_initialization.F90

This commit takes the first steps toward correcting problems with the Kelvin initialization code, including making the OBC nudging timescale an explicit parameter and adding a number of comments identifying concerns and suggesting possible improvements with the code that is used when `KELVIN_WAVE_MODE > 0`. This commit includes the introduction of the new runtime parameter `KELVIN_WAVE_VEL_NUDGING_TIMESCALE`, with a default value set to recover the current hard-coded answers.  A new warning message cautions about the suspected problems with the internal wave version of the code.  By default, all answers are bitwise identical in the 4 Kelvin wave test cases that can be found at github.com/ESMG/ESMG-configs, but there is a new parameter in the MOM_parameter_doc.all files these cases.

+Steps to correct Kelvin_initialization issues

---

src/parameterizations/vertical/MOM_kappa_shear.F90

- Update to horizontal averaging procedure in MOM_kappa_shear for VERTEX_SHEAR = True.
- Adds geometric and thickness weighted averages for moving diffusivity from vertices to tracer points.
- Adds new diagnostics of N2, S2, Kd, and TKE both with and without VERTEX_SHEAR, useful for debugging.
- Bitwise reproduces OM5 config w/ VERTEX_SHEAR = True.

Updates MOM_kappa_shear averaging and diagnostics.

---

src/user/Kelvin_initialization.F90

- Takes care of first two problems in issue #848.
- It now runs with amplitude of 0.5.

*Improvements to internal Kelvin wave

---

src/core/MOM.F90

A new parameter, INTERFACE_FILTER_DT_BUG, is added to fix two bugs in
the time interval passed to interface_filter and to thickness_diffuse.
This parameter has no effect, and is not read or logged, when
THICKNESSDIFFUSE_FIRST is true and DT_TRACER_ADVECT = DT_THERMO or
when both THICKNESSDIFFUSE_FIRST and APPLY_INTERFACE_FILTER are false.
Its default is false which will change answers in the rare existing cases
with the bug.  In such cases, the original answers can be restored by
setting INTERFACE_FILTER_DT_BUG to true.
In addition, a missing calc_derived_thermo call has been added:
In non-Boussinesq mode, calc_derived_thermo needs to be called before
diag_update_remap_grids.  Commit 23b2049 appears to require an extra call.
Without the call, MOM6 issues a FATAL error message.

Add INTERFACE_FILTER_DT_BUG

---

src/core/MOM_barotropic.F90

(edited to correct the names of the new routines)
This PR moves some parts of `btstep()` into subroutines:
- `btstep_ubt_from_layer`
- `btstep_find_Cor`
- `truncate_velocities`
- `btloop_eta_predictor`
- `store_u_for_OBCs` and `store_v_for_OBCs`
- `btloop_update_v`
- `btloop_update_u`
- `btstep_layer_accel`
This eliminates the duplication of the u and v update code in the bt loop, but preserves the `BT_USE_OLD_CORIOLIS_BRACKET_BUG` in the update when v is done second.
The creation of these subroutines should not change answers. I have tested it in the Baltic OM4 0.25 case with `BT_USE_OLD_CORIOLIS_BRACKET_BUG`  both `True` and `False`.
Each routine has many arguments and I have tried to correctly label them `intent(in)` or `intent(inout)` as appropriate. Some variables did not have clear …

Move some parts of btstep() into subroutines

---

src/core/MOM_open_boundary.F90

See [CEFI-regional-MOM6 issue 154](https://github.com/NOAA-GFDL/CEFI-regional-MOM6/issues/154)
The current error message when an OBC file name is incorrect or the file is missing is not clear. This PR adds to the existing error message to give two more possible reasons the error may be triggered.

Expand error message when OBC files are missing

---

src/diagnostics/MOM_diagnostics.F90

- cmor names were missing for the temp/salt output fields when using conservative temperature and absolute salinity.  This PR adds them.

Adding cmor names for temp and salt in MOM_diagnostics

---

config_src/drivers/FMS_cap/MOM_surface_forcing_gfdl.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_TEOS10.F90

This PR addresses  issue #852.
- The model restores its salinity directly toward the provided dataset.  If the dataset was in practical salinity and the model absolute, there was no conversion and hence the wrong restoring flux was used.
- This commit adds an option to convert the dataset salinity to absolute salinity if the model is absolute and the dataset is practical.
- This commit does not provide the opposite capability, since I'm unaware of that issue being encountered.

Add salt restore conversion option

---

src/parameterizations/lateral/MOM_hor_visc.F90

This reorders several if-blocks inside of a large do-loop of horizontal_viscosity() associated with rescaled Kh.
This should help performance, but will also make it easier to move these loops to GPU.

Horvisc: Reorder if-blocks in rescaled Kh

---

src/framework/MOM_diag_mediator.F90

The output of the current `available_diags` file lacks the dimensions of each diagnostic.
This PR includes a commit that adds the appropriate horizontal and vertical dimension names to the entries listed in the available_diags file. Scalar diagnostics are denoted with a "scalar" string.
Example of an entry generated with the new code:
```
"temp"  [Used] (CMOR equivalent is "thetao")
! modules: {ocean_model,ocean_model_z,ocean_model_rho2,ocean_model_rho0,ocean_model_d2,ocean_model_z_d2,ocean_model_rho2_d2,ocean_model_rho0_d2}
! dimensions: yh, xh, zl
! long_name: Potential Temperature
! units: degC
! cell_methods: xh:mean yh:mean zl:mean area:mean
! variants: {temp,temp_xyave,thetao,thetao_xyave}
```

Add variable dimensions to available_diags file

---

.testing/Makefile
.testing/tools/compare_perf.py

This fixes the path for the optimized target builds (opt_target) used in
the profiling tests.  Previously they were pointing to the wrong
directories and were never built.
Due to oddities of rule order and overrides, the optimized targets were
using the latest code.  That is, **the perf tests were being run against
themselves**.
The perf and profile rules now correctly compare optimized output to the
optimized target output (typically dev/gfdl).
This PR also contains a minor improvement to the perf comparison script output.

.testing: Fix optimized target paths

---

.gitlab-ci.yml

Issues with the cray-libsci module have caused issues with the Intel C compilers on Gaea.  This patch unloads the cray-libsci module and restores access to the C compiler.

Disable cray-libsci for Intel in Gitlab .testing

---

src/core/MOM_barotropic.F90

Replaced the 8 Coriolis parameter arrays (`[abcd]zon` and `[abcd]mer`) with merged 3-dimensional arrays (`f_4_u` and `f_4_v`), where the extra dimension is of size 4 and varies fastest.  This reduces the number of arguments being passed around and it could improve performance by increasing the likelihood of cache hits. Also made the `dgeo_de` argument to `set_up_BT_OBC()` non-optional, which reduces the number of calls to this routine and should increase the chances it might be inlined.  A few more spelling errors were corrected, and some notes added in comments highlighting potentially suspect reassignments of effective total gravities at open boundary condition points.  All answers are bitwise identical and no external interfaces are changed.

Add merged Coriolis arrays in MOM_barotropic

---

src/framework/_Horizontal_indexing.dox

This tiny PR fix some typos in the MOM6 documentation when illustrating the index for v-point.
The current doc with the typo is at (https://mom6.readthedocs.io/en/main/api/generated/pages/Horizontal_Indexing.html)
Under Section "Soft convention for loop variables", the reference for v-point is incorrect. See the screenshot here:
The later one should be v(i,J-1) and \f$v_{i,j-\frac{1}{2}}\f$
As suggested by @marshallward , Submit PR here instead of the repo `mom-ocean`

Fix the incorrect index for v-point in the doc

---

src/core/MOM.F90
src/diagnostics/MOM_debugging.F90

Refactored `totalTandS()` and `totalStuff()` to optionally work with scaled variables, by adding an optional `unit_scale_type` argument and a optional argument specifying the unscaling of thickness to `totalTandS()` and an optional `unscale` argument to `totalStuff()`.  The comments describing the units of 19 variables were modified to reflect the various units that might be used.  All solutions are bitwise identical, and output is unchanged when dimensional rescaling is not being used, but the debugging output can now be unaltered by the use of dimensional rescaling.  There are new optional arguments to two publicly visible routines.
This change has been tested via calls to `totalTandS()` added to `step_MOM_thermo()`, but because `totalTandS()` is only intended for debugging, these …

+Refactor totalTandS to optionally work with scaled variables

---

src/diagnostics/MOM_diagnose_KdWork.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

This is about half of the work needed for issue #816 .
This PR adds a new routine to compute KdWork (the buoyancy flux and its integral) based on N2 and Kd.  When provided with N2 at the end of dt_therm in adiabatic_ALE it diagnoses the implied work done by Kd and can split this work into the various processes that contribute to Kd.  It splits N2 into salinity and temperature to enhance the information provided by the diagnostic and for diffusivity that is different for heat and salt (e.g. double diffusion).  It also allows the total N2 and the salinity and temperature contributions to N2 to be diagnosed and output, which is also useful since all other N2 diagnostics in the model are floored at 0.
It should not be expected to work with KPP, since KPP's nonlocal flux requires additional …

Kd work and buoyancy flux diagnostics

---

.testing/Makefile
.testing/tools/cmp_diag.sh
.testing/tools/diff_diag.sh
src/framework/MOM_diag_mediator.F90

This PR has two commits:
* A timestamp is appended to the checksum output of chksum_diag, to facilitate sorting.
* CI testing sorts this output in order to eliminate false-negative diagnostic regressions.
Since it changes the `chksum_diag` files, there will be a regression.  But it should not propagate to future runs.  It may, however, propagate to other forks, such as MOM-ocean.

Chksum diag timestamp

---

src/core/MOM_PressureForce.F90
src/core/MOM_PressureForce_FV.F90
src/core/MOM_barotropic.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_dynamics_unsplit.F90
src/core/MOM_dynamics_unsplit_RK2.F90
src/core/MOM_variables.F90
src/diagnostics/MOM_diagnostics.F90

This PR adds a series of new diagnostics in both barotropic solver and pressure force modules. There is no answer change.
Currently, the kinetic energy budget is as follows:
`dKE_dt` = `KE_Coradv` + `PE_to_KE` + `KE_BT` + `KE_visc` + `KE_horvisc`
While this expression is algebraically correct, the physical meaning of some individual terms can be obscure.  
1. `KE_BT` is from the total acceleration from barotropic solver that includes anomalous pressure force, anomalous Coriolis force and when (tidal) linear wave drag is used, a barotropic wave drag term. In other words, this term has a well-defined numerical meaning but not a physical one.
2. `PE_to_KE` is from `PF[uv]` in PressureForce module, which also includes the acceleration from tidal forcing and SAL. 
New diagnostics are added to …

Add new terms to kinetic energy diagnostics

---

src/core/MOM_barotropic.F90

Restore the parentheses to the expressions for `Cor_v` in `btloop_update_v()` so that the model will once again respect rotational symmetry when fused-multiply-adds are enabled.  These parentheses were in the corresponding expressions until PR #845 to dev/gfdl when they were inadvertently omitted. This commit changes answers (and restores rotational symmetry) when fused-multiply-adds are enabled.

*Restore Cor_v parentheses for symmetry with FMAs

---

src/core/MOM_barotropic.F90

Added code to zero out `bt_pgf_u` and `bt_pgf_v` at open boundary condition points, thereby altering the pressure diagnostics that are derived from these arrays. At OBCs, the pressure force is not well defined, and in fact the `u_accel_bt` and `v_accel_bt` arrays upon which recently added calculation of `bt_pgf_u` and `bt_pgf_v` are based is immediately replaced by a different OBC-specific expression for the accelerations at OBC points.  Moreover, at OBC points `bt_pgf_u` and `bt_pgf_v` were being calculated using values of `eta_anom` that were projected outward across OBCs, but where this means that two different OBCs could be trying to set these projected values of `eta_anom` to two different values (e.g, at a convex corner in OBC segments or at back-to-back OBC segments separated by a …

Zero out bt_pgf_u at OBC points

---

src/core/MOM_barotropic.F90

This series of 9 commits extensively refactors the code in MOM_barotropic for simplicity and efficiency, with a particular emphasis on reducing the cost of the open boundary condition code and using simpler subsidiary routines within the barotropic time stepping loops.
The open boundary condition code that is called from inside of `btstep_timeloop()` no longer uses the indirectly referenced segments in the OBC type to determine the location, direction and kind of open boundary conditions, instead using two new arrays (`u_OBC_type` and `v_OBC_type`) in the local `BT_OBC_type` to specify the kind of OBC point with their absolute value while their signs indicate the direction.  The OBC code in the barotropic timestepping is only called now if there is an OBC segment on the PE, and the loop …

Refactor barotropic time stepping and OBC code

---

src/core/MOM_barotropic.F90
src/parameterizations/vertical/MOM_tidal_mixing.F90

This PR consists of two PRs to fix problems with the recent pull request from dev/gfdl to main.
The first commit addresses the problem that Kd_itides was not set for the VBF diagnostic because it mistakenly checked if Kd_itidal was associated. The note in the code to not confuse Kd_itides with Kd_itidal has been confirmed by the problem this commit addresses. Code was also added to work with Polzin option in MOM_tidal_mixing.
The second commit adds additional logic to avoid segmentation faults from applying Flather open boundary conditions near the opposite side of the computational domain (e.g., applying a Northern Flather boundary condition on the southern edge of the domain). This situation does not arise when open boundaries are only found on the edges of a domain, but in parallel …

Irregular obc fix and VBF diagnostis for tidal Kd term bug fix

---

src/core/MOM_barotropic.F90

Added additional logic to avoid segmentation faults from applying Flather open boundary conditions near the opposite side of the computational domain (e.g., applying a Northern Flather boundary condition on the southern edge of the domain).  This situation does not arise when open boundaries are only found on the edges of a domain, but in parallel cases with sloped OBCs (such as the ESMG-configs rotated seamount test case) this atypical situation can arise.  The key point to the specific fix is to note that when such a case arises, the OBC velocity in the outer halo point does not subsequently impact the solution on that PE either because its effects are masked out by land or OBC points at the neighboring orthogonal velocities, and then they are overwritten by a halo update (perhaps …

(*)Fix northern Flather OBCs in southern halos

---

src/core/MOM_forcing_type.F90

Keep 5 recently added area integrated surface mass or heat flux diagnostics in `forcing_diagnostics()` in rescaled units by replacing an `unscale` argument with a `tmp_scale` argument to `global_area_integral()`.  Also added the corresponding conversion arguments to the `register_scalar_field()` calls for each of these diagnostics, so that the documented units and conversion factors can be used to confirm the correctness of the documented units for these variables.  The appropriate internal temporary variables for the integrated heat or mass fluxes were also used for clarity about the units of these variables.  Benign `conversion=1.0` arguments were added to another 8 `register_diag_field()` calls for nondimensional forcing variables.  All answers and diagnostics are bitwise identical.

Diagnose more integrated fluxes in rescaled units

---

src/core/MOM_forcing_type.F90
src/core/MOM_grid.F90
src/user/RGC_initialization.F90
src/user/dumbbell_initialization.F90

Corrected the descriptions of the units of two `I_rho` variables in `find_ustar_fluxes()` and `find_ustar_mech_forcing()` and of the `lensponge` internal variable in `RGC_initialize_sponges()`.  Also corrected the comments describing the locations of `grid%geolatT` and `grid%geolonT`.  Also refactored `dumbbell_initialize_thickness()` to use `geoLonT` or `geoLatT` directly rather than setting a temporary variable with ill-defined units that is only used once. Only changes in comments or very simple code logic changes are included in this commit, and all answers are bitwise identical.

Correct variable units in comments in 4 modules

---

src/diagnostics/MOM_debugging.F90
src/tracer/MARBL_tracers.F90
src/tracer/MOM_hor_bnd_diffusion.F90

Replaced 14 `scale` arguments in recently added `checksum()` calls with the preferred `unscale` argument, following the pattern used elsewhere throughout the MOM6 code.  These two arguments are functionally equivalent, but `unscale` makes it easier to identify implausible combinations of scaling factors.  All answers are bitwise identical.

Replace checksum scale arguments with unscale

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90

The MASK_OUTSIDE_OBCS flag doesn't know about the MASKING_DEPTH and this should take care of the problem.

 Fix for MASK_OUTSIDE_OBCS with MASKING_DEPTH

---

src/core/MOM.F90
src/equation_of_state/MOM_EOS.F90
src/equation_of_state/MOM_EOS_TEOS10.F90

The current code won't allow running with the TEOS10 or Roquet equation of state with a linear freezing temperature.  While the TEOS10 and Roquet equation of states were not designed for linear freezing point equations, there are valid cases where a user may desire to use a linear freezing point equation.  For example, SIS2 only uses a linear freezing point equation, so it may be preferred to use MOM6 with the same equation as SIS2.  Therefore, this PR suggests to change the FATAL error to a WARNING.

 Add flexibility for TFreeze form w/ different model definition of temp/salt

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90

Fixed a bug that was causing some open boundary condition fields (e.g., those related to the tides) not to be read in from files before they are used unless there are some PEs that do NOT include any input date based OBC points.  This bug causes certain configurations with not to reproduce across PE count.  Most high-PE count jobs (those with at least 3 PEs in each direction) previously were correct, but single PE jobs or jobs with a prime number or 2 times a prime number of PEs were never correct for these cases.  Specifically, this commit removes the `some_need_no_IO_for_data` element from the `ocean_OBC_type`, and it always calls `update_OBC_segment_data()` during initialization when any OBCs are being used.  It also replaces three calls to `allocate_rotated_array()` with calls to the …

*Fix PE-count dependency with some kinds of OBCs

---

src/core/MOM.F90
src/core/MOM_boundary_update.F90
src/core/MOM_dynamics_split_RK2.F90
src/core/MOM_dynamics_split_RK2b.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90

This PR consists of three commits that add diagnostic capabilities the to help diagnose the models' (in)ability to rotate (single-processor) configurations that use open boundary conditions and obtain bitwise identical solutions.  
The changes include the introduction of the new publicly visible routines `write_OBC_info()` and `chksum_OBC_segments()` that write extensive debugging information about the OBC fields, and which were used to identify the various bugs that will be corrected in a subsequent pull request.  Calls to these routines are enabled via the new runtime parameters `DEBUG_OBCS` and`NK_OBC_DEBUG`. The new function `rotate_OBC_segment_direction()` is now available to convert the directions of OBC segments when there is grid rotation.
A fatal error message that previously …

+OBC grid rotation debugging code

---

src/core/MOM_open_boundary.F90

This PR consists of two commits that implement the ability to rotate (single-processor) configurations that use open boundary conditions and obtain bitwise identical solutions.  It adds a new runtime option (`OBC_HOR_INDEXING_BUG`) to correct a group of 5 horizontal indexing bugs that will change answers with OBCs, even when the solution is not rotated.  Several other bugs that led to segmentation faults when the grid index rotation is enabled with OBCs were also corrected by setting the requisite pointers and copying missing data between rotated and unrotated OBC types.
The specific answer changing bugs that are corrected by setting `OBC_HOR_INDEXING_BUG` to false are 4 instances where the wrong horizontal indices are used in the input buffer when reading in velocity-point data from a …

+(*)Correct OBC indexing bugs and errors with OBC grid rotation

---

src/core/MOM_boundary_update.F90
src/user/dyed_channel_initialization.F90

When there are specified open boundary conditions, `dyed_channel_update_flow()` was setting the normal transport with the wrong units of [L2 T-1 ~> m2 s-1] instead of [H L2 T-1 ~> m3 s-1 or kg s-1], effectively omitting the layer thickness in the transports.  This has been corrected by adding the new runtime parameter `CHANNEL_FLOW_OBC_TRANSPORT_BUG` that either uses a fixed thickness if true (of 1 m or 1 kg m-2) or the actual interior thickness.  In either case, the model is now passing the dimensional consistency testing.  This change requires a new layer thickness argument to  `dyed_channel_update_flow()`.  In addition, code was added to `dyed_channel_update_flow()` so that it also satisfies rotational consistency.  By default, answers are bitwise identical when no dimensional …

+(*)Fix bugs with dyed_channel_update_flow

---

src/user/tidal_bay_initialization.F90

Modified tidal_bay_set_OBC_data to work properly with grid rotation of 90, 180 or 270 degrees.  With these changes the ESMG Tidal_bay test case is now giving bitwise identical answers under grid rotation.  This commit also corrects a
recently added problem with potentially unallocated arrays being used to test whether a pointer is set to the unrotated tracer reservoirs in cases where there are no tracers.  This commit does change (and fix) answers when grid rotation is used, but answers are bitwise identical when there is no grid rotation, and there are no changes to any public interfaces.

(*)tidal_bay_set_OBC_data works with grid rotation

---

src/core/MOM_barotropic.F90

Corrected the previous PE-count and layout dependency of answers for cases with open boundaries are not at the natural edges of the domain by storing the previous barotropic velocities in `ubt_prev` and `vbt_prev` over a wider range of loop indices, and by increasing the stencil size used in `btstep_timeloop()` in such cases.  Because the required loop range no longer matches the range over which the new velocities are set in `bt_loop_update_u()` and `bt_loop_update_v()`, the code setting these arrays has been moved out of these routines and into the main body of `btstep_timeloop()`.  This commit will change answers (and make them invariant to the PE count and layout) in some cases, such as the ESMG-configs Kelvin_wave/rotate45_BT and Kelvin_wave/rotate_BT test cases, where there are …

*Fix PE-layout reproducibility with interior OBCs

---

.testing/Makefile

This changes the default version of FMS in `.testing`.
Although this won't affect regression testing (which defines its own version of FMS), it is still worth verifying that our automated .testing builds work correctly before merging.

GitHub: Update FMS CI version to 2025.02.01

---

src/core/MOM.F90
src/core/MOM_variables.F90
src/parameterizations/vertical/MOM_diabatic_aux.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90

Frazil may need an extra halo pass, but only when all of the following are true: 
(1) frazil is calculated and applied in the halo (e.g., vertex_shear is true) 
(2) the thermodynamic loop is called more than once before passing frazil to the sea-ice (dt_therm<dt_cpld) 
(3) reclaim_frazil is true
(4) a previous make_frazil was called after the diabatic loop and before T&S were updated in halos.
This commit adds the halo pass inside make_frazil since it is where we can know all of these conditions at once.  We needed to add a flag to know if frazil was reset (which happens every timestep if dt_therm>=dt_cpld), in which case the halo pass would be unnecessary.  We needed an optional argument for make_frazil so we could flag to only do this update on the first call to make_frazil (which is …

Add conditional halo pass for frazil inside make_frazil

---

src/core/MOM.F90
src/core/MOM_open_boundary.F90
src/initialization/MOM_state_initialization.F90
src/user/Kelvin_initialization.F90
src/user/supercritical_initialization.F90

This PR consists of a series of 8 commits that simplify the calls used to initialize the OBCs, including initializing the OBCs directly on the rotated grid when grid rotation is in use.  This includes moving the code that initializes the OBCs out of `MOM_initialize_state()` and into the new subroutine `MOM_initialize_OBCs()`.  The code that sets up the OBCs was rearranged and consolidated into fewer blocks of code, including the combination of the functionality that had previously been provided by the separate OBC routines into other closely related routines and the elimination of some functionality that is no longer need with this simpler structure.  As a result, the publicly visible OBC interface to `rotate_OBC_init()`, `set_tracer_data()` and `open_boundary_setup_vert()` were …

+Rotated and simpler OBC initialization

---

src/diagnostics/MOM_diagnose_KdWork.F90
src/diagnostics/MOM_diagnose_MLD.F90
src/parameterizations/vertical/MOM_diabatic_driver.F90
src/parameterizations/vertical/MOM_energetic_PBL.F90
src/parameterizations/vertical/MOM_geothermal.F90
src/parameterizations/vertical/MOM_set_diffusivity.F90

**Fix issues in MOM_diagnose_KdWork logic**
- Fix missing allocation logic for diffusivities needed by idz variables.
- Fix a logic mistake cross-up of ePBL diagnostic id that should have been bkgnd diagnostic id
**Adds code to compute ePBL BBL mstar**
- Adds output of buoyancy flux from geothermal routine, needed for computing bottom mstar.
- Adds capability into ePBL to use mstar coefficient in BBL, including options to specify the same or different as the surface scheme
**Adds code to generalize energy based mixed layer depth for bottom up mixed layer diagnostic**
- Generalizes code to work moving up or down the column
- Adds flag to preserve OM4 solution, should be the same at round-off (may be able to recover the same bitwise answers, but it needs some testing)

Add ePBL BBL mstar and bottom mixed layer diagnostics

---

src/parameterizations/lateral/MOM_internal_tides.F90

- Solve the issue of rays not propagating through the northfold: the
use of pass_vector for speed_[x/y] is not appropriate since these arrays
are meant to be scalar and the direction is contained in the angle dimension
of energy. changing to regular pass_var at the appropriate cell location fixes it
- The energy gets trapped at critical latitude: this PR introduces 2 options for
energy propagation, either propagate along the critical latitude or reflect on it.
These are controlled by TURN_CRITICAL_LAT (False: get trapped, True: do something)
and REFLECT_CRITICAL_LAT (True: reflect like a solid wall, False: propagate along)
Although the correct physical behavior is to both do something and reflect, keeping the
other options available is useful for debugging.
- Several divisions by constant …

(*) Multiple fixes for the ray tracing
